p2p-org/key-app-android

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/UserTokensPolling.kt, app/src/main/java/org/p2p/wallet/swap/SwapModule.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/interactor/SwapTokensInteractor.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapContract.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidget.kt, app/src/main/res/layout/fragment_jupiter_swap.xml
https://p2pvalidator.atlassian.net/browse/PWN-7472
https://p2pvalidator.atlassian.net/browse/PWN-7453
PWN-7472 - Token filtering improved
PWN-7453 - Keyboard for swap screen
NO-TICKET - Added debug routes info to the main swap screen
=> PWN-7472 - Additional fixes for Swap

app/src/main/res/layout/fragment_jupiter_swap.xml
=> NO-TICKET - Debug info position

app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/presenter/SwapTokensCommonMapper.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/icon_wrapper/IconWrapperCellModel.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/icon_wrapper/UiKitIconWrapper.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/right_side/RightSideCellModel.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/right_side/UiKitRightSideView.kt, ui-kit/src/main/kotlin/org/p2p/uikit/utils/text/TextViewCellModel.kt, ui-kit/src/main/res/layout/widget_right_side_icon_wrapper.xml
https://p2pvalidator.atlassian.net/browse/PWN-7113
new type for right side of finance block. Delete TextBadge
=> PWN-7113 - new type for right side of finance block. Delete TextBadge

app/src/main/java/org/p2p/wallet/swap/jupiter/api/SwapJupiterApi.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/api/response/CreateSwapTransactionResponse.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/JupiterSwapPair.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/repository/routes/JupiterSwapRoutesRemoteRepository.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/repository/transaction/JupiterSwapTransactionMapper.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateRoutesRefresher.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/adapter/SwapTokensARoundedItemDecoration.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/adapter/SwapTokensBRoundedItemDecoration.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/finance_block/FinanceBlockViewHolder.kt
https://p2pvalidator.atlassian.net/browse/PWN-7519
=> PWN-7519 - New swap. Fixes

app/proguard-rules.pro
https://p2pvalidator.atlassian.net/browse/PWN-7343
=> PWN-7343 - Fix bug with BKS provider

app/src/main/java/org/p2p/wallet/swap/ui/jupiter/info/SwapInfoMapper.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/mapper/SwapWidgetMapper.kt, app/src/main/res/layout/fragment_jupiter_swap.xml, ui-kit/src/main/kotlin/org/p2p/uikit/utils/text/TextViewCellModel.kt
https://p2pvalidator.atlassian.net/browse/PWN-7113
fix price impact, add multiline support
=> PWN-7113 - fix price impact, add multiline support

app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapState.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateManager.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/rate/SwapRateTickerManager.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapContract.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt, app/src/main/res/layout/fragment_jupiter_swap.xml
https://p2pvalidator.atlassian.net/browse/PWN-7484
swap fullscreen error
=> PWN-7484 - swap fullscreen error

app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensAdapter.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensContract.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensFragment.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensMapper.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensPresenter.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/ERC20Tokens.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/icon_wrapper/IconWrapperCellModel.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/icon_wrapper/UiKitIconWrapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-7380
PWN-7380 - make receive tokens list on UiCells
=> PWN-7380 - make receive tokens list on UiCells

app/src/main/java/org/p2p/wallet/common/analytics/AnalyticsModule.kt, app/src/main/java/org/p2p/wallet/swap/SwapModule.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/analytics/JupiterSwapMainScreenAnalytics.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/analytics/JupiterSwapSettingsAnalytics.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/analytics/JupiterSwapTransactionDetailsAnalytics.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/routes/SwapSelectRoutesBottomSheet.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/routes/SwapSelectRoutesMapper.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/settings/JupiterSwapSettingsFragment.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/settings/presenter/JupiterSwapSettingsPresenter.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/SwapTokensFragment.kt, app/src/main/java/org/p2p/wallet/transaction/ui/JupiterTransactionProgressBottomSheet.kt
https://p2pvalidator.atlassian.net/browse/PWN-7225
=> PWN-7225 - New swap. Analytics part 2

app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapContract.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-7453
swap show keyboard
=> PWN-7453 - swap show keyboard

ui-kit/src/main/kotlin/org/p2p/uikit/utils/recycler/AdapterExtensions.kt, ui-kit/src/main/kotlin/org/p2p/uikit/utils/recycler/CustomBaseAdapter.kt, ui-kit/src/main/kotlin/org/p2p/uikit/utils/recycler/decoration/EightPxOffsetDecoration.kt, ui-kit/src/main/kotlin/org/p2p/uikit/utils/recycler/decoration/GroupedRoundingDecoration.kt, ui-kit/src/main/kotlin/org/p2p/uikit/utils/recycler/decoration/OffsetByCellDecoration.kt, ui-kit/src/main/kotlin/org/p2p/uikit/utils/recycler/decoration/OnePxDividerDecoration.kt, ui-kit/src/main/kotlin/org/p2p/uikit/utils/recycler/decoration/RoundingByCellDecoration.kt
https://p2pvalidator.atlassian.net/browse/PWN-7526
default item decoration
=> PWN-7526 - default item decoration

app/src/main/java/org/p2p/wallet/auth/AuthModule.kt, app/src/main/java/org/p2p/wallet/auth/interactor/AuthLogoutInteractor.kt, app/src/main/java/org/p2p/wallet/infrastructure/swap/JupiterSwapStorage.kt, app/src/main/java/org/p2p/wallet/infrastructure/swap/JupiterSwapStorageContract.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/token_selector/CommonSwapTokenSelector.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/token_selector/PreinstallTokenASelector.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/token_selector/SwapInitialTokenSelector.kt
https://p2pvalidator.atlassian.net/browse/PWN-7538
=> PWN-7538 - New swap. Fix preselect tokens

app/src/main/java/org/p2p/wallet/infrastructure/network/NetworkModule.kt, app/src/main/java/org/p2p/wallet/relay/RelayRemoteRepository.kt, app/src/main/java/org/p2p/wallet/relay/RelayRepository.kt, app/src/main/java/org/p2p/wallet/rpc/api/RpcBlockhashApi.kt, app/src/main/java/org/p2p/wallet/rpc/repository/blockhash/RpcBlockhashRemoteRepository.kt, app/src/main/java/org/p2p/wallet/rpc/repository/blockhash/RpcBlockhashRepository.kt, app/src/main/java/org/p2p/wallet/sdk/facade/RelaySdkFacade.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/api/SwapJupiterApi.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/api/request/CreateSwapTransactionRequest.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/interactor/JupiterSwapInteractor.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/repository/model/JupiterSwapRoute.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/repository/routes/JupiterSwapRoutesMapper.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/repository/transaction/JupiterSwapTransactionMapper.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateRoutesRefresher.kt, app/src/main/res/values/environment_config.xml, solana/src/main/java/org/p2p/solanaj/model/types/RecentBlockhashResponse.java
https://p2pvalidator.atlassian.net/browse/PWN-7533
https://p2pvalidator.atlassian.net/browse/PWN-7541
- removed recent_blockhash from SDK request
=> PWN-7533 - New Swap. Proxy backend

app/src/main/java/org/p2p/wallet/swap/SwapModule.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/interactor/model/SwapTokenModel.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapFeatureException.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/handler/SwapStateTokenAZeroHandler.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/validator/MinimumSolAmountValidator.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/mapper/SwapButtonMapper.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/internal/spv/core/storage/SpvDatabase.kt
https://p2pvalidator.atlassian.net/browse/PWN-7142
=> PWN-7142 - Min SOL balance case

app/src/main/java/org/p2p/wallet/common/ui/bottomsheet/BaseBottomSheet.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/info/SwapInfoMapper.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/mapper/SwapWidgetMapper.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/settings/presenter/SwapContentSettingsMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-7542
https://p2pvalidator.atlassian.net/browse/PWN-7559
https://p2pvalidator.atlassian.net/browse/PWN-7560
PWN-7559 - Liquidity fee bottom sheet fixes
PWN-7560 - Other bottom sheets fixed
=> PWN-7542 - Minor ticker corrections

app/src/main/java/org/p2p/wallet/swap/jupiter/interactor/JupiterSwapInteractor.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-7577
=> PWN-7577 - New swap. Use already existed transaction

app/src/main/java/org/p2p/wallet/infrastructure/StorageModule.kt, app/src/main/java/org/p2p/wallet/infrastructure/swap/JupiterSwapStorage.kt, app/src/main/java/org/p2p/wallet/infrastructure/swap/JupiterSwapStorageContract.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/repository/tokens/JupiterSwapTokensInMemoryRepository.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/repository/tokens/JupiterSwapTokensLocalRepository.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/repository/tokens/JupiterSwapTokensRemoteRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-7555
=> PWN-7555 - New Swap. Cache tokens response in prefs

app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidget.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidgetModel.kt
https://p2pvalidator.atlassian.net/browse/PWN-7464
fix swap widget
=> PWN-7464 - fix swap widget

app/src/main/java/org/p2p/wallet/swap/SwapModule.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/interactor/JupiterSwapInteractor.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/interactor/SwapTokensInteractor.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapState.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateManager.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateRoutesRefresher.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/handler/SwapStateTokenANotZeroHandler.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/info/SwapInfoBottomSheet.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/routes/SwapSelectRoutesBottomSheet.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/settings/presenter/JupiterSwapSettingsPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-6960
new state for case when throw SwapException while loading
=> PWN-6960 -swap new feature state

app/src/main/java/org/p2p/wallet/common/feature_toggles/di/FeatureTogglesModule.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/EthAddressEnabledFeatureToggle.kt, app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryContract.kt, app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryFragment.kt, app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryPresenter.kt, app/src/main/java/org/p2p/wallet/home/HomeModule.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/receive/ReceiveFragmentFactory.kt, app/src/main/java/org/p2p/wallet/swap/SwapModule.kt
https://p2pvalidator.atlassian.net/browse/PWN-7535
PWN-7535 - EthAddressEnabledFeatureToggle added
=> PWN-7535 - EthAddressEnabledFeatureToggle added

app/src/main/java/org/p2p/wallet/swap/SwapModule.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/repository/routes/JupiterSwapRoutesMapper.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateManager.kt, app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/handler/SwapStateTokenANotZeroHandler.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidget.kt
https://p2pvalidator.atlassian.net/browse/PWN-7573
PWN-7573 - fix price impact and other
=> PWN-7573 - fix price impact and other

app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapContract.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-7583
swap slider fix
=> PWN-7583 - swap slider fix

app/src/main/java/org/p2p/wallet/AppCreatedAction.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/empty/PopularTokenViewHolder.kt, app/src/main/java/org/p2p/wallet/push_notifications/api/NotificationServiceApi.kt, app/src/main/java/org/p2p/wallet/push_notifications/ineractor/PushNotificationsInteractor.kt, app/src/main/java/org/p2p/wallet/push_notifications/model/DeviceToken.kt, app/src/main/java/org/p2p/wallet/push_notifications/repository/PushTokenRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-7587
=> PWN-7587 - THS endpoint fixes, empty state fixes

app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/adapter/SwapTokensARoundedItemDecoration.kt, app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/adapter/SwapTokensBRoundedItemDecoration.kt, ui-kit/src/main/kotlin/org/p2p/uikit/utils/recycler/decoration/GroupedRoundingDecoration.kt
https://p2pvalidator.atlassian.net/browse/PWN-7585
fix token B decoration
=> PWN-7585 - fix token B decoration

app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidget.kt
https://p2pvalidator.atlassian.net/browse/PWN-7589
fix amount listener
=> PWN-7589 - fix amount listener

app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt, app/src/main/res/layout/fragment_jupiter_swap.xml, app/src/main/res/layout/fragment_jupiter_swap_settings.xml
https://p2pvalidator.atlassian.net/browse/PWN-7453
swap fix keyboard
=> PWN-7453 - swap fix keyboard

app/src/main/java/org/p2p/wallet/common/ui/recycler/EndlessScrollListener.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/NetworkModule.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensContract.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensFragment.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-7380
=> PWN-7380 - Optimize token list

app/src/main/java/org/p2p/wallet/jupiter/interactor/SwapTokensInteractor.kt
https://p2pvalidator.atlassian.net/browse/PWN-7472
=> PWN-7472 - Filter fixed

app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/JupiterSwapSettingsFragment.kt
https://p2pvalidator.atlassian.net/browse/PWN-7464
cancel loading on input empty, fix crash
=> PWN-7464 - cancel loading on input empty, fix crash

app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensFragment.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensPresenter.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/dialog/SelectReceiveNetworkBottomSheet.kt, app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt, core/src/main/java/org/p2p/core/utils/Constants.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/ERC20Tokens.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/EthTokenMetadata.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/price/EthereumPriceRepository.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumKitRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-7571
PWN-7571 - update supported tokens and use them in receive + add as a first tokens in receive
=> PWN-7571 - update supported tokens and use them in receive + add as a first tokens in receive

app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt
https://p2pvalidator.atlassian.net/browse/7627
same token fix validation
=> PWN-7627 - same token fix validation

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-7571
PWN-7571 - do not pin tokens when searching
=> PWN-7571 - do not pin tokens when searching

app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/java/org/p2p/wallet/newsend/ui/stub/SendUnavailableFragment.kt, app/src/main/java/org/p2p/wallet/qr/ScanQrModule.kt, app/src/main/java/org/p2p/wallet/receive/solana/NewReceiveSolanaFragment.kt, app/src/main/res/layout/fragment_new_receive_solana.xml
https://p2pvalidator.atlassian.net/browse/PWN-7381
=> PWN-7381 - Fix receive sol MR comments

app/src/main/java/org/p2p/wallet/receive/eth/ReceiveEthereumFragment.kt, app/src/main/res/layout/fragment_ethereum_receive.xml, app/src/main/res/values/strings.xml, ui-kit/src/main/kotlin/org/p2p/uikit/components/finance_block/UiKitFinanceBlockView.kt, ui-kit/src/main/res/layout/widget_finance_block.xml
https://p2pvalidator.atlassian.net/browse/PWN-7382
=> PWN-7382 - Fix receive ethereum ui bugs

app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapFeatureException.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/validator/MinimumSolAmountValidator.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapContract.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapFragment.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/mapper/SwapButtonMapper.kt, app/src/main/res/values/swap_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-7142
swap sol error fix
=> PWN-7142 - swap sol error fix

app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/SwapContentSettingsMapper.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/SwapFeeLoader.kt
https://p2pvalidator.atlassian.net/browse/PWN-7591
swap total fee
=> PWN-7591 - swap total fee

app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/JupiterSwapSettingsPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-7663
swap fix toast
=> PWN-7663 - settings fix toast

app/src/main/java/org/p2p/wallet/auth/interactor/MetadataInteractor.kt, app/src/main/java/org/p2p/wallet/common/crashlogging/helpers/CrashHttpLoggingInterceptor.kt, app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt
https://p2pvalidator.atlassian.net/browse/PWN-7662
https://p2pvalidator.atlassian.net/browse/PWN-7658
=> PWN-7662 - New Swap. Try to catch STE

app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt
https://p2pvalidator.atlassian.net/browse/PWN-7576
swap observe on user token amount change
=> PWN-7576 - swap observe on user token amount change

app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt
https://p2pvalidator.atlassian.net/browse/PWN-7662
=> WIP: PWN-7662 - New Swap. Remove inifinite loading on startRefreshJob

app/src/main/java/org/p2p/wallet/AppModule.kt, app/src/main/java/org/p2p/wallet/bridge/send/BridgeSendModule.kt, app/src/main/java/org/p2p/wallet/bridge/send/SendFragmentFactory.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendContract.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendFragment.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt, app/src/main/java/org/p2p/wallet/newsend/analytics/NewSendAnalytics.kt, app/src/main/java/org/p2p/wallet/newsend/model/NetworkType.kt, app/src/main/java/org/p2p/wallet/newsend/model/SearchResult.kt, app/src/main/java/org/p2p/wallet/newsend/model/SearchTarget.kt, app/src/main/java/org/p2p/wallet/newsend/model/SendTokenModel.kt, app/src/main/java/org/p2p/wallet/newsend/ui/search/NewSearchFragment.kt, app/src/main/java/org/p2p/wallet/newsend/ui/search/NewSearchPresenter.kt, app/src/main/java/org/p2p/wallet/receive/ReceiveModule.kt, app/src/main/java/org/p2p/wallet/swap/SwapModule.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/utils/EthereumUtils.kt
https://p2pvalidator.atlassian.net/browse/PWN-7613
PWN-7613 - make a copy of SendFragment and use for bridges + add Ethereum validation and navigate to BridgeSendFragment if address is in Ethereum Network
=> PWN-7613 - BridgesSendFragment

app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/JupiterSwapSettingsPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-7691
non blocking settings screen
=> PWN-7691 - non blocking settings screen

ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/EthTokenConverter.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumKitRepository.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumRepository.kt, ethereumkit/src/test/java/org/p2p/ethereumkit/TokenBalancesTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-7595
=> PWN-7595 - Add ETH wallet to token claim list

app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensContract.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensFragment.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensMapper.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensPresenter.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/dialog/SelectReceiveNetworkBottomSheet.kt, app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt, app/src/main/res/layout/fragment_receive_supported_tokens.xml, app/src/main/res/values/bridges_strings.xml, ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/ERC20Tokens.kt
https://p2pvalidator.atlassian.net/browse/PWN-7380
PWN-7380 - receive fixes according to comments
=> PWN-7380 - receive fixes

app/src/main/java/org/p2p/wallet/swap/model/Slippage.kt, app/src/main/java/org/p2p/wallet/transaction/ui/JupiterTransactionProgressBottomSheet.kt, app/src/main/res/values/swap_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-7713
slippage fix text
=> PWN-7713 slippage fix text

app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapFeatureException.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/mapper/SwapButtonMapper.kt, app/src/main/res/values/swap_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-7708
small token amount error
=> PWN-7708 small token amount error

app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/interactor/JupiterSwapInteractor.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapState.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateRoutesRefresher.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/handler/SwapStateRoutesLoadedHandler.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/info/SwapInfoBottomSheet.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/routes/SwapSelectRoutesBottomSheet.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/JupiterSwapSettingsPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/SwapContentSettingsMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-7719
tokenA validation after routes load
=> PWN-7719 - tokenA validation after routes load

app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt
https://p2pvalidator.atlassian.net/browse/PWN-7721
swap fix StackOverflowError
=> PWN-7721 - swap fix StackOverflowError

app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapUserTokensChangeHandler.kt
https://p2pvalidator.atlassian.net/browse/PWN-7690
update tokenB balance
=> PWN-7690 - update tokenB balance

app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryContract.kt, app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryFragment.kt, app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/res/layout/fragment_new_receive_solana.xml
https://p2pvalidator.atlassian.net/browse/PWN-7381
PWN-7381 - fixes receive solana screen according to comments + related screens also
=> PWN-7381 - fixes receive solana screen

app/src/main/java/org/p2p/wallet/receive/eth/ReceiveEthereumFragment.kt, app/src/main/res/layout/fragment_ethereum_receive.xml, app/src/main/res/values/strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-7382
PWN-7382 - pass token symbol to show on UI correctly
=> PWN-7382 - pass token symbol to show on UI correctly

app/src/main/java/org/p2p/wallet/jupiter/repository/model/SwapFailure.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/routes/JupiterSwapRoutesRemoteRepository.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapFeatureException.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateRoutesRefresher.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-7708
=> PWN-7708 small amount error

app/src/main/java/org/p2p/wallet/common/ui/bottomsheet/BaseBottomSheet.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/info/SwapInfoBottomSheet.kt
https://p2pvalidator.atlassian.net/browse/PWN-7734
PWN-7734 - remove  setExpanded(isExpanded = true) from base bottomsheet, also do not forget to fix PWN-7559 locally
=> PWN-7734 - remove  setExpanded(isExpanded = true) from base bottomsheet, also do not forget to fix PWN-7559 locally

app/src/main/java/org/p2p/wallet/home/ui/vialink/SendViaLinkReceiveFundsBottomSheet.kt, app/src/main/java/org/p2p/wallet/home/ui/vialink/SendViaLinkReceiveFundsContract.kt, app/src/main/java/org/p2p/wallet/home/ui/vialink/SendViaLinkReceiveFundsPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/vialink/SendViaLinkReceiveFundsState.kt, app/src/main/java/org/p2p/wallet/home/ui/vialink/interactor/SendViaLinkReceiveFundsInteractor.kt, app/src/main/java/org/p2p/wallet/home/ui/vialink/interactor/SendViaLinkWrapper.kt, app/src/main/java/org/p2p/wallet/newsend/SendModule.kt, app/src/main/res/drawable/bg_rain_circle.xml, app/src/main/res/layout/dialog_send_via_link_recieve_funds.xml, app/src/main/res/layout/layout_send_via_link_claim_success.xml, app/src/main/res/values/send_strings.xml, app/src/main/res/values/send_via_link_strings.xml, core/src/main/java/org/p2p/core/glide/GlideManager.kt, ui-kit/src/main/kotlin/org/p2p/uikit/utils/ImageViewExtensions.kt, ui-kit/src/main/res/values/strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-7422
| Screenshot #1 |
|:-------------:|
|<img width="581" alt="Screen Shot 2023-03-16 at 18 43 30" src="https://user-images.githubusercontent.com/100791035/225593066-af856f5b-a94a-423f-9ef0-63c4e084a436.png">|
=> PWN-7422 - SVL. Receive funds bottom sheet

app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/NewSwapEnabledFeatureToggle.kt, buildSrc/src/main/java/AppVersions.kt
https://p2pvalidator.atlassian.net/browse/PWN-7746
=> PWN-7746 - New swap. Fix ft name

app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/ContentTypeInterceptor.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/tokens/presenter/SwapTokensBMapper.kt, app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt, app/src/main/java/org/p2p/wallet/user/repository/UserRemoteRepository.kt, app/src/main/java/org/p2p/wallet/user/repository/prices/impl/TokenPricesCoinGeckoRepository.kt, buildSrc/src/main/java/AppVersions.kt, core/src/main/java/org/p2p/core/utils/Constants.kt
https://p2pvalidator.atlassian.net/browse/PWN-7752
|<img width="359" alt="Screen Shot 2023-03-19 at 20 59 59" src="https://user-images.githubusercontent.com/100791035/226177242-b597bdc7-4209-469a-ad22-e2c81293ca2b.png">|<img width="359" alt="Screen Shot 2023-03-19 at 20 59 54" src="https://user-images.githubusercontent.com/100791035/226177256-f1b48c24-56f2-4bd3-a72c-32f9a7ee047c.png">|<img width="359" alt="Screen Shot 2023-03-19 at 20 59 20" src="https://user-images.githubusercontent.com/100791035/226177274-ce65b005-8198-491a-9f2f-eef615577e2a.png">|
=> PWN-7752 PWN-7759 - New Swap. Replace BTC ETH to UX friendly names

app/src/main/java/org/p2p/wallet/home/HomeModule.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/tokens/JupiterSwapTokensPricesInMemoryRepository.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/tokens/JupiterSwapTokensPricesLocalRepository.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/tokens/JupiterSwapTokensRemoteRepository.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/tokens/JupiterSwapTokensRepository.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/JupiterSwapSettingsPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/SwapContentSettingsMapper.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/SwapFeeLoader.kt, app/src/main/java/org/p2p/wallet/user/repository/UserRemoteRepository.kt, core/src/main/java/org/p2p/core/utils/Constants.kt
https://p2pvalidator.atlassian.net/browse/PWN-7780
=> PWN-7780 - Fix home fragment scroll and ETH token

app/src/main/java/org/p2p/wallet/bridge/send/mapper/SendUiMapper.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt, app/src/main/java/org/p2p/wallet/newsend/interactor/SearchInteractor.kt
https://p2pvalidator.atlassian.net/browse/PWN-7613
PWN-7613 - show usdCet if user has no tokens
=> PWN-7613 - show usdCet if user has no tokens

app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryPresenter.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/ERC20Tokens.kt
https://p2pvalidator.atlassian.net/browse/PWN-7781
PWN-7781 - handle supported tokens with new field receiveFromTokens to check token and wrapped token by mint from this list
=> PWN-7781 - handle supported tokens new way

app/src/main/java/org/p2p/wallet/auth/interactor/AuthInteractor.kt, app/src/main/java/org/p2p/wallet/push_notifications/AppFirebaseMessagingService.kt
https://p2pvalidator.atlassian.net/browse/PWN-7587
update token each time login
=> PWN-7587 - THS update token each time login

app/src/main/java/org/p2p/wallet/bridge/api/mapper/BridgeMapper.kt, app/src/main/java/org/p2p/wallet/bridge/api/request/GetSolanaFeesRpcRequest.kt, app/src/main/java/org/p2p/wallet/bridge/api/request/SolanaTransferStatusRpcRequest.kt, app/src/main/java/org/p2p/wallet/bridge/api/request/SolanaTransferStatusesRpcRequest.kt, app/src/main/java/org/p2p/wallet/bridge/api/request/TransferFromSolanaRpcRequest.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeAmountResponse.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeBundleFeesResponse.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeBundleResponse.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeSendFeesResponse.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeSendStatusResponse.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeSendTransactionResponse.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeTransactionStatusResponse.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/mapper/ClaimUiMapper.kt, app/src/main/java/org/p2p/wallet/bridge/model/BridgeBundle.kt, app/src/main/java/org/p2p/wallet/bridge/model/BridgeBundleFees.kt, app/src/main/java/org/p2p/wallet/bridge/model/BridgeFee.kt, app/src/main/java/org/p2p/wallet/bridge/send/BridgeSendInteractor.kt, app/src/main/java/org/p2p/wallet/bridge/send/BridgeSendModule.kt, app/src/main/java/org/p2p/wallet/bridge/send/model/BridgeSendFees.kt, app/src/main/java/org/p2p/wallet/bridge/send/model/BridgeSendTransaction.kt, app/src/main/java/org/p2p/wallet/bridge/send/model/BridgeSendTransactionDetails.kt, app/src/main/java/org/p2p/wallet/bridge/send/model/BridgeSendTransactionStatus.kt, app/src/main/java/org/p2p/wallet/bridge/send/repository/EthereumSendRemoteRepository.kt, app/src/main/java/org/p2p/wallet/bridge/send/repository/EthereumSendRepository.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumKitRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-7616
=> PWN-7616 - Add Rust send integration

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/price/EthereumPriceRepository.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/price/PriceRepository.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumKitRepository.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-7606
PWN-7606 - cache added to coingecko prices repo + fix on home USDT_COINGECKO_ID
=> PWN-7606 - cache added to coingecko prices repo + fix on home USDT_COINGECKO_ID

app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-7790
PWN-7790 - show fees whenever free it or not
=> PWN-7790 - show fees whenever free it or not

app/src/main/java/org/p2p/wallet/user/repository/prices/di/TokenPricesModule.kt, app/src/main/java/org/p2p/wallet/user/repository/prices/impl/TokenPricesCoinGeckoRepository.kt, core/src/main/java/org/p2p/core/model/TokenPriceWithMark.kt, core/src/main/java/org/p2p/core/pricecache/PriceCacheRepository.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/price/EthereumPriceRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-7606
PWN-7606 - fixes for coingecko use single for TokenPricesRemoteRepository and use common PriceCacheRepository.kt to use same logic under the hood
=> PWN-7606 - fixes for coingecko

app/src/main/java/org/p2p/wallet/common/ui/widget/SlippageRadioView.kt, app/src/main/java/org/p2p/wallet/jupiter/analytics/JupiterSwapSettingsAnalytics.kt, app/src/main/java/org/p2p/wallet/jupiter/model/SwapRateTickerState.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/rate/SwapRateTickerManager.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/mapper/SwapRateTickerMapper.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/JupiterSwapSettingsFragment.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/JupiterSwapSettingsPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/view/SwapCustomSlippageCell.kt, app/src/main/java/org/p2p/wallet/swap/model/Slippage.kt, app/src/main/java/org/p2p/wallet/swap/ui/settings/OrcaSwapSettingsFragment.kt, app/src/main/java/org/p2p/wallet/transaction/ui/JupiterTransactionProgressBottomSheet.kt, buildSrc/src/main/java/AppVersions.kt
https://p2pvalidator.atlassian.net/browse/PWN-7729
https://p2pvalidator.atlassian.net/browse/PWN-7733
- increase delay for custom slippage
- fix formatting issue
**IM GOING TO GIVE THE FEATURE BUILD TO QA FIRSTLY, AND ONLY AFTER THAT MERGE**
=> PWN-7729 PWN-7733 - Swap release fixes

app/src/main/java/org/p2p/wallet/bridge/api/mapper/BridgeServiceErrorMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-7726
PWN-7726 - fix error codes to parse error properly
=> PWN-7726 - fix error codes to parse error properly

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/UserTokensPolling.kt, app/src/main/java/org/p2p/wallet/home/ui/main/models/EthereumHomeState.kt, app/src/main/java/org/p2p/wallet/home/ui/main/models/EthereumState.kt
https://p2pvalidator.atlassian.net/browse/PWN-7606
PWN-7606 - fix home screen and pooling tokens where we need + move ethereum data to EthereumState for home screen
=> PWN-7606 - fix home screen and pooling tokens where we need + move ethereum data to EthereumState for home screen

app/src/main/java/org/p2p/wallet/jupiter/statemanager/rate/SwapRateTickerManager.kt
https://p2pvalidator.atlassian.net/browse/PWN-7733
=> PWN-7733 - Fix swap rates again

.github/workflows/release-build.yml, app/src/main/java/org/p2p/wallet/bridge/api/request/SendEthereumBundleRpcRequest.kt, app/src/main/java/org/p2p/wallet/common/ui/widget/SlippageRadioView.kt, app/src/main/java/org/p2p/wallet/jupiter/analytics/JupiterSwapSettingsAnalytics.kt, app/src/main/java/org/p2p/wallet/jupiter/model/SwapRateTickerState.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/rate/SwapRateTickerManager.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/mapper/SwapRateTickerMapper.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/JupiterSwapSettingsFragment.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/JupiterSwapSettingsPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/view/SwapCustomSlippageCell.kt, app/src/main/java/org/p2p/wallet/swap/model/Slippage.kt, app/src/main/java/org/p2p/wallet/swap/ui/settings/OrcaSwapSettingsFragment.kt, app/src/main/java/org/p2p/wallet/transaction/ui/JupiterTransactionProgressBottomSheet.kt, app/src/main/res/values/history_strings.xml, buildSrc/src/main/java/AppVersions.kt, buildSrc/src/main/java/LastCommit.kt
Reverts p2p-org/key-app-android#1495
=> Revert "Release/v2.5.0.7 into develop"

app/src/main/java/org/p2p/wallet/bridge/api/request/GetSolanaFeesRpcRequest.kt, app/src/main/java/org/p2p/wallet/bridge/send/BridgeSendModule.kt, app/src/main/java/org/p2p/wallet/bridge/send/interactor/EthereumSendInteractor.kt, app/src/main/java/org/p2p/wallet/bridge/send/repository/EthereumSendRemoteRepository.kt, app/src/main/java/org/p2p/wallet/bridge/send/repository/EthereumSendRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-7828
PWN-7828 - EthereumSendInteractor.kt and fixes to make real call
=> PWN-7828 - EthereumSendInteractor.kt and fixes to make real call

app/src/main/res/layout/fragment_claim.xml
https://p2pvalidator.atlassian.net/browse/PWN-7831
PWN-7831 - fix bold -> regular for textViewFiatAmount
=> PWN-7831 - fix bold -> regular for textViewFiatAmount

app/src/main/java/org/p2p/wallet/newsend/statemachine/SendExtentions.kt, app/src/main/java/org/p2p/wallet/newsend/statemachine/fee/SendBridgeFeeLoader.kt, app/src/main/java/org/p2p/wallet/newsend/statemachine/handler/bridge/AmountChangeActionHandler.kt, app/src/main/java/org/p2p/wallet/newsend/statemachine/handler/bridge/InitFeatureActionHandler.kt, app/src/main/java/org/p2p/wallet/newsend/statemachine/handler/bridge/NewTokenActionHandler.kt, app/src/main/java/org/p2p/wallet/newsend/statemachine/mapper/SendBridgeStaticStateMapper.kt, app/src/main/java/org/p2p/wallet/newsend/statemachine/model/SendFee.kt, app/src/main/java/org/p2p/wallet/newsend/statemachine/model/SendInitialData.kt, app/src/main/java/org/p2p/wallet/newsend/statemachine/model/SendToken.kt, app/src/main/java/org/p2p/wallet/newsend/statemachine/validator/SendBridgeValidator.kt
https://p2pvalidator.atlassian.net/browse/PWN-7614
bridge-load-fee
=> PWN-7614 - bridge load fee

app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt, app/src/main/java/org/p2p/wallet/newsend/model/CalculationMode.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendContract.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendFragment.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt, app/src/main/java/org/p2p/wallet/newsend/ui/vialink/SendViaLinkPresenter.kt, app/src/main/java/org/p2p/wallet/transaction/model/NewShowProgress.kt, app/src/main/java/org/p2p/wallet/transaction/ui/NewTransactionProgressBottomSheet.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitSendDetailsWidget.kt
https://p2pvalidator.atlassian.net/browse/PWN-7874
PWN-7874 - make changes on Ui and block fiat switching when there is no rates on token for send
=> PWN-7874 - make changes on Ui and block fiat switching when there is no rates on token for send

app/src/main/java/org/p2p/wallet/home/model/HomeMapper.kt, app/src/main/java/org/p2p/wallet/restore/RestoreModule.kt, app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt, app/src/main/java/org/p2p/wallet/restore/model/DerivableAccount.kt, app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsAdapter.kt, app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-7873
=> PWN-7873 - Rate fixes in onboarding

app/src/main/java/org/p2p/wallet/sell/interactor/SellInteractor.kt
https://p2pvalidator.atlassian.net/browse/PWN-7845
PWN-7845 - cash out button visibility fix
=> PWN-7845 - cash out button visibility fix

app/src/main/java/org/p2p/wallet/newsend/model/TemporaryAccount.kt, app/src/main/java/org/p2p/wallet/svl/model/SendLinkGenerator.kt, app/src/main/java/org/p2p/wallet/svl/ui/send/SendViaLinkPresenter.kt, solana/src/main/java/org/p2p/solanaj/core/Account.kt
https://p2pvalidator.atlassian.net/browse/PWN-7891
- fix link generation
=> PWN-7891 PWN-7894 - SVL. Fix account generation

app/src/main/java/org/p2p/wallet/history/HistoryModule.kt, app/src/main/java/org/p2p/wallet/history/ui/sendvialink/HistorySendLinkDetailsBottomSheet.kt, app/src/main/java/org/p2p/wallet/history/ui/sendvialink/HistorySendLinkDetailsContract.kt, app/src/main/java/org/p2p/wallet/history/ui/sendvialink/HistorySendLinkDetailsPresenter.kt, app/src/main/java/org/p2p/wallet/infrastructure/db/WalletDatabase.kt, app/src/main/java/org/p2p/wallet/infrastructure/sendvialink/UserSendLinksDatabaseRepository.kt, app/src/main/java/org/p2p/wallet/infrastructure/sendvialink/UserSendLinksLocalRepository.kt, app/src/main/java/org/p2p/wallet/infrastructure/sendvialink/db/UserSendLinkEntity.kt, app/src/main/java/org/p2p/wallet/infrastructure/sendvialink/db/UserSendLinksDao.kt, app/src/main/java/org/p2p/wallet/infrastructure/sendvialink/model/UserSendLink.kt, app/src/main/java/org/p2p/wallet/svl/ui/linkgeneration/SendLinkGenerationPresenter.kt, app/src/main/java/org/p2p/wallet/svl/ui/send/SendViaLinkPresenter.kt, app/src/main/res/layout/dialog_history_send_link_details.xml, app/src/main/res/values/history_strings.xml, ui-kit/src/main/res/values/strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-7421
WIP: local testing in progress
=> PWN-7421 - SVL. History details

app/src/main/java/org/p2p/wallet/restore/RestoreModule.kt, app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt, app/src/main/java/org/p2p/wallet/restore/model/DerivableAccount.kt, app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsAdapter.kt, app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsPresenter.kt, buildSrc/src/main/java/AppVersions.kt
https://p2pvalidator.atlassian.net/browse/PWN-7927
=> PWN-7927 - Fix SOL rate in DerivableAccountFragment

app/src/main/java/org/p2p/wallet/bridge/api/request/SendEthereumBundleRpcRequest.kt
https://p2pvalidator.atlassian.net/browse/PWN-7828
PWN-7828 - simulate_ethereum_bundle -> send_ethereum_bundle
=> PWN-7828 - simulate_ethereum_bundle -> send_ethereum_bundle

app/src/main/java/org/p2p/wallet/auth/widget/PhoneNumberInputView.kt, app/src/main/java/org/p2p/wallet/common/mvp/MvpPresenter.kt, app/src/main/java/org/p2p/wallet/history/model/HistoryPagingResult.kt, app/src/main/java/org/p2p/wallet/history/ui/history/HistoryContract.kt, app/src/main/java/org/p2p/wallet/history/ui/history/HistoryFragment.kt, app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt, app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListView.kt, app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewClickListener.kt, app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewContract.kt, app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewPresenter.kt, app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewType.kt, app/src/main/java/org/p2p/wallet/history/ui/model/HistoryItem.kt, app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryFragment.kt, app/src/main/java/org/p2p/wallet/history/ui/token/adapter/HistoryAdapter.kt, app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/HistoryUserSendLinksViewHolder.kt, app/src/main/java/org/p2p/wallet/infrastructure/sendvialink/UserSendLinksDatabaseRepository.kt, app/src/main/java/org/p2p/wallet/infrastructure/sendvialink/UserSendLinksLocalRepository.kt, app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt, app/src/main/res/layout/item_history_user_send_links.xml, ui-kit/src/main/kotlin/org/p2p/uikit/utils/ViewExtensions.kt
https://p2pvalidator.atlassian.net/browse/PWN-7912
=> PWN-7912 - SVL. History scroll fix for user send links

app/src/main/java/org/p2p/wallet/auth/widget/PhoneNumberInputView.kt, app/src/main/java/org/p2p/wallet/common/mvp/MvpPresenter.kt, app/src/main/java/org/p2p/wallet/history/ui/history/HistoryContract.kt, app/src/main/java/org/p2p/wallet/history/ui/history/HistoryFragment.kt, app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt, app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListView.kt, app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewContract.kt, app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewPresenter.kt, app/src/main/java/org/p2p/wallet/history/ui/model/HistoryItem.kt, app/src/main/java/org/p2p/wallet/history/ui/sendvialink/HistorySendLinkDetailsBottomSheet.kt, app/src/main/java/org/p2p/wallet/history/ui/sendvialink/HistorySendLinkDetailsPresenter.kt, app/src/main/java/org/p2p/wallet/history/ui/sendvialink/HistorySendLinksFragment.kt, app/src/main/java/org/p2p/wallet/history/ui/sendvialink/HistorySendLinksPresenter.kt, app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryFragment.kt, app/src/main/java/org/p2p/wallet/history/ui/token/adapter/HistoryAdapter.kt, app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/HistoryUserSendLinksViewHolder.kt, app/src/main/java/org/p2p/wallet/infrastructure/sendvialink/UserSendLinksDatabaseRepository.kt, app/src/main/java/org/p2p/wallet/infrastructure/sendvialink/UserSendLinksLocalRepository.kt, app/src/main/java/org/p2p/wallet/infrastructure/sendvialink/db/UserSendLinkEntity.kt, app/src/main/java/org/p2p/wallet/newsend/SendModule.kt, app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt, app/src/main/res/layout/dialog_send_via_link_receive_funds.xml, app/src/main/res/layout/item_history_user_send_links.xml, buildSrc/src/main/java/AppVersions.kt, buildSrc/src/main/java/LastCommit.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/finance_block/FinanceBlockDelegates.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/right_side/UiKitRightSideView.kt, ui-kit/src/main/kotlin/org/p2p/uikit/utils/ViewExtensions.kt, ui-kit/src/main/res/layout/widget_finance_block.xml, ui-kit/src/main/res/layout/widget_right_side_double_text.xml
https://p2pvalidator.atlassian.net/browse/PWN-7913
=> PWN-7913 - SVL. Links history text fix

app/src/main/java/org/p2p/wallet/svl/ui/linkresult/SendLinkGenerationResultFragment.kt, app/src/main/res/values/send_via_link_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-7911
=> PWN-7911 - SVL. Change share text format

app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerInteractor.kt, app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerViaLinkInteractor.kt, app/src/main/java/org/p2p/wallet/newsend/SendFeeRelayerManager.kt, app/src/main/java/org/p2p/wallet/svl/interactor/SendViaLinkInteractor.kt, app/src/main/res/layout/layout_send_via_link_claim_success.xml
https://p2pvalidator.atlassian.net/browse/PWN-7933
=> PWN-7933 - Send fixes

app/src/main/java/org/p2p/wallet/history/ui/sendvialink/HistorySendLinksPresenter.kt, app/src/main/java/org/p2p/wallet/history/ui/token/adapter/HistoryAdapter.kt, app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/HistoryUserSendLinksViewHolder.kt, app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt, ui-kit/src/main/res/layout/widget_finance_block.xml
https://p2pvalidator.atlassian.net/browse/PWN-7975
=> PWN-7975 - SVL. Fix history item blinking

app/build.gradle.kts, app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt, app/src/main/java/org/p2p/wallet/auth/model/Username.kt, app/src/main/java/org/p2p/wallet/auth/username/api/request/LookupNameRequest.kt, app/src/main/java/org/p2p/wallet/auth/username/api/response/LookupNameResponse.kt, app/src/main/java/org/p2p/wallet/auth/username/di/RegisterUsernameServiceModule.kt, app/src/main/java/org/p2p/wallet/auth/username/repository/UsernameParser.kt, app/src/main/java/org/p2p/wallet/auth/username/repository/UsernameRemoteRepository.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/UsernameDomainFeatureToggle.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/test/java/org/p2p/wallet/auth/gateway/repository/mapper/ChaCha20Poly1305SymmetricKeyGeneratorTest.kt, app/src/test/java/org/p2p/wallet/auth/gateway/repository/mapper/GatewayServiceOnboardingMetadataCipherTest.kt, app/src/test/java/org/p2p/wallet/auth/username/repository/UsernameParserTest.kt, app/src/test/java/org/p2p/wallet/infrastructure/network/data/RpcErrorParserTest.kt, app/src/test/java/org/p2p/wallet/sdk/facade/mapper/SolendMethodResultMapperTest.kt, app/src/test/java/org/p2p/wallet/sdk/moonpay/repository/sell/MoonpayExternalCustomerIdProviderTest.kt
https://p2pvalidator.atlassian.net/browse/PW-7901
=> PWN-7901 - Add withTld to name-service

core/src/main/java/org/p2p/core/token/Token.kt
https://p2pvalidator.atlassian.net/browse/PWN-7998
cut eth formatting
=> PWN-7998 - cut eth formatting

app/src/main/java/org/p2p/wallet/qr/ui/ScanQrFragment.kt
https://p2pvalidator.atlassian.net/browse/PWN-7961
fix qr scanning
=> PWN-7961 - fix qr scanning

app/src/main/java/org/p2p/wallet/newsend/ui/search/adapter/SearchViewHolder.kt, app/src/main/res/layout/item_search.xml
https://p2pvalidator.atlassian.net/browse/PWN-7960
=> PWN-7960 - Remove bottom textView for eth address in search fragment

app/src/main/java/org/p2p/wallet/common/date/ZonedDateExtensions.kt, app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerInteractor.kt, app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetFragment.kt, app/src/main/java/org/p2p/wallet/history/ui/sendvialink/HistorySendLinkDetailsPresenter.kt, app/src/main/java/org/p2p/wallet/svl/ui/error/SendViaLinkErrorFragment.kt, app/src/main/java/org/p2p/wallet/svl/ui/receive/ReceiveViaLinkBottomSheet.kt, app/src/main/res/layout/fragment_send_link_generation.xml, app/src/main/res/layout/fragment_send_via_link_error.xml, app/src/main/res/layout/layout_send_via_link_claim_success.xml, app/src/main/res/layout/widget_send_via_link.xml
https://p2pvalidator.atlassian.net/browse/PWN-8039
https://p2pvalidator.atlassian.net/browse/PWN-8018
https://p2pvalidator.atlassian.net/browse/PWN-7976
https://p2pvalidator.atlassian.net/browse/PWN-7968
https://p2pvalidator.atlassian.net/browse/PWN-7889
=> PWN-8039 - Various UI fixes

app/src/main/java/org/p2p/wallet/common/feature_toggles/di/FeatureTogglesModule.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/TokenMetadataUpdateFeatureToggle.kt, app/src/main/java/org/p2p/wallet/feerelayer/model/TransactionFeeLimits.kt, app/src/main/java/org/p2p/wallet/home/ui/main/UserTokensPolling.kt, app/src/main/java/org/p2p/wallet/newsend/ui/search/NewSearchPresenter.kt, app/src/main/java/org/p2p/wallet/svl/interactor/ReceiveViaLinkInteractor.kt, app/src/main/java/org/p2p/wallet/svl/interactor/SendViaLinkInteractor.kt, app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt, app/src/main/res/layout/widget_send_via_link.xml, app/src/main/res/values/send_via_link_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8072
=> PWN-8072 - Additional svl fixers

app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-7952
=> PWN-7952 - Fix sorting order

app/src/main/java/org/p2p/wallet/bridge/api/request/GetEthereumFreeFeeLimitRequest.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeFreeFeeLimitResponse.kt, app/src/main/java/org/p2p/wallet/bridge/claim/interactor/ClaimInteractor.kt, app/src/main/java/org/p2p/wallet/bridge/claim/model/ClaimDetails.kt, app/src/main/java/org/p2p/wallet/bridge/claim/repository/EthereumClaimRemoteRepository.kt, app/src/main/java/org/p2p/wallet/bridge/claim/repository/EthereumClaimRepository.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimPresenter.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/dialogs/ClaimInfoBottomSheet.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/mapper/ClaimUiMapper.kt, app/src/main/java/org/p2p/wallet/bridge/interactor/EthereumInteractor.kt, app/src/main/res/values/bridges_strings.xml, app/src/main/res/values/environment_config.xml
https://p2pvalidator.atlassian.net/browse/PWN-8005
=> PWN-8005 - Fix fee in details screen

app/src/main/java/org/p2p/wallet/bridge/claim/ui/mapper/ClaimUiMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-7959
=> PWN-7959 - Fix claim fee text

app/src/main/java/org/p2p/wallet/infrastructure/db/WalletDatabase.kt, app/src/main/java/org/p2p/wallet/newsend/db/RecipientEntity.kt, app/src/main/java/org/p2p/wallet/newsend/model/RecipientConverter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8102
PWN-8102 - NetworkType save in DB
=> PWN-8102 - NetworkType save in DB in search saving

app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimPresenter.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/mapper/ClaimUiMapper.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/UserTokensPolling.kt, app/src/main/res/layout/fragment_home.xml, app/src/main/res/values/send_strings.xml, core/src/main/java/org/p2p/core/utils/AmountExtensions.kt
=> NO-TICKET - Fix home screen states, fix eth scaling bug

app/src/main/java/org/p2p/wallet/bridge/claim/ui/mapper/ClaimUiMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-8095
PWN-8095 - fix showing free transactions in progress bottomSheet
=> PWN-8095 - fix showing free transactions in progress bottomSheet

app/src/main/java/org/p2p/wallet/history/analytics/HistoryAnalytics.kt, app/src/main/java/org/p2p/wallet/svl/ui/receive/ReceiveViaLinkBottomSheet.kt, app/src/main/java/org/p2p/wallet/svl/ui/send/SvlReceiveFundsAnalytics.kt
https://p2pvalidator.atlassian.net/browse/PWN-8034
=> PWN-8034 - Analytics fixes

app/src/main/java/org/p2p/wallet/auth/interactor/AuthLogoutInteractor.kt, app/src/main/java/org/p2p/wallet/bridge/interactor/EthereumInteractor.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/UserTokensPolling.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumKitRepository.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-8111
https://p2pvalidator.atlassian.net/browse/PWN-8112
=> PWN-8111 - Fix pull to refresh state on home screen

app/build.gradle.kts, app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-7619
=> PWN-7619 - Fix token sorting order

app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8088
=> PWN-8088 - Fix claim analytics events

app/src/main/java/org/p2p/wallet/newsend/ui/search/NewSearchPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8117
PWN-8117 - show error if token is not supported in search
=> PWN-8117 - show error if token is not supported in search

app/src/main/java/org/p2p/wallet/bridge/send/statemachine/handler/bridge/NewTokenActionHandler.kt
https://p2pvalidator.atlassian.net/browse/PWN-8122
PWN-8122 - fix token change state handling
=> PWN-8122 - fix token change state handling

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, core/src/main/java/org/p2p/core/utils/Constants.kt
https://p2pvalidator.atlassian.net/browse/PWN-7780
Added Ethereum token to home screen.
Searching for WETH token instead of ETH
=> PWN-7780 - return WETH token to home screen

app/src/main/java/org/p2p/wallet/infrastructure/network/NetworkModule.kt, app/src/main/java/org/p2p/wallet/user/repository/prices/di/TokenPricesModule.kt
https://p2pvalidator.atlassian.net/browse/PWN-7958
=> PWN-7958 - Fix crash while coingeckoApi was held by debug checkpoint

ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumKitRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-8127
=> PWN-8127 - Fix filter for eth tokens which fiat amount is less than 1$

app/src/main/java/org/p2p/wallet/newsend/ui/search/adapter/SearchViewHolder.kt
https://p2pvalidator.atlassian.net/browse/PWN-8152
=> PWN-8152 - Revert token ticker in search fragment

app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
https://p2pvalidator.atlassian.net/browse/PWN-8112
=> PWN-8112 - hide fiat amount on empty state screen

app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt, app/src/main/java/org/p2p/wallet/common/date/ZonedDateExtensions.kt, app/src/main/java/org/p2p/wallet/history/HistoryModule.kt, app/src/main/java/org/p2p/wallet/history/interactor/HistoryInteractor.kt, app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryTransaction.kt, app/src/main/java/org/p2p/wallet/history/repository/local/PendingTransactionsInMemoryRepository.kt, app/src/main/java/org/p2p/wallet/history/repository/local/PendingTransactionsLocalRepository.kt, app/src/main/java/org/p2p/wallet/history/repository/local/TransactionDetailsDatabaseRepository.kt, app/src/main/java/org/p2p/wallet/history/repository/local/TransactionDetailsLocalRepository.kt, app/src/main/java/org/p2p/wallet/history/repository/remote/HistoryRepository.kt, app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetFragment.kt, app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsContract.kt, app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt, app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt, app/src/main/java/org/p2p/wallet/svl/ui/receive/ReceiveViaLinkPresenter.kt, app/src/main/java/org/p2p/wallet/utils/DateTimeUtils.kt, app/src/main/java/org/p2p/wallet/utils/TransactionImageViewExtensions.kt, app/src/main/res/values/history_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-7948
- fix design 
- extract repository with pending transactions
=> PWN-7948 - SVL. Fix pending transactions

app/src/main/java/org/p2p/wallet/newsend/model/NewSendButtonState.kt, app/src/main/res/values/send_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8151
=> PWN-8151 - Change send button state text

app/src/main/java/org/p2p/wallet/auth/repository/AuthRemoteRepository.kt, app/src/main/java/org/p2p/wallet/auth/repository/AuthRepository.kt, app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootPresenter.kt, app/src/main/java/org/p2p/wallet/auth/ui/verify/VerifySecurityKeyPresenter.kt, app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt, app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsAdapter.kt, app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsContract.kt, app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsFragment.kt, app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsPresenter.kt, app/src/main/res/layout/item_token_simple.xml
https://p2pvalidator.atlassian.net/browse/PWN-7811
- Added support for choosing derived account
- Added ripple to account foreground
- Default wallet index = 0 for deprecated code
=> PWN-7811 - added support for choosing derived account

app/src/main/java/org/p2p/wallet/bridge/api/mapper/BridgeMapper.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeSendFeesResponse.kt, app/src/main/java/org/p2p/wallet/bridge/claim/model/ClaimDetails.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimPresenter.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/dialogs/ClaimInfoBottomSheet.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/mapper/ClaimUiMapper.kt, app/src/main/java/org/p2p/wallet/bridge/model/BridgeAmount.kt, app/src/main/java/org/p2p/wallet/bridge/send/model/BridgeSendFees.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/dialog/BridgeSendFeeBottomSheet.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/mapper/BridgeSendUiMapper.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/model/BridgeFeeDetails.kt, app/src/main/res/values/bridges_strings.xml, core/src/main/java/org/p2p/core/utils/AmountExtensions.kt
https://p2pvalidator.atlassian.net/browse/PWN-8133
PWN-8133 - fix fees in bottomsheet logic + resultAmount handling
=> PWN-8133 - fix fees in bottomsheet logic

app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8088
PWN-8088 - fix logFreeTransactionsClicked event moment
=> PWN-8088 - fix logFreeTransactionsClicked event moment

app/src/main/AndroidManifest.xml, app/src/main/java/org/p2p/wallet/deeplinks/AppDeeplinksManager.kt, app/src/main/java/org/p2p/wallet/svl/interactor/ReceiveViaLinkInteractor.kt, app/src/main/java/org/p2p/wallet/svl/model/SendViaLinkClaimingState.kt, app/src/main/java/org/p2p/wallet/svl/ui/receive/ReceiveViaLinkPresenter.kt, app/src/main/java/org/p2p/wallet/user/repository/UserLocalRepository.kt, app/src/main/java/org/p2p/wallet/user/repository/UserRemoteRepository.kt, app/src/main/java/org/p2p/wallet/user/repository/prices/impl/TokenPricesCoinGeckoRepository.kt, app/src/main/res/layout/item_history_transaction.xml, app/src/main/res/values/deeplinks.xml, core/src/main/java/org/p2p/core/pricecache/PriceCacheRepository.kt, core/src/main/java/org/p2p/core/token/Token.kt, ui-kit/src/main/res/layout/widget_start_amount_view.xml
https://p2pvalidator.atlassian.net/browse/PWN-7948
=> PWN-7948 - SVL. Additional history fixes

app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-7619
=> PWN-7619 - Change sorting algorithm

app/src/main/java/org/p2p/wallet/bridge/api/request/TransferFromSolanaRpcRequest.kt, app/src/main/java/org/p2p/wallet/bridge/send/BridgeSendModule.kt, app/src/main/java/org/p2p/wallet/bridge/send/interactor/BridgeSendInteractor.kt, app/src/main/java/org/p2p/wallet/bridge/send/repository/EthereumSendRemoteRepository.kt, app/src/main/java/org/p2p/wallet/bridge/send/repository/EthereumSendRepository.kt, app/src/main/java/org/p2p/wallet/bridge/send/statemachine/fee/SendBridgeTransactionLoader.kt, app/src/main/java/org/p2p/wallet/bridge/send/statemachine/model/SendFee.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt, app/src/main/java/org/p2p/wallet/rpc/repository/solana/RpcSolanaRemoteRepository.kt
=> NO-TICKET - Update send calculation fee logic

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
https://p2pvalidator.atlassian.net/browse/PWN-8193
=> PWN-8193 - Fix token rates after login

app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapFragment.kt
https://p2pvalidator.atlassian.net/browse/PWN-7588
PWN-7588 - pause/resume StateManager when needed
=> PWN-7588 - pause/resume StateManager when needed

app/src/main/java/org/p2p/wallet/bridge/send/ui/dialog/BridgeSendFeeBottomSheet.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/mapper/BridgeSendUiMapper.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/model/BridgeFeeDetails.kt, app/src/main/res/layout/dialog_bridge_send_info.xml, app/src/main/res/values/bridges_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8133
PWN-8133 - remove total fees
=> PWN-8133 - remove total fees

app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensPresenter.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/dialog/SelectReceiveNetworkBottomSheet.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/ERC20Tokens.kt
https://p2pvalidator.atlassian.net/browse/PWN-8178
PWN-8178 - remove sol from supported tokens
=> PWN-8178 - remove sol from supported tokens

app/src/main/java/org/p2p/wallet/svl/ui/send/SendViaLinkContract.kt, app/src/main/java/org/p2p/wallet/svl/ui/send/SendViaLinkFragment.kt, app/src/main/java/org/p2p/wallet/svl/ui/send/SendViaLinkPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8184
PWN-8184 - disable switch amounts if there is no token rates
=> PWN-8184 - disable switch amounts if there is no token rates

app/src/main/java/org/p2p/wallet/bridge/claim/ui/dialogs/ClaimInfoBottomSheet.kt
https://p2pvalidator.atlassian.net/browse/PWN-8005
PWN-8005 - always show amount on user will get field
=> PWN-8005 - always show amount on user will get field

app/src/main/res/layout/fragment_ethereum_receive.xml, app/src/main/res/layout/fragment_new_receive_solana.xml
https://p2pvalidator.atlassian.net/browse/PWN-8183
PWN-8183 - fix texts align and constraints
=> PWN-8183 - fix texts align and constraints

app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimFragment.kt, app/src/main/res/layout/fragment_claim.xml
https://p2pvalidator.atlassian.net/browse/PWN-8216
PWN-8216 - change text color as we needed according to state
=> PWN-8216 - change text color as we needed according to state

app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt, app/src/main/res/values/send_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8203
PWN-8203- change text when Insufficient funds on bridging
=> PWN-8203- change text when Insufficient funds on bridging

app/src/main/java/org/p2p/wallet/bridge/claim/ui/dialogs/ClaimInfoBottomSheet.kt, app/src/main/res/values/bridges_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8226
=> PWN-8226 - Change claim dialog title

app/build.gradle.kts, app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt, app/src/main/java/org/p2p/wallet/auth/model/Username.kt, app/src/main/java/org/p2p/wallet/auth/username/api/request/LookupNameRequest.kt, app/src/main/java/org/p2p/wallet/auth/username/api/response/LookupNameResponse.kt, app/src/main/java/org/p2p/wallet/auth/username/di/RegisterUsernameServiceModule.kt, app/src/main/java/org/p2p/wallet/auth/username/repository/UsernameParser.kt, app/src/main/java/org/p2p/wallet/auth/username/repository/UsernameRemoteRepository.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/java/org/p2p/wallet/newsend/ui/search/NewSearchPresenter.kt, app/src/test/java/org/p2p/wallet/auth/gateway/repository/mapper/ChaCha20Poly1305SymmetricKeyGeneratorTest.kt, app/src/test/java/org/p2p/wallet/auth/gateway/repository/mapper/GatewayServiceOnboardingMetadataCipherTest.kt, app/src/test/java/org/p2p/wallet/auth/username/repository/UsernameParserTest.kt, app/src/test/java/org/p2p/wallet/infrastructure/network/data/RpcErrorParserTest.kt, app/src/test/java/org/p2p/wallet/sdk/facade/mapper/SolendMethodResultMapperTest.kt, app/src/test/java/org/p2p/wallet/sdk/moonpay/repository/sell/MoonpayExternalCustomerIdProviderTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-7901
- .key username in priority now
=> PWN-7901 - Name Service bugs

app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8236
PWN-8236 - remove not needed code in attach
=> PWN-8236 - remove not needed code in attach

app/src/main/java/org/p2p/wallet/history/ui/history/HistoryFragment.kt, app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/SwapInitialTokenSelectorFactory.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/token_selector/PreinstallTokensBySymbolSelector.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/token_selector/SwapInitialTokenSelector.kt, app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-8238
=> PWN-8238 - Change swap banner tokens pair

app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-8258
=> PWN-8258 - Fix infinity history

app/src/main/java/org/p2p/wallet/bridge/send/ui/mapper/BridgeSendUiMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-8230
PWN-8230 - remove fees in sol from progress dialog
=> PWN-8230 - remove fees in sol from progress dialog

app/src/main/java/org/p2p/wallet/receive/list/TokenListPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-4179
PWN-4179 - remove wSol (wrapped sol) from tokens list
=> PWN-4179 - remove wSol (wrapped sol) from tokens list

app/proguard-rules.pro, app/src/main/java/org/p2p/wallet/bridge/api/mapper/BridgeServiceErrorMapper.kt, app/src/main/java/org/p2p/wallet/bridge/repository/BridgeRemoteRepository.kt, core/src/main/java/org/p2p/core/rpc/JsonRpc.kt, gradle.properties
https://p2pvalidator.atlassian.net/browse/PWN-8256
=> PWN-8256 - Fix claim bundles on release builds

app/proguard-rules.pro, app/src/main/java/org/p2p/wallet/history/repository/remote/MoonpayHistoryRemoteRepository.kt, app/src/main/java/org/p2p/wallet/newsend/SendFeeRelayerManager.kt, app/src/main/java/org/p2p/wallet/newsend/model/FeeRelayerState.kt, app/src/main/java/org/p2p/wallet/newsend/model/FeeRelayerStateError.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt, buildSrc/src/main/java/AppVersions.kt
https://p2pvalidator.atlassian.net/browse/PWN-8257
=> PWN-8257 - Fix CashOut history

app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
https://p2pvalidator.atlassian.net/browse/PWN-8222
=> PWN-8222 - Fix token sorting on main screen before PTR

app/src/main/java/org/p2p/wallet/receive/list/TokenListPresenter.kt, app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt, core/src/main/java/org/p2p/core/utils/Constants.kt
https://p2pvalidator.atlassian.net/browse/PWN-4179
PWN-4179 - remove wSol (wrapped sol) from all tokens
=> PWN-4179 - remove wSol (wrapped sol) from all tokens

app/proguard-rules.pro, app/src/main/java/org/p2p/wallet/App.kt, app/src/main/java/org/p2p/wallet/common/crashlogging/helpers/TimberCrashTree.kt, app/src/main/java/org/p2p/wallet/common/crashlogging/impl/SentryFacade.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/moonpay/MoonpayErrorResponse.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/moonpay/MoonpayErrorResponseType.kt, app/src/main/java/org/p2p/wallet/rpc/interactor/TransactionAddressInteractor.kt, app/src/main/java/org/p2p/wallet/seed/UiKitSeedPhraseView.kt
https://p2pvalidator.atlassian.net/browse/PWN-6505
=> PWN-6505 - Remove network related errors from Sentry

app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsFragment.kt, app/src/main/res/layout/fragment_derivable_accounts.xml
https://p2pvalidator.atlassian.net/browse/PWN-5102
- layout fix
=> PWN-5102 - derivable accounts screen fix

app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyContract.kt, app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyFragment.kt, app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyPresenter.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitAmountsView.kt
https://p2pvalidator.atlassian.net/browse/PWN-5104
Hide icon if currency selection is not available
=> PWN-5104 - hide currency select icon if currency selection isn't available

app/src/main/java/org/p2p/wallet/transaction/ui/NewTransactionProgressBottomSheet.kt
https://p2pvalidator.atlassian.net/browse/PWN-8285
PWN-8285 - remove fee line if there is no fee (do not show free)
=> PWN-8285 - remove fee line if there is no fee (do not show free)

app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimPresenter.kt, app/src/main/res/values/bridges_strings.xml, app/src/main/res/values/strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8269
https://p2pvalidator.atlassian.net/browse/PWN-8270
PWN-8269, PWN-8270 - claim fixes
=> PWN-8269, PWN-8270 - claim fixes for release

app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimContract.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimFragment.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimPresenter.kt, app/src/main/res/layout/fragment_claim.xml, app/src/main/res/values/bridges_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8272
PWN-8272 - show user will get on claim screen
=> PWN-8272 - show user will get on claim screen

app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpActivity.kt, app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpBottomSheet.kt, app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpFragment.kt, app/src/main/java/org/p2p/wallet/common/ui/bottomsheet/ErrorBottomSheet.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/java/org/p2p/wallet/utils/DialogExtensions.kt, app/src/main/res/layout/dialog_error_bottom_sheet.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
https://p2pvalidator.atlassian.net/browse/PWN-8211
PWN-8211 - new dialogs ui according to designs
=> PWN-8211 - new dialogs ui according to designs

.idea/codeStyles/Project.xml, app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/interactor/JupiterSwapInteractor.kt, app/src/main/java/org/p2p/wallet/jupiter/interactor/model/SwapPriceImpactType.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/price_impact/SwapPriceImpactView.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapFragment.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/mapper/SwapWidgetMapper.kt, app/src/main/res/values/swap_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8092
=> PWN-8092 - Swap. New warning view

app/src/main/java/org/p2p/wallet/bridge/claim/ClaimModule.kt, app/src/main/java/org/p2p/wallet/bridge/claim/interactor/ClaimInteractor.kt, app/src/main/java/org/p2p/wallet/bridge/claim/mapper/EthereumBundleMapper.kt, app/src/main/java/org/p2p/wallet/bridge/claim/repository/EthereumClaimInMemoryRepository.kt, app/src/main/java/org/p2p/wallet/bridge/claim/repository/EthereumClaimLocalRepository.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimPresenter.kt, app/src/main/java/org/p2p/wallet/bridge/interactor/EthereumInteractor.kt, app/src/main/java/org/p2p/wallet/home/HomeModule.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/OnHomeItemsClickListener.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenToClaimViewHolder.kt, app/src/main/java/org/p2p/wallet/transaction/model/TransactionState.kt, app/src/main/java/org/p2p/wallet/transaction/ui/NewTransactionProgressBottomSheet.kt, app/src/main/res/values/bridges_strings.xml, core/src/main/java/org/p2p/core/token/Token.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/EthTokenConverter.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/EthereumClaimToken.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumKitRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-8271
=> PWN-8271 - Add progress dialog for claiming bundles

app/src/main/java/org/p2p/wallet/bridge/send/statemachine/SendFeatureException.kt, app/src/main/java/org/p2p/wallet/bridge/send/statemachine/validator/SendBridgeValidator.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8311
PWN-8311 - show same error in case validateIsFeeMoreThanAmount
=> PWN-8311 - show same error in case validateIsFeeMoreThanAmount

app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/JupiterSwapFeeBuilder.kt
https://p2pvalidator.atlassian.net/browse/PWN-8212
caused by terrible DI graph
=> PWN-8212 - Fix crash on swap settings

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8307
PWN-8307 - fix send showSendNoTokens when no tokens logic
=> PWN-8307 - fix send showSendNoTokens when no tokens logic

app/src/main/java/org/p2p/wallet/home/MainFragment.kt
https://p2pvalidator.atlassian.net/browse/PWN-8177
- fixed crash when, somehow, showInternetError(true) called twice
=> PWN-8177 - fix double fragment adding crash

app/src/main/java/org/p2p/wallet/bridge/api/mapper/BridgeMapper.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeBundleFeesResponse.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeBundleResponse.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeSendFeesResponse.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/mapper/ClaimUiMapper.kt, app/src/main/java/org/p2p/wallet/bridge/model/BridgeBundle.kt, app/src/main/java/org/p2p/wallet/bridge/model/BridgeBundleFees.kt, app/src/main/java/org/p2p/wallet/bridge/send/model/BridgeSendFees.kt, app/src/main/java/org/p2p/wallet/bridge/send/statemachine/fee/SendBridgeFeeRelayerCounter.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/mapper/BridgeSendUiMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-8273
PWN-8273 - use fee in token now
=> PWN-8273 - use fee in token now

app/src/main/java/org/p2p/wallet/bridge/api/mapper/BridgeMapper.kt, app/src/main/java/org/p2p/wallet/bridge/model/BridgeBundle.kt, app/src/main/java/org/p2p/wallet/bridge/model/BridgeBundleFees.kt, app/src/main/java/org/p2p/wallet/bridge/model/BridgeFee.kt, app/src/main/java/org/p2p/wallet/bridge/send/model/BridgeSendFees.kt, app/src/main/java/org/p2p/wallet/bridge/send/model/BridgeSendTransactionDetails.kt, app/src/main/java/org/p2p/wallet/history/api/model/RpcHistoryTokenResponse.kt, app/src/main/java/org/p2p/wallet/history/api/model/RpcHistoryTransactionInfoResponse.kt, app/src/main/java/org/p2p/wallet/history/interactor/mapper/RpcHistoryTransactionConverter.kt, app/src/main/java/org/p2p/wallet/history/model/bridge/BridgeHistoryTransaction.kt, app/src/main/java/org/p2p/wallet/history/repository/remote/BridgeHistoryRepository.kt, app/src/main/java/org/p2p/wallet/history/ui/model/HistoryItem.kt, app/src/main/java/org/p2p/wallet/history/ui/token/adapter/HistoryAdapter.kt, app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/BridgePendingViewHolder.kt, app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt, app/src/main/res/values/bridges_strings.xml, core/src/main/java/org/p2p/core/token/SolAddress.kt, core/src/main/java/org/p2p/core/wrapper/HexString.kt, core/src/main/java/org/p2p/core/wrapper/eth/EthAddress.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/ERC20Tokens.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/internal/models/Signature.kt
https://p2pvalidator.atlassian.net/browse/PWN-8288
=> PWN-8288 - Fix history transaction parsing

app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt, app/src/main/java/org/p2p/wallet/common/crashlogging/helpers/CrashHttpLoggingInterceptor.kt, app/src/main/java/org/p2p/wallet/common/crashlogging/helpers/TimberCrashTree.kt, app/src/main/java/org/p2p/wallet/jupiter/interactor/JupiterSwapInteractor.kt, app/src/main/java/org/p2p/wallet/solana/SolanaNetworkObserver.kt, buildSrc/src/main/java/AppVersions.kt, core/src/main/java/org/p2p/core/rpc/JsonRpc.kt
https://p2pvalidator.atlassian.net/browse/PWN-8092
=> PWN-8092 - Swap. Add casting to double for correct behaviour

app/src/main/java/org/p2p/wallet/bridge/api/mapper/BridgeMapper.kt, app/src/main/java/org/p2p/wallet/bridge/api/request/SolanaTransferStatusesRpcRequest.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeTransactionStatusResponse.kt, app/src/main/java/org/p2p/wallet/bridge/send/model/BridgeSendTransactionDetails.kt, app/src/main/java/org/p2p/wallet/history/ui/model/HistoryItem.kt, app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/BridgePendingViewHolder.kt, app/src/main/java/org/p2p/wallet/home/HomeModule.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/UserTokensPolling.kt
https://p2pvalidator.atlassian.net/browse/PWN-8288
PWN-8288 - get send details and fix counting + pending send item fix
=> PWN-8288 - get send details and fix counting + pending send item fix

app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimContract.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimFragment.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimPresenter.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/dialog/BridgeSendFeeBottomSheet.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/mapper/BridgeSendUiMapper.kt, app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryTransaction.kt, app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt, app/src/main/res/layout/dialog_bridge_send_info.xml, app/src/main/res/layout/fragment_claim.xml, app/src/main/res/values/bridges_strings.xml, app/src/main/res/values/history_strings.xml, app/src/main/res/values/strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8393
https://p2pvalidator.atlassian.net/browse/PWN-8388
https://p2pvalidator.atlassian.net/browse/PWN-8413
PWN-8393 - remove network fees from BridgeSendFeeBottomSheet.kt
PWN-8388 - sent -> received copy change
PWN-8413 - use asApproximateUsd(withBraces = true) for formatting
=> PWN-8393, PWN-8388, PWN-8413 - Bridge fixes

app/src/main/java/org/p2p/wallet/AppModule.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/alarmlogger/AlarmErrorsLogger.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/alarmlogger/AlarmErrorsModule.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/alarmlogger/api/AlarmErrorsRequest.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/alarmlogger/api/AlarmErrorsServiceApi.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/alarmlogger/api/AlarmErrorsSwapRequest.kt, app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/interactor/JupiterSwapInteractor.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/utils/CoroutinesExtensions.kt, app/src/main/res/values/environment_config.xml
https://p2pvalidator.atlassian.net/browse/PWN-8417
=> PWN-8417 - Alarm logger from 2.6.2 to 2.7.0

app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendContract.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendFragment.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt, app/src/main/java/org/p2p/wallet/home/repository/UserTokensLocalRepository.kt, app/src/main/java/org/p2p/wallet/home/ui/new/NewSelectTokenContract.kt, app/src/main/java/org/p2p/wallet/home/ui/new/NewSelectTokenFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/new/NewSelectTokenPresenter.kt, app/src/main/java/org/p2p/wallet/newsend/SendModule.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendContract.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendFragment.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt, app/src/main/java/org/p2p/wallet/newsend/ui/stub/SendFeePayerPromptFragment.kt, app/src/main/java/org/p2p/wallet/svl/ui/send/SendViaLinkFragment.kt, app/src/main/java/org/p2p/wallet/svl/ui/send/SendViaLinkPresenter.kt, app/src/main/java/org/p2p/wallet/updates/SocketUpdatesManager.kt, core/src/main/java/org/p2p/core/token/Token.kt
https://p2pvalidator.atlassian.net/browse/PWN-8333
=> PWN-8333 - Sockets SEND SVL integration

app/src/main/java/org/p2p/wallet/infrastructure/network/NetworkModule.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/routes/JupiterSwapRoutesRemoteRepository.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/transaction/JupiterSwapTransactionRemoteRepository.kt, app/src/main/java/org/p2p/wallet/user/repository/prices/di/TokenPricesModule.kt, app/src/main/java/org/p2p/wallet/utils/CoroutinesExtensions.kt, app/src/test/java/org/p2p/wallet/utils/CoroutinesExtensionsTest.kt
=> [Cherry-Pick] PWN-8260 - added retry logic for timeout errors during getting swap routes

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
=> [Cherry-Pick] PWN-8245 - show rates loading warning in snackbar how it was before

app/src/main/java/org/p2p/wallet/home/repository/UserTokensLocalRepository.kt, app/src/main/java/org/p2p/wallet/home/repository/UserTokensRepository.kt, app/src/main/java/org/p2p/wallet/sell/interactor/SellInteractor.kt, app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8333 
=> PWN-8333 - Sell sockets integration

app/src/main/java/org/p2p/wallet/App.kt, app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryContract.kt, app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryFragment.kt, app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryPresenter.kt, app/src/main/java/org/p2p/wallet/home/repository/HomeDatabaseRepository.kt, app/src/main/java/org/p2p/wallet/home/repository/UserTokensLocalRepository.kt, app/src/main/java/org/p2p/wallet/home/repository/UserTokensRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-8333
=> PWN-8333 - Token history socket integration

app/src/main/java/org/p2p/wallet/bridge/api/mapper/BridgeMapper.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeBundleResponse.kt, app/src/main/java/org/p2p/wallet/bridge/api/response/BridgeTransactionStatusResponse.kt, app/src/main/java/org/p2p/wallet/bridge/claim/interactor/ClaimInteractor.kt, app/src/main/java/org/p2p/wallet/bridge/claim/model/ClaimDetails.kt, app/src/main/java/org/p2p/wallet/bridge/claim/model/ClaimStatus.kt, app/src/main/java/org/p2p/wallet/bridge/claim/repository/EthereumBridgeInMemoryRepository.kt, app/src/main/java/org/p2p/wallet/bridge/claim/repository/EthereumBridgeLocalRepository.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimPresenter.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/mapper/ClaimUiMapper.kt, app/src/main/java/org/p2p/wallet/bridge/interactor/EthereumInteractor.kt, app/src/main/java/org/p2p/wallet/bridge/model/BridgeBundle.kt, app/src/main/java/org/p2p/wallet/bridge/send/model/BridgeSendTransactionDetails.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/mapper/BridgeSendUiMapper.kt, app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryTransaction.kt, app/src/main/java/org/p2p/wallet/home/HomeModule.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt, app/src/main/java/org/p2p/wallet/transaction/model/NewShowProgress.kt, app/src/main/java/org/p2p/wallet/transaction/ui/NewTransactionProgressBottomSheet.kt
https://p2pvalidator.atlassian.net/browse/PWN-8271
PWN-8271 - show claim bundle progress details on tap on claim cell on home screen
=> PWN-8271 - show claim bundle progress details on tap on claim cell on home screen

app/src/main/java/org/p2p/wallet/jupiter/interactor/JupiterSwapInteractor.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/model/JupiterSwapRoute.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/routes/JupiterSwapRoutesMapper.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/transaction/JupiterSwapTransactionMapper.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/swap/model/Slippage.kt
https://p2pvalidator.atlassian.net/browse/PWN-8092
Check for high fees while swapping and show HighFees warning if fee more than given slippage
=> PWN-8092 - high fees warning

app/src/main/java/org/p2p/wallet/bridge/interactor/EthereumInteractor.kt, app/src/main/java/org/p2p/wallet/home/HomeModule.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/UserTokensPolling.kt
https://p2pvalidator.atlassian.net/browse/PWN-8438
PWN-8438 - move common logic with check ethAddressEnabledFeatureToggle is enabled in EthereumInteractor.kt to get rid of odd calls without feature toggle enabled
=> PWN-8438 - move common logic to EthereumInteractor

app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8267
Hiding skeleton/shimmer when another history page is loaded
=> PWN-8267 - hide shimmer when another history page is loaded

app/src/main/java/org/p2p/wallet/receive/eth/ReceiveEthereumContract.kt, app/src/main/java/org/p2p/wallet/receive/eth/ReceiveEthereumFragment.kt, app/src/main/java/org/p2p/wallet/receive/eth/ReceiveEthereumPresenter.kt, app/src/main/res/layout/fragment_ethereum_receive.xml
https://p2pvalidator.atlassian.net/browse/PWN-8477
PWN-8477 - getClaimMinAmountForFreeFee from ethereumInteractor on ReceiveEthereumFragment.kt
=> PWN-8477 - getClaimMinAmountForFreeFee from ethereumInteractor on ReceiveEthereumFragment.kt

app/src/main/java/org/p2p/wallet/home/MainFragment.kt, core/src/main/java/org/p2p/core/utils/LifecycleScopeRestarter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8465
PWN-8465 - fix showInternetError with LifecycleScopeRestarter.kt
=> PWN-8465 - fix showInternetError with LifecycleScopeRestarter.kt

app/src/main/java/org/p2p/wallet/rpc/repository/account/RpcAccountRemoteRepository.kt, app/src/main/java/org/p2p/wallet/rpc/repository/balance/RpcBalanceRemoteRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-8470
- Since the SOL token balance loads separately from other tokens, it requires a separate request config
=> PWN-8470 - loading sol balance with commitment=confirmed

app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterBaseTest.kt, app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterPriceImpactTest.kt, app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapTestHelpers.kt
Updated tests according new merged code
=> NO-TICKET - fixed swap unit tests

app/src/main/java/org/p2p/wallet/bridge/model/BridgeBundle.kt, app/src/main/java/org/p2p/wallet/history/interactor/mapper/RpcHistoryTransactionConverter.kt, app/src/main/java/org/p2p/wallet/history/model/bridge/BridgeHistoryTransaction.kt, app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryTransaction.kt, app/src/main/java/org/p2p/wallet/history/repository/remote/BridgeHistoryRepository.kt, app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-8400
PWN-8400 - filter transactions that are not in process to show
=> PWN-8400 - filter transactions that are not in process to show

app/src/main/java/org/p2p/wallet/newsend/SendFeeRelayerManager.kt, app/src/main/java/org/p2p/wallet/newsend/interactor/SendInteractor.kt, app/src/main/java/org/p2p/wallet/newsend/model/CalculationMode.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8248
=> PWN-8248 - Update labels when view created again

app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimPresenter.kt, app/src/main/res/layout/fragment_claim.xml, app/src/main/res/values/bridges_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8479
PWN-8479 - claim changes according to designs
=> PWN-8479 - claim changes according to designs

app/src/main/java/org/p2p/wallet/common/mvp/BasePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8329
- Fixed attaching to polling; it should be attached only after inital loading is completed
=> PWN-8329 - fixed initial banner with no tokens

app/src/main/java/org/p2p/wallet/AppModule.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/UserTokensPolling.kt, app/src/main/java/org/p2p/wallet/svl/ui/receive/ReceiveViaLinkPresenter.kt, app/src/main/java/org/p2p/wallet/updates/SocketUpdatesManager.kt, core/src/main/java/org/p2p/core/network/ConnectionManager.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/internal/core/EthereumKit.kt, solana/src/main/java/org/p2p/solanaj/ws/SocketClientCreateResult.kt, solana/src/main/java/org/p2p/solanaj/ws/SubscriptionSocketClientFactory.kt, solana/src/main/java/org/p2p/solanaj/ws/impl/SubscriptionWebSocketClient.kt
https://p2pvalidator.atlassian.net/browse/PWN-8470
- Reworked `ConnectionManager` - we can no longer rely on system statuses provided by ConnectivityManager, as it do not accurately display the factual state
- Fixed reconnecting to websockets
=> PWN-8470 - fixed problems related to disconnected inet

app/src/main/java/org/p2p/wallet/bridge/claim/ui/mapper/ClaimUiMapper.kt, app/src/main/java/org/p2p/wallet/bridge/model/BridgeFee.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/mapper/BridgeSendUiMapper.kt, app/src/main/java/org/p2p/wallet/history/interactor/mapper/RpcHistoryTransactionConverter.kt, app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsPresenter.kt, app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt, app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/BridgePendingViewHolder.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/environment/NetworkServicesUrlProvider.kt, app/src/main/java/org/p2p/wallet/transaction/model/NewShowProgress.kt, app/src/main/java/org/p2p/wallet/transaction/ui/NewTransactionProgressBottomSheet.kt, app/src/main/res/values/bridges_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8415
https://p2pvalidator.atlassian.net/browse/PWN-8432
https://p2pvalidator.atlassian.net/browse/PWN-8563
66ca6ed0(PWN-8415 - get amount from bundles not count it with fee)
ac68526b(PWN-8432 - fix colors in details for send to Ethereum)
1653a0c4(PWN-8563 - fix claim colors in bottomSheet + pending viewHolders)
=> PWN-8415, PWN-8432, PWN-8563 - Bridge fixes

app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerViaLinkInteractor.kt, app/src/main/java/org/p2p/wallet/rpc/interactor/TransactionInteractor.kt, app/src/main/java/org/p2p/wallet/rpc/repository/balance/RpcBalanceRemoteRepository.kt, app/src/main/java/org/p2p/wallet/rpc/repository/history/RpcTransactionRemoteRepository.kt, app/src/main/java/org/p2p/wallet/rpc/repository/history/RpcTransactionRepository.kt, app/src/main/java/org/p2p/wallet/svl/interactor/ReceiveViaLinkInteractor.kt, app/src/main/java/org/p2p/wallet/svl/interactor/SendViaLinkInteractor.kt, app/src/main/java/org/p2p/wallet/updates/subscribe/SolanaAccountUpdateSubscriber.kt, app/src/main/java/org/p2p/wallet/updates/subscribe/SplTokenProgramSubscriber.kt, solana/src/main/java/org/p2p/solanaj/model/types/ConfirmationStatus.kt, solana/src/main/java/org/p2p/solanaj/model/types/RequestConfiguration.kt
https://p2pvalidator.atlassian.net/browse/PWN-8603
- added preflightCommitment=confirmed for svl claiming
- also unified commitment value using solana sdk enum `ConfirmationStatus`
=> PWN-8603 - added preflightCommitment=confirmed for svl claiming

app/src/main/java/org/p2p/wallet/bridge/claim/ui/mapper/ClaimUiMapper.kt, app/src/main/java/org/p2p/wallet/bridge/send/statemachine/fee/SendBridgeTransactionLoader.kt, app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetFragment.kt, app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt, app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/transaction/ui/NewTransactionProgressBottomSheet.kt
https://p2pvalidator.atlassian.net/browse/PWN-8609
https://p2pvalidator.atlassian.net/browse/PWN-8562
PWN-8609 - Sent to <-> Send to Ethereum 
PWN-8562 - fix free paid returned in progress bottomsheet
=> PWN-8609, PWN-8562 - Bridge fixes 

app/src/main/java/org/p2p/wallet/home/db/TokenDao.kt, app/src/main/java/org/p2p/wallet/home/repository/HomeDatabaseRepository.kt, app/src/main/java/org/p2p/wallet/home/repository/HomeLocalRepository.kt, app/src/main/java/org/p2p/wallet/home/repository/UserTokensLocalRepository.kt, app/src/main/java/org/p2p/wallet/home/repository/UserTokensRepository.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/updates/SocketUpdatesManager.kt, app/src/main/java/org/p2p/wallet/updates/SubscriptionUpdatesManager.kt, app/src/main/java/org/p2p/wallet/updates/handler/SolanaAccountUpdateHandler.kt, app/src/main/java/org/p2p/wallet/updates/handler/SplTokenProgramUpdateHandler.kt
https://p2pvalidator.atlassian.net/browse/PWN-8470
- Fixed data race while updating balances from multiple sources at once
=> PWN-8470 - fixed user tokens updating

app/src/main/java/org/p2p/wallet/bridge/claim/ui/dialogs/ClaimInfoBottomSheet.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt, app/src/main/java/org/p2p/wallet/history/interactor/mapper/RpcHistoryTransactionConverter.kt, app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryTransaction.kt, app/src/main/java/org/p2p/wallet/transaction/model/HistoryTransactionStatus.kt, app/src/main/java/org/p2p/wallet/utils/TransactionImageViewExtensions.kt, app/src/main/res/layout/dialog_claim_info.xml, app/src/main/res/values/bridges_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8360
https://p2pvalidator.atlassian.net/browse/PWN-8397
PWN-8397 - pending transactions fix 
PWN-8360 - fix amounts when use bridges bundle
=> PWN-8397, PWN-8360 - Bridges Pendings Fixes

app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt, app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/ReserveUsernamePresenter.kt, app/src/main/java/org/p2p/wallet/auth/username/repository/UsernameRemoteRepository.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt, app/src/main/res/values/onboarding_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8504 
=> PWN-8504 - Additional changes for alarms

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
https://p2pvalidator.atlassian.net/browse/8625
- Fixed joining load tokens job, as a result, initial tokens state works correct
=> PWN-8625 - fixed empty state at app launch

app/src/main/java/org/p2p/wallet/common/feature_toggles/di/FeatureTogglesModule.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/SwapRoutesValidationEnabledFeatureToggle.kt, app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/analytics/JupiterSwapMainScreenAnalytics.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/routes/JupiterSwapRouteValidator.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/routes/JupiterSwapRoutesRemoteRepository.kt, app/src/main/java/org/p2p/wallet/rpc/repository/solana/RpcSolanaApi.kt, app/src/main/java/org/p2p/wallet/rpc/repository/solana/RpcSolanaRemoteRepository.kt, solana/src/main/java/org/p2p/solanaj/model/types/Encoding.kt, solana/src/main/java/org/p2p/solanaj/rpc/RpcSolanaRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-8493
- instead of validating route by route, we are doing async jobs to validate them all. Results are astonishing fast!
=> PWN-8493 - Validate ALL swap routes

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8625
- Fixed again =\
=> PWN-8625 - fixed again initial zero token state

app/src/main/res/layout/fragment_ethereum_receive.xml, app/src/main/res/values/strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8630
PWN-8630 - receive description added
=> PWN-8630 - receive description added

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumKitRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-8660
=> PWN-8660 - Fix eth balance update

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8660
=> PWN-8660 - Fix tokens updating on Home Screen

app/src/main/java/org/p2p/wallet/history/interactor/mapper/RpcHistoryTransactionConverter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8562
PWN-8562 - fix server changes - find fee with not empty symbol for getting symbol and decimals
=> PWN-8562 - fix server changes - find fee with not empty symbol for getting symbol and decimals

app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt
https://p2pvalidator.atlassian.net/browse/PWN-7901
- Fetch source username domain instead of using default one (feature value)
=> PWN-7901 - show source username domain at home screen

ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumKitRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-8654 
PWN-8654 - fix adding metadata everytime in localTokensMetadata
=> PWN-8654 - fix adding metadata everytime in localTokensMetadata

app/src/main/java/org/p2p/wallet/bridge/claim/ui/dialogs/ClaimInfoBottomSheet.kt, app/src/main/java/org/p2p/wallet/bridge/claim/ui/mapper/ClaimUiMapper.kt, app/src/main/java/org/p2p/wallet/bridge/model/BridgeAmount.kt, app/src/main/java/org/p2p/wallet/bridge/model/BridgeFee.kt
https://p2pvalidator.atlassian.net/browse/PWN-8589
@kabramovp2p approved
=> PWN-8589 - Add fee to total amount if user pays for claim

app/src/main/java/org/p2p/wallet/auth/gateway/repository/mapper/GatewayServiceCreateWalletMapper.kt, app/src/main/java/org/p2p/wallet/auth/gateway/repository/model/GatewayOnboardingMetadata.kt, app/src/test/java/org/p2p/wallet/auth/gateway/repository/mapper/GatewayServiceOnboardingMetadataCipherTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-8340
PWN-8340 - update metadata structure
=> PWN-8340 - update metadata structure

app/src/main/java/org/p2p/wallet/infrastructure/network/environment/NetworkServicesUrlProvider.kt, buildSrc/src/main/java/AppVersions.kt
to analyze what went wrong in Sentry
=> NO-TICKET - add logging for env configs

ethereumkit/src/main/java/org/p2p/ethereumkit/internal/models/Signature.kt
=> NO-TICKET - fix bug with obfuscation

app/src/main/res/layout/dialog_history_send_link_details.xml
https://p2pvalidator.atlassian.net/browse/PWN-8624
=> PWN-8624 - XML ids

app/src/main/java/org/p2p/wallet/alarmlogger/api/AlarmErrorsSwapRequest.kt, app/src/main/java/org/p2p/wallet/alarmlogger/model/AlarmSwapErrorConverter.kt, app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapProfiler.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateRoutesRefresher.kt, app/src/test/java/org/p2p/wallet/jupiter/statemanager/SwapProfilerTest.kt, app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterBaseTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-8693
Adding more info for swap alarm
- Added diff time for last route fetched and last transaction for route created
- Added tokenA and tokenB balances
=> PWN-8693 - send to alarm tx creation and routes fetch diff time + token balances

app/src/test/java/org/p2p/wallet/auth/interactor/GatewayMetadataMergerTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-8348
PWN-8348 - metadata merger tests to check logic when same metaTimestampSec logic and when it is different
=> PWN-8348 - metadata merger tests

app/src/main/java/org/p2p/wallet/striga/StrigaUserConstants.kt, app/src/main/java/org/p2p/wallet/striga/user/api/StrigaApi.kt, app/src/main/java/org/p2p/wallet/striga/user/api/StrigaCreateUserRequest.kt, app/src/main/java/org/p2p/wallet/striga/user/api/response/StrigaCreateUserResponse.kt, app/src/main/java/org/p2p/wallet/striga/user/model/StrigaUserInitialDetails.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserRemoteRepository.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserRepository.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserRepositoryMapper.kt, app/src/test/java/org/p2p/wallet/striga/user/repository/StrigaUserRepositoryMapperTest.kt, app/src/test/java/org/p2p/wallet/striga/user/repository/StrigaUserRepositoryTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-8450
Create user API method
=> PWN-8450 - Striga API. Create User

app/src/main/java/org/p2p/wallet/striga/model/StrigaApiError.kt, app/src/main/java/org/p2p/wallet/striga/model/StrigaDataLayerError.kt, app/src/main/java/org/p2p/wallet/striga/user/api/StrigaApi.kt, app/src/main/java/org/p2p/wallet/striga/user/api/StrigaResendSmsRequest.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserRemoteRepository.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-8452
- added resend sms method
- added doc to API to understand what errors to catch
=> PWN-8452 - Striga API. resend_sms

app/src/main/java/org/p2p/wallet/common/ui/SimpleMaskFormatter.kt, app/src/main/java/org/p2p/wallet/striga/model/StrigaApiError.kt, app/src/main/java/org/p2p/wallet/striga/model/StrigaDataLayerHttpErrorParser.kt, app/src/main/java/org/p2p/wallet/striga/signup/StrigaSignUpFirstStepContract.kt, app/src/main/java/org/p2p/wallet/striga/signup/StrigaSignUpSecondStepContract.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpFirstStepFragment.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpFirstStepPresenter.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpSecondStepFragment.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpSecondStepPresenter.kt, app/src/main/java/org/p2p/wallet/striga/signup/validation/BirthdayInputValidator.kt, app/src/test/java/org/p2p/wallet/striga/model/StrigaDataLayerHttpError400And409ParserTest.kt, app/src/test/java/org/p2p/wallet/striga/signup/ui/StrigaSignupFirstStepPresenterTest.kt, app/src/test/java/org/p2p/wallet/striga/signup/ui/StrigaSignupSecondStepPresenterTest.kt, app/src/test/java/org/p2p/wallet/striga/signup/validation/BirthdayInputValidatorTest.kt, app/src/test/java/org/p2p/wallet/striga/user/repository/StrigaUserRepositoryTest.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitEditText.kt
https://p2pvalidator.atlassian.net/browse/PWN-8635
- clear error on input
- fixed stroke for UiKitEditText state
- fixed mask formatting for non-space placeholders
- fixed birthday year validation in edge cases
=> PWN-8635 - minor fixes

app/src/main/java/org/p2p/wallet/auth/ui/generalerror/timer/OnboardingGeneralErrorTimerFragment.kt, app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt, app/src/main/java/org/p2p/wallet/striga/finish/StrigaSignupFinishFragment.kt, app/src/main/java/org/p2p/wallet/striga/onboarding/StrigaOnboardingContract.kt, app/src/main/java/org/p2p/wallet/striga/onboarding/StrigaOnboardingFragment.kt, app/src/main/java/org/p2p/wallet/striga/onboarding/StrigaOnboardingPresenter.kt, app/src/main/java/org/p2p/wallet/utils/OnboardingSpanUtils.kt, app/src/main/res/layout/fragment_striga_onboarding.xml, app/src/main/res/layout/fragment_striga_signup_finish.xml, app/src/main/res/values/striga_strings.xml, ui-kit/src/main/kotlin/org/p2p/uikit/utils/SpanUtils.kt
https://p2pvalidator.atlassian.net/browse/PWN-8842
https://p2pvalidator.atlassian.net/browse/PWN-8836
https://p2pvalidator.atlassian.net/browse/PWN-8835
https://p2pvalidator.atlassian.net/browse/PWN-8834
=> PWN-8834 - Striga bugfixes

app/src/main/java/org/p2p/wallet/AppModule.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/inapp/DebugTogglesFeatureFlag.kt, app/src/main/java/org/p2p/wallet/infrastructure/StorageModule.kt
https://p2pvalidator.atlassian.net/browse/PWN-8333
=> PWN-8833 - Save local FT after relogin

app/src/main/java/org/p2p/wallet/auth/ui/phone/countrypicker/CountryCodePickerPresenter.kt, app/src/main/java/org/p2p/wallet/striga/presetpicker/StrigaPresetDataSearcher.kt
https://p2pvalidator.atlassian.net/browse/PWN-8845
=> PWN-8845 - Change country detect pattern

app/src/main/java/org/p2p/wallet/auth/repository/CountryCodeInMemoryRepository.kt, app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt, gradle.properties
https://p2pvalidator.atlassian.net/browse/PWN-8853
=> PWN-8853 - Change logic of country detection

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
~~https://p2pvalidator.atlassian.net/browse/~~
- Fixed showing refreshing status when something is loading at home screen
=> NO-TICKET - fix home refreshing

app/src/main/java/org/p2p/wallet/auth/model/CountryCode.kt, app/src/main/java/org/p2p/wallet/striga/signup/StrigaSignUpFirstStepContract.kt, app/src/main/java/org/p2p/wallet/striga/signup/StrigaSignUpSecondStepContract.kt, app/src/main/java/org/p2p/wallet/striga/signup/interactor/StrigaSignupInteractor.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpFirstStepFragment.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpFirstStepPresenter.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpSecondStepFragment.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpSecondStepPresenter.kt, app/src/main/java/org/p2p/wallet/striga/signup/validation/PhoneNumberInputValidator.kt, app/src/main/java/org/p2p/wallet/striga/signup/validation/StrigaSignupDataValidator.kt, app/src/main/java/org/p2p/wallet/striga/ui/TopUpWalletPresenter.kt, app/src/test/java/org/p2p/wallet/striga/signup/interactor/StrigaSignupInteractorTest.kt, app/src/test/java/org/p2p/wallet/striga/signup/ui/StrigaSignupFirstStepPresenterTest.kt, app/src/test/java/org/p2p/wallet/striga/signup/ui/StrigaSignupSecondStepPresenterTest.kt, app/src/test/java/org/p2p/wallet/striga/signup/validation/PhoneNumberInputValidatorTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-8804
Added dynamic input validation when user clicks `next` button
=> PWN-8804 striga dynamic input validation

app/src/main/java/org/p2p/wallet/common/ui/recycler/adapter/DividerItemDecorator.kt, app/src/main/java/org/p2p/wallet/striga/presetpicker/StrigaPresetDataPickerFragment.kt, app/src/main/java/org/p2p/wallet/striga/presetpicker/mapper/StrigaItemCellMapper.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpFirstStepFragment.kt, app/src/main/res/layout/widget_search_view.xml, ui-kit/src/main/kotlin/org/p2p/uikit/components/left_side/UiKitLeftSideView.kt, ui-kit/src/main/res/layout/widget_icon_wrapper_single.xml, ui-kit/src/main/res/layout/widget_left_side_icon_triple_text.xml
https://p2pvalidator.atlassian.net/browse/PWN-8845
=> PWN-8845 - Change country picker design

ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitEditText.kt
=> NO-TICKET - Add disable state for UiKitEditText.kt

app/src/main/java/org/p2p/wallet/striga/ui/TopUpWalletBottomSheet.kt
=> NO-TICKET - fix striga onboarding navigation

.github/actions/setup-slack/action.yml, .github/actions/setup-version-build/action.yml, .github/workflows/pull-request-check.yml, app/build.gradle.kts, bash_scripts/slack_upload_changelog.sh, build.gradle, buildSrc/src/main/java/AppVersions.kt, buildSrc/src/main/java/Versions.kt, buildSrc/src/main/kotlin/org/p2p/wallet/android/application.gradle.kts
1. Adding a text to upload APK message in slack with current build version name
2. A new type of version name
3. Added manual feature builds for pull requests
=> NO-TICKET - Manual feature build

.github/actions/setup-changelog/action.yml, .github/actions/setup-slack/action.yml, .github/workflows/feature-build.yml, .github/workflows/pull-request-check.yml, .github/workflows/release-build.yml
=> NO-TICKET - Changelog ref names corrections because of new workflow triggers

.github/actions/setup-changelog/action.yml, .github/workflows/scheduled-build.yml
Added changelog for daily builds
=> NO-TICKET - Triggering actions

app/build.gradle.kts, app/src/main/java/org/p2p/wallet/auth/interactor/MetadataInteractor.kt, app/src/main/java/org/p2p/wallet/striga/StrigaModule.kt, app/src/main/java/org/p2p/wallet/striga/kyc/StrigaKycModule.kt, app/src/main/java/org/p2p/wallet/striga/kyc/sdk/StrigaKycSdkFacade.kt, app/src/main/java/org/p2p/wallet/striga/kyc/sdk/StrigaKycSdkListeners.kt, app/src/main/java/org/p2p/wallet/striga/kyc/sdk/StrigaSdkLogger.kt, app/src/main/java/org/p2p/wallet/striga/kyc/ui/StrigaKycContract.kt, app/src/main/java/org/p2p/wallet/striga/kyc/ui/StrigaKycFragment.kt, app/src/main/java/org/p2p/wallet/striga/kyc/ui/StrigaKycInteractor.kt, app/src/main/java/org/p2p/wallet/striga/kyc/ui/StrigaKycPresenter.kt, app/src/main/java/org/p2p/wallet/striga/user/api/StrigaApi.kt, app/src/main/java/org/p2p/wallet/striga/user/api/StrigaStartKycResponse.kt, app/src/main/java/org/p2p/wallet/striga/user/api/request/StrigaCreateUserRequest.kt, app/src/main/java/org/p2p/wallet/striga/user/api/request/StrigaResendSmsRequest.kt, app/src/main/java/org/p2p/wallet/striga/user/api/request/StrigaStartKycRequest.kt, app/src/main/java/org/p2p/wallet/striga/user/api/request/StrigaVerifyMobileNumberRequest.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserRemoteRepository.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserRepository.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserRepositoryMapper.kt, app/src/main/res/layout/fragment_striga_kyc.xml, app/src/test/java/org/p2p/wallet/striga/user/repository/StrigaUserRepositoryTest.kt, build.gradle, gradle.properties
https://p2pvalidator.atlassian.net/browse/PWN-8734
=> PWN-8734 - Start integrating with sumsub sdk

app/src/main/java/org/p2p/wallet/auth/AuthModule.kt, app/src/main/java/org/p2p/wallet/auth/interactor/restore/TorusKeyInteractor.kt, app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt, app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingContract.kt, app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingPresenter.kt, app/src/main/java/org/p2p/wallet/auth/web3authsdk/GoogleSignInHelper.kt, app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApi.kt, app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApiClient.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/environment/NetworkServicesUrlProvider.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/environment/TorusEnvironment.kt, app/src/main/java/org/p2p/wallet/striga/ui/TopUpWalletPresenter.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserRemoteRepository.kt, app/src/main/res/values/environment_config.xml
- just small renaming to match real life and how everything is connected
=> NO-TICKET - Small refactor to Web3Auth class

app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt, app/src/main/java/org/p2p/wallet/striga/presetpicker/StrigaPresetDataPickerFragment.kt, app/src/main/java/org/p2p/wallet/striga/presetpicker/StrigaPresetPickItemDecorator.kt, app/src/main/res/drawable/list_divider_smoke.xml, app/src/main/res/layout/fragment_striga_preset_data_picker.xml, app/src/main/res/layout/widget_search_view.xml, ui-kit/src/main/kotlin/org/p2p/uikit/organisms/sectionheader/UiKitSectionHeader.kt
https://p2pvalidator.atlassian.net/browse/PWN-8839
=> PWN-8839 - Fix striga picker design 

app/src/main/java/org/p2p/wallet/smsinput/BaseSmsInputFragment.kt, app/src/main/java/org/p2p/wallet/smsinput/SmsInputFactory.kt, app/src/main/java/org/p2p/wallet/smsinput/SmsInputNavigationStrategy.kt
https://p2pvalidator.atlassian.net/browse/PWN-8875
- Fixed sms input navigation
=> PWN-8875 - fixed sms input backstack managing

app/src/main/java/org/p2p/wallet/striga/user/api/response/StrigaCreateUserResponse.kt, app/src/main/java/org/p2p/wallet/striga/user/model/StrigaUserInitialDetails.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserRepositoryMapper.kt, app/src/test/java/org/p2p/wallet/striga/signup/interactor/StrigaSignupInteractorTest.kt, app/src/test/java/org/p2p/wallet/striga/user/repository/StrigaUserRepositoryMapperTest.kt, app/src/test/java/org/p2p/wallet/striga/user/repository/StrigaUserRepositoryTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-8940
Added `@SerializedName` for every field that is mapped from json
=> PWN-8940 - fixed models for proguarded builds

app/src/main/java/org/p2p/wallet/common/ui/bottomsheet/BaseDoneBottomSheet.kt
https://p2pvalidator.atlassian.net/browse/PWN-8945
=> PWN-8945 - Fix crash with bottom sheet

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/models/HomeScreenViewState.kt, app/src/main/java/org/p2p/wallet/infrastructure/StorageModule.kt, app/src/main/java/org/p2p/wallet/striga/kyc/ui/StrigaKycFragment.kt, app/src/main/java/org/p2p/wallet/striga/user/StrigaStorage.kt, app/src/main/java/org/p2p/wallet/striga/user/StrigaStorageContract.kt, app/src/main/java/org/p2p/wallet/striga/user/interactor/StrigaUserInteractor.kt, app/src/main/java/org/p2p/wallet/striga/user/model/StrigaUserVerificationStatus.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserStatusDestinationMapper.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserStatusRepository.kt, app/src/main/java/org/p2p/wallet/utils/NavigationExtensions.kt
https://p2pvalidator.atlassian.net/browse/PWN-8946
- fixed back navigation in StrigaKycFragment
- fixed bank transfer navigation
- added realtime home banners update (combined with tokens flow)
- reverted StrigaStorage to keep striga user status
- reordered striga kyc statuses to be able to use ordinal value
=> PWN-8946 - striga bugfixes

.github/actions/setup-slack/action.yml, .github/workflows/release-build.yml, app/src/main/java/org/p2p/wallet/settings/ui/security/SecurityAndPrivacyFragment.kt
https://p2pvalidator.atlassian.net/browse/PWN-8847
=> NO-TICKET - Minor text fixes in CI/CD

app/src/main/java/org/p2p/wallet/auth/interactor/MetadataInteractor.kt, app/src/main/java/org/p2p/wallet/debug/pushservice/DebugWeb3Fragment.kt, app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsFragment.kt, app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsMapper.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/provider/SeedPhraseProvider.kt, app/src/main/java/org/p2p/wallet/striga/model/StrigaDataLayerResult.kt, app/src/main/java/org/p2p/wallet/striga/ui/TopUpWalletPresenter.kt, app/src/main/java/org/p2p/wallet/striga/user/interactor/StrigaUserInteractor.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserStatusRepository.kt, app/src/main/res/layout/fragment_debug_web3.xml, app/src/main/res/layout/fragment_striga_sign_up_second_step.xml, app/src/main/res/values/settings_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8959 
https://p2pvalidator.atlassian.net/browse/PWN-8953
https://p2pvalidator.atlassian.net/browse/PWN-8917
=> PWN-8959 PWN-8953 PWN-8917 - Striga. Bugfixes

app/src/main/java/org/p2p/wallet/common/InAppFeatureFlags.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/inapp/StrigaSimulateMobileAlreadyVerifiedFlag.kt, app/src/main/java/org/p2p/wallet/smsinput/SmsInputContract.kt, app/src/main/java/org/p2p/wallet/smsinput/onboarding/OnboardingSmsInputFragment.kt, app/src/main/java/org/p2p/wallet/smsinput/striga/StrigaSmsInputFragment.kt, app/src/main/java/org/p2p/wallet/smsinput/striga/StrigaSmsInputPresenter.kt, app/src/main/java/org/p2p/wallet/smsinput/updatedevice/UpdateDeviceSmsInputFragment.kt, app/src/main/java/org/p2p/wallet/striga/model/StrigaDataLayerError.kt, app/src/main/java/org/p2p/wallet/striga/model/StrigaDataLayerHttpErrorParser.kt, app/src/main/java/org/p2p/wallet/striga/signup/StrigaSignUpSecondStepContract.kt, app/src/main/java/org/p2p/wallet/striga/signup/interactor/StrigaSignupInteractor.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpFirstStepFragment.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpSecondStepFragment.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpSecondStepPresenter.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignupErrorNumberAlreadyUsedFragment.kt, app/src/main/java/org/p2p/wallet/striga/sms/StrigaSmsErrorViewType.kt, app/src/main/java/org/p2p/wallet/striga/user/api/response/StrigaUserDetailsResponse.kt, app/src/main/java/org/p2p/wallet/striga/user/model/StrigaUserDetails.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserRepositoryMapper.kt, app/src/main/res/values/striga_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8938
- Added mobile already user error handling while creating striga user
=> PWN-8938 - striga - mobile already used error handling

app/src/main/java/org/p2p/wallet/history/ui/sendvialink/HistorySendLinksFragment.kt, app/src/main/res/layout/fragment_history_send_links.xml, ui-kit/src/main/kotlin/org/p2p/uikit/components/finance_block/UiKitMainCellView.kt
https://p2pvalidator.atlassian.net/browse/PWN-8706
PWN-8706 - redesign send via link history screen
=> PWN-8706 - redesign send via link history screen

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
- fixed swap button click handling
=> NO-TICKET - fix swap button click handling

app/src/main/java/org/p2p/wallet/auth/interactor/MetadataInteractor.kt, app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApiClient.kt, app/src/main/java/org/p2p/wallet/settings/ui/devices/DevicesFragment.kt, app/src/main/java/org/p2p/wallet/settings/ui/devices/DevicesPresenter.kt, app/src/main/java/org/p2p/wallet/settings/ui/mail/SettingsEmailConfirmPresenter.kt, app/src/main/res/values/settings_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8341
PWN-8341 - integration with refresh device share method and save it on device for future usage also fixes PWN-8979
=> PWN-8341 - integration with refresh device share method and save it on device for future usage

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8678
PWN-8678 - restore latest home state on attach
=> PWN-8678 - restore latest home state on attach

app/src/main/java/org/p2p/wallet/alarmlogger/model/AlarmSendErrorConverter.kt, app/src/main/java/org/p2p/wallet/alarmlogger/model/AlarmSwapErrorConverter.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/data/transactionerrors/RpcTransactionError.kt, app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/interactor/JupiterSwapInteractor.kt, app/src/main/java/org/p2p/wallet/jupiter/interactor/JupiterSwapSendTransactionDelegate.kt, app/src/main/java/org/p2p/wallet/jupiter/interactor/JupiterSwapTokensResult.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapState.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateRoutesRefresher.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/handler/SwapStateLoadingTransactionHandler.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/handler/SwapStateRoutesLoadedHandler.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/handler/SwapStateSwapLoadedHandler.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/info/SwapInfoBottomSheet.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/routes/SwapSelectRoutesBottomSheet.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/JupiterSwapSettingsPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/settings/presenter/SwapContentSettingsMapper.kt, app/src/main/java/org/p2p/wallet/utils/Base58String.kt, app/src/test/java/org/p2p/wallet/jupiter/interactor/JupiterSendSwapTransactionDelegateTest.kt, app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterBaseTest.kt, app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterExecuteTransactionTest.kt, app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterTestPresenterBuilder.kt, app/src/test/java/org/p2p/wallet/utils/TestUtils.kt
https://p2pvalidator.atlassian.net/browse/PWN-8753
- see the comments
=> PWN-8753 - Swap. Fix InvalidTimestamp from Whirlpools

app/src/main/java/org/p2p/wallet/common/feature_toggles/di/FeatureTogglesModule.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/remote_config/AppFirebaseRemoteConfig.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/remote_config/FeatureTogglesValuesSource.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/remote_config/LocalFirebaseRemoteConfig.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/remote_config/RemoteConfigValuesProvider.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/RemoteFeatureToggle.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/SwapRoutesRefreshFeatureToggle.kt, app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt, app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterBaseTest.kt, app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterExecuteTransactionTest.kt, app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterPriceImpactTest.kt, app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterTokenAmountChangeTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-9001
=> PWN-9001 - Swap refresh routes interval via feature toggle

app/src/main/java/org/p2p/wallet/settings/ui/devices/DevicesPresenter.kt, app/src/main/java/org/p2p/wallet/smsinput/updatedevice/UpdateDeviceSmsInputPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9040
PWN-9040 - phone number reset on block screen
=> PWN-9040 - phone number reset on block screen

app/src/main/java/org/p2p/wallet/settings/ui/security/SecurityAndPrivacyFragment.kt, app/src/main/java/org/p2p/wallet/utils/DrawableUtils.kt, ui-kit/src/main/kotlin/org/p2p/uikit/atoms/UiKitStartAmountView.kt
https://p2pvalidator.atlassian.net/browse/PWN-8992
PWN-8992 - make utils to get drawable with needed sizes to fix issues with icon size on UiKitStartAmountView.kt
=> PWN-8992 - make utils to get drawable with needed sizes to fix issues with icon size on UiKitStartAmountView.kt

app/src/main/java/org/p2p/wallet/settings/ui/devices/DevicesContract.kt, app/src/main/java/org/p2p/wallet/settings/ui/devices/DevicesFragment.kt, app/src/main/java/org/p2p/wallet/settings/ui/devices/DevicesPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9057
PWN-9057 - show common error on GatewayHandledState.CriticalError
=> PWN-9057 - show common error on GatewayHandledState.CriticalError

app/src/main/res/layout/fragment_email_confirm.xml, app/src/main/res/values/onboarding_strings.xml, app/src/main/res/values/settings_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-9086
https://p2pvalidator.atlassian.net/browse/PWN-9041
PWN-9086 - update text on confirm email screen 
PWN-9041 - update timer screen text
=> PWN-9086, PWN-9041 - update device share flow texts

app/src/main/res/values/environment_config.xml
=> NO-TICKET - fix striga base url

app/src/main/java/org/p2p/wallet/settings/ui/devices/DevicesPresenter.kt, app/src/main/java/org/p2p/wallet/settings/ui/mail/SettingsEmailConfirmPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9092
PWN-9092 - fix error handling on update share
=> PWN-9092 - fix error handling on update share

app/src/main/res/raw/striga_occupation_values.json
https://p2pvalidator.atlassian.net/browse/PWN-903
- fixed behavior for occupation list
=> PWN-9036 - striga fix occupation list

app/src/main/java/org/p2p/wallet/auth/gateway/repository/mapper/GatewayServiceCreateWalletMapper.kt, app/src/main/java/org/p2p/wallet/auth/interactor/MetadataInteractor.kt, app/src/test/java/org/p2p/wallet/auth/interactor/GatewayMetadataMergerTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-9092
PWN-9092 - code clean up
=> PWN-9092 - code clean up

app/src/main/java/org/p2p/wallet/alarmlogger/AlarmErrorsModule.kt, app/src/main/java/org/p2p/wallet/alarmlogger/api/AlarmErrorStrigaRequest.kt, app/src/main/java/org/p2p/wallet/alarmlogger/logger/AlarmErrorsLogger.kt, app/src/main/java/org/p2p/wallet/alarmlogger/model/AlarmStrigaErrorConverter.kt, app/src/main/java/org/p2p/wallet/alarmlogger/model/StrigaAlarmError.kt, app/src/main/java/org/p2p/wallet/alarmlogger/model/StrigaErrorConverter.kt, app/src/main/java/org/p2p/wallet/striga/kyc/ui/StrigaKycPresenter.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpSecondStepPresenter.kt, app/src/test/java/org/p2p/wallet/striga/signup/ui/StrigaSignupSecondStepPresenterTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-8830
=> PWN-8830 - Striga alarm errors

app/src/main/java/org/p2p/wallet/home/model/HomeElementItem.kt, app/src/main/java/org/p2p/wallet/home/model/HomePresenterMapper.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/UserTokensPolling.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/BridgeTokenToClaimViewHolder.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/HomeItemsClickListeners.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/SingleBannerViewHolder.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/StrigaTokenToClaimViewHolder.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenAdapter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenHiddenViewHolder.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenViewHolder.kt, app/src/main/java/org/p2p/wallet/home/ui/main/empty/EmptyViewAdapter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/models/HomeScreenViewState.kt, app/src/main/java/org/p2p/wallet/striga/di/StrigaWalletModule.kt, app/src/main/java/org/p2p/wallet/striga/wallet/interactor/StrigaClaimInteractor.kt, app/src/main/java/org/p2p/wallet/striga/wallet/models/StrigaClaimableToken.kt, app/src/main/java/org/p2p/wallet/striga/wallet/models/StrigaUserWallet.kt, app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt, app/src/main/res/layout/item_token_to_striga_claim.xml, ui-kit/src/main/kotlin/org/p2p/uikit/components/right_side/RightSideCellModel.kt
https://p2pvalidator.atlassian.net/browse/PWN-8907
=> PWN-8907 - Striga. Add claimable tokens to home

app/build.gradle.kts, app/src/main/java/org/p2p/wallet/striga/kyc/sdk/StrigaKycSdkFacade.kt, app/src/main/java/org/p2p/wallet/striga/kyc/sdk/StrigaKycSdkListeners.kt, app/src/main/java/org/p2p/wallet/striga/kyc/sdk/StrigaSdkLogger.kt, app/src/main/java/org/p2p/wallet/striga/kyc/ui/StrigaKycPresenter.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpSecondStepPresenter.kt
- due to implicit permission to Location
=> NO-TICKET - comment KYC SDK

app/build.gradle.kts, app/proguard-rules.pro, app/src/main/java/org/p2p/wallet/auth/interactor/MetadataInteractor.kt, app/src/main/java/org/p2p/wallet/striga/StrigaUserIdProvider.kt, app/src/main/java/org/p2p/wallet/striga/di/StrigaWalletModule.kt, app/src/main/java/org/p2p/wallet/striga/iban/StrigaUserIbanDetailsContract.kt, app/src/main/java/org/p2p/wallet/striga/iban/StrigaUserIbanDetailsFragment.kt, app/src/main/java/org/p2p/wallet/striga/iban/StrigaUserIbanDetailsPresenter.kt, app/src/main/java/org/p2p/wallet/striga/iban/StrigaUserIbanUiMapper.kt, app/src/main/java/org/p2p/wallet/striga/kyc/StrigaKycModule.kt, app/src/main/java/org/p2p/wallet/striga/model/StrigaDataLayerResult.kt, app/src/main/java/org/p2p/wallet/striga/onboarding/StrigaOnboardingPresenter.kt, app/src/main/java/org/p2p/wallet/striga/signup/StrigaSignUpSecondStepContract.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpFirstStepPresenter.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpSecondStepFragment.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpSecondStepPresenter.kt, app/src/main/java/org/p2p/wallet/striga/wallet/interactor/StrigaWalletInteractor.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/StrigaWalletRemoteRepository.kt, app/src/main/res/values/striga_strings.xml, app/src/test/java/org/p2p/wallet/striga/iban/StrigaUserIbanDetailsPresenterTest.kt, app/src/test/java/org/p2p/wallet/utils/TestUtils.kt, app/src/test/java/org/p2p/wallet/utils/TimberTestUtils.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/left_side/LeftSideCellModel.kt
https://p2pvalidator.atlassian.net/browse/PWN-8900
- fetch iban details from remote
=> PWN-8900 - Striga. Claim flow 1

app/src/main/res/raw/striga_occupation_values.json, app/src/test/resources/striga_occupation_values.json
https://p2pvalidator.atlassian.net/browse/PWN-9036
updated occupation list
=> PWN-9036 - striga. update occupation list

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9137
=> PWN-9137 - Fix bug with showing tokens after update app

core/src/main/java/org/p2p/core/model/DefaultBlockParameter.kt, core/src/main/java/org/p2p/core/network/gson/GsonProvider.kt, core/src/main/java/org/p2p/core/network/gson/GsonTypeAdapters.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/alchemy/request/GetBalanceJsonRpc.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/balance/EthereumTokensRemoteRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-9138
=> PWN-9138 - Fix bug with showing claim bundles on home fragment

app/src/main/java/org/p2p/wallet/striga/presetpicker/mapper/StrigaItemCellMapper.kt, app/src/main/java/org/p2p/wallet/striga/signup/ui/StrigaSignUpSecondStepPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9036
- Show emoji before occupation name in input
| Screenshot #1 |
|:-------------:|
| <image width=300 src="https://github.com/p2p-org/key-app-android/assets/130352737/41bccd84-c4c2-47ca-8380-a74e3c2f4570" /> |
=> PWN-9036 - Striga. Occupation emoji appearance

app/src/main/java/org/p2p/wallet/home/model/HomeElementItem.kt, app/src/main/java/org/p2p/wallet/home/model/HomePresenterMapper.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeInteractor.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/HomeItemsClickListeners.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/StrigaTokenToClaimViewHolder.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenAdapter.kt, app/src/main/java/org/p2p/wallet/striga/wallet/interactor/StrigaClaimInteractor.kt, app/src/main/java/org/p2p/wallet/striga/wallet/models/StrigaClaimableToken.kt, app/src/main/java/org/p2p/wallet/striga/wallet/models/StrigaNetworkCurrency.kt, app/src/main/java/org/p2p/wallet/striga/wallet/models/StrigaNetworkType.kt, app/src/main/java/org/p2p/wallet/striga/wallet/models/StrigaUserWalletAccount.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/StrigaUserWalletsMapper.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/StrigaWalletRemoteRepository.kt, app/src/main/res/layout/item_token_to_striga_claim.xml, core/src/main/java/org/p2p/core/utils/AmountExtensions.kt
https://p2pvalidator.atlassian.net/browse/PWN-8895
- Show progress for striga claim button
- Implemented claim tokens itself
- Fixed couple bugs
=> PWN-8895 - Striga. Claim UI implementation

app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/res/layout/fragment_home.xml
https://p2pvalidator.atlassian.net/browse/PWN-9174
PWN-9174 - home screen relayout to fix issue
=> PWN-9174 - home screen relayout to fix issue

app/src/main/java/org/p2p/wallet/auth/interactor/MetadataInteractor.kt
https://p2pvalidator.atlassian.net/browse/PWN-9158
PWN-9158 - hasDeviceShare or same device to check that we can manage device share
=> PWN-9158 - hasDeviceShare or same device to check that we can manage device share

app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
https://p2pvalidator.atlassian.net/browse/PWN-9175
Fixed crash related to absent name qualifier
=> PWN-9175 - onboarding timer error crashfix

app/src/main/res/layout/widget_progress_state.xml, app/src/main/res/values/send_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-8402
- Changed text
=> PWN-8402 - few seconds instead of 5-20

app/src/main/java/org/p2p/wallet/newsend/ui/search/adapter/SearchViewHolder.kt
https://p2pvalidator.atlassian.net/browse/PWN-8246
PWN-8246 - fix center of address showing on search
=> PWN-8246 - fix center of address showing on search

app/src/main/java/org/p2p/wallet/home/model/HomeBannerItem.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeInteractor.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/HomeItemsClickListeners.kt, app/src/main/java/org/p2p/wallet/home/ui/main/adapter/SingleBannerViewHolder.kt, app/src/main/java/org/p2p/wallet/home/ui/main/empty/BigBannerViewHolder.kt, app/src/main/java/org/p2p/wallet/kyc/model/StrigaKycStatusBanner.kt, app/src/main/java/org/p2p/wallet/striga/user/StrigaStorage.kt, app/src/main/java/org/p2p/wallet/striga/user/StrigaStorageContract.kt, app/src/main/java/org/p2p/wallet/striga/user/interactor/StrigaUserInteractor.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserStatusRepository.kt, app/src/main/res/layout/item_big_banner.xml, app/src/main/res/layout/item_home_banner.xml, app/src/test/java/org/p2p/wallet/striga/sms/StrigaSmsInputInteractorTest.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitButton.kt
https://p2pvalidator.atlassian.net/browse/PWN-9166
https://p2pvalidator.atlassian.net/browse/PWN-9109
- Hide striga kyc banners when clicked
- Added click listener to the root view of any banner
=> PWN-9166, PWN-9109 - striga. banners

app/src/main/java/org/p2p/wallet/App.kt
=> NO-TICKET - Crashlytics disabled for debug

app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt, app/src/main/java/org/p2p/wallet/common/ui/BaseFragmentAdapter.kt, app/src/main/java/org/p2p/wallet/common/ui/FragmentPageConfiguration.kt, app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerContract.kt, app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/container/ScreenConfiguration.kt, app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapFragment.kt, app/src/main/java/org/p2p/wallet/solend/ui/aboutearn/SolendAboutEarnFragment.kt, app/src/main/java/org/p2p/wallet/solend/ui/info/SolendInfoBottomSheet.kt, app/src/main/res/layout/fragment_main.xml
https://p2pvalidator.atlassian.net/browse/NO-TICKETka
NO-TICKET - refactor and migrate MainContainerFragment.kt on ViewPager2
=> NO-TICKET - refactor and migrate MainContainerFragment.kt on ViewPager2

app/src/main/java/org/p2p/wallet/auth/AuthModule.kt, app/src/main/java/org/p2p/wallet/auth/interactor/MetadataInteractor.kt, app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApi.kt, app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApiClient.kt, app/src/main/java/org/p2p/wallet/auth/web3authsdk/mapper/Web3AuthClientMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-9190
PWN-9190 - merge merged metadata and upload on server (and torus if tKey is valid)
=> PWN-9190 - merge merged metadata and upload on server (and torus if tKey is valid)

app/src/main/java/org/p2p/wallet/smsinput/SmsInputTimer.kt, app/src/main/java/org/p2p/wallet/striga/signup/interactor/StrigaSignupInteractor.kt, app/src/main/java/org/p2p/wallet/striga/sms/StrigaSmsInputInteractor.kt
https://p2pvalidator.atlassian.net/browse/PWN-8973
- Fixed sms timers
- Upgraded striga sms mocking
=> PWN-8973 - fix sms timers; upgrade striga sms mocking

app/src/main/java/org/p2p/wallet/auth/AuthModule.kt, app/src/main/java/org/p2p/wallet/auth/interactor/AuthLogoutInteractor.kt, app/src/main/java/org/p2p/wallet/striga/user/StrigaStorage.kt, app/src/main/java/org/p2p/wallet/striga/user/StrigaStorageContract.kt, app/src/test/java/org/p2p/wallet/striga/sms/StrigaSmsInputInteractorTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-9201
- Clear striga storage after logout
=> PWN-9201 - striga. clear storage after logout

app/src/main/java/org/p2p/wallet/striga/wallet/repository/impl/StrigaWalletRemoteRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-9205
- Calendar month must be zero based
=> PWN-9205 - striga. fix month for hardcoded date (must be zero based)

app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt, app/src/main/java/org/p2p/wallet/kyc/StrigaFragmentFactory.kt, app/src/main/java/org/p2p/wallet/striga/ui/TopUpWalletBottomSheet.kt, app/src/main/java/org/p2p/wallet/striga/ui/TopUpWalletContract.kt, app/src/main/java/org/p2p/wallet/striga/ui/TopUpWalletPresenter.kt, app/src/main/java/org/p2p/wallet/striga/user/model/StrigaUserDetails.kt, app/src/main/java/org/p2p/wallet/striga/user/model/StrigaUserStatusDestination.kt, app/src/main/java/org/p2p/wallet/striga/user/repository/StrigaUserStatusDestinationMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-9202
- Fixed navigation to kyc pedning when clicked bank transfer
=> PWN-9202 - striga. fixed navigation to pending bottomsheet

app/build.gradle.kts, app/src/main/java/org/p2p/wallet/striga/kyc/sdk/StrigaKycSdkFacade.kt, app/src/main/java/org/p2p/wallet/striga/kyc/sdk/StrigaKycSdkListeners.kt, app/src/main/java/org/p2p/wallet/striga/kyc/sdk/StrigaSdkLogger.kt, app/src/main/java/org/p2p/wallet/striga/kyc/ui/StrigaKycPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9209
- Return sumsub sdk and uncomment code
=> PWN-9209 - striga. return sumsub sdk and uncomment it

app/src/main/res/values/settings_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-9106
PWN-9106 - text fix on screen `nice`
=> PWN-9106 - text fix on screen `nice`

app/src/main/java/org/p2p/wallet/home/HomeModule.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/provider/TokenKeyProvider.kt, app/src/main/java/org/p2p/wallet/updates/subscribe/SolanaAccountUpdateSubscriber.kt, app/src/main/java/org/p2p/wallet/updates/subscribe/SplTokenProgramSubscriber.kt
https://p2pvalidator.atlassian.net/browse/PWN-9239
=> PWN-9239 - Fix bug with subscribing to sockets with empty tokenKey

app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerContract.kt, app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerPresenter.kt, core/src/main/java/org/p2p/core/network/ConnectionManager.kt
https://p2pvalidator.atlassian.net/browse/PWN-8679
Also added ConnectionManager.checkNow() function for instant check the internet status
=> PWN-8679 - remove fullscreen inet error

app/src/main/java/org/p2p/wallet/auth/interactor/MetadataInteractor.kt, app/src/main/java/org/p2p/wallet/home/events/SolanaTokensLoader.kt, app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoPresenter.kt, app/src/main/java/org/p2p/wallet/user/interactor/TokenMetadataInteractor.kt, core/src/main/java/org/p2p/core/network/interceptor/RpcInterceptor.kt
https://p2pvalidator.atlassian.net/browse/PWN-9239
=> PWN-9239 - Fix bug with ETH initializing 

app/src/main/java/org/p2p/wallet/bridge/interactor/EthereumInteractor.kt, app/src/main/java/org/p2p/wallet/home/HomeModule.kt, app/src/main/java/org/p2p/wallet/home/events/EthereumTokensLoader.kt, app/src/main/java/org/p2p/wallet/home/events/SolanaTokensLoader.kt, app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerContract.kt, app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletPresenter.kt, app/src/main/java/org/p2p/wallet/tokenservice/TokenServiceCoordinator.kt, app/src/main/res/layout/fragment_my_crypto.xml, app/src/main/res/layout/layout_home_balance.xml, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumKitRepository.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumRepository.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/token/EthereumTokensInMemoryRepository.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/token/EthereumTokensLocalRepository.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitBottomNavigationView.kt
https://p2pvalidator.atlassian.net/browse/PWN-9153
PWN-9153 - send button implemented + my crypto button badge show when eth tokens not empty
=> PWN-9153 - send button implemented + my crypto button badge show when eth tokens not empty

app/src/main/java/org/p2p/wallet/common/feature_toggles/di/FeatureTogglesModule.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/FeatureToggleProvider.kt
https://p2pvalidator.atlassian.net/browse/PWN-9151
PWN-9151 - FeatureToggleProvider.kt added to use in places where we need more then one FT
=> PWN-9151 - FeatureToggleProvider.kt added to use in places where we need more then one FT

app/src/main/java/org/p2p/wallet/user/interactor/TokenMetadataInteractor.kt, app/src/test/java/org/p2p/wallet/user/interactor/TokenMetadataInteractorTest.kt, core/src/main/java/org/p2p/core/rpc/RpcApi.kt, core/src/main/java/org/p2p/core/token/TokensMetadataInfo.kt, token-service/src/main/java/org/p2p/token/service/repository/metadata/TokenMetadataRemoteRepository.kt, token-service/src/main/java/org/p2p/token/service/repository/metadata/TokenMetadataRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-8987
https://p2pvalidator.atlassian.net/browse/PWN-9277
=> PWN-8987 - PWN-9277 - Metadata last modified fixed

app/src/main/java/org/p2p/wallet/striga/ui/TopUpWalletPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9232
removed loading kyc status by clicking bank transfer when it's already approved
=> PWN-9232 - striga. minimize kyc status loading after approval

app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerContract.kt, app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/main/delegates/striga/onramp/StrigaOnRampCellModel.kt, app/src/main/java/org/p2p/wallet/home/ui/main/delegates/striga/onramp/StrigaOnRampDelegate.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletContract.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/mapper/WalletMapper.kt, app/src/main/res/drawable/ic_deposit.xml, app/src/main/res/layout/fragment_wallet.xml, app/src/main/res/layout/item_token_to_striga_onramp.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/p2p/wallet/home/ui/wallet/WalletPresenterMapperTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-9143
PWN-9143 - make wallet screen according to designs
=> PWN-9143 - make wallet screen according to designs

app/src/main/java/org/p2p/wallet/striga/StrigaUserConstants.kt, app/src/main/java/org/p2p/wallet/striga/onramp/StrigaOnRampModule.kt, app/src/main/java/org/p2p/wallet/striga/user/interactor/StrigaUserInteractor.kt, app/src/main/java/org/p2p/wallet/striga/user/model/StrigaUserDetails.kt, app/src/main/java/org/p2p/wallet/striga/wallet/api/StrigaWalletApi.kt, app/src/main/java/org/p2p/wallet/striga/wallet/api/request/StrigaAccountStatementRequest.kt, app/src/main/java/org/p2p/wallet/striga/wallet/api/response/StrigaAccountStatementResponse.kt, app/src/main/java/org/p2p/wallet/striga/wallet/interactor/StrigaWalletInteractor.kt, app/src/main/java/org/p2p/wallet/striga/wallet/models/StrigaUserBankingDetails.kt, app/src/main/java/org/p2p/wallet/striga/wallet/models/ids/StrigaAccountTransactionId.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/StrigaWalletRepository.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/impl/StrigaWalletCachedRepository.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/impl/StrigaWalletInMemoryRepository.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/impl/StrigaWalletRemoteRepository.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/mapper/StrigaAccountStatementMapper.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/mapper/StrigaWalletMapper.kt, app/src/test/java/org/p2p/wallet/striga/wallet/repository/StrigaWalletRemoteRepositoryTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-9265
- split one big wallet repository into two different repo
- implement api request with all needed info
=> PWN-9265 - Striga. /account/statement

app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletPresenter.kt, core/src/main/java/org/p2p/core/token/TokenExtensions.kt
https://p2pvalidator.atlassian.net/browse/PWN-9143
PWN-9143 - filter tokens on `isTokenVisibleOnWalletScreen`
=> PWN-9143 - filter tokens on `isTokenVisibleOnWalletScreen`

app/src/main/java/org/p2p/wallet/home/ui/topup/TopUpWalletBottomSheet.kt, app/src/main/java/org/p2p/wallet/home/ui/topup/TopUpWalletContract.kt, app/src/main/java/org/p2p/wallet/home/ui/topup/TopUpWalletPresenter.kt, app/src/main/java/org/p2p/wallet/moonpay/interactor/PaymentMethodsInteractor.kt, app/src/main/java/org/p2p/wallet/moonpay/ui/BuyModule.kt, app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyFragment.kt, app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyPresenter.kt, app/src/main/res/drawable/bg_rain_rounded_16.xml, app/src/main/res/layout/fragment_receive_supported_tokens.xml, app/src/main/res/layout/fragment_wallet.xml
https://p2pvalidator.atlassian.net/browse/PWN-9305
PWN-9305 - make changes according to add money logic
=> PWN-9305 - make changes according to `add money` logic

app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletFragment.kt, app/src/main/res/layout/dialog_topup_wallet.xml, app/src/main/res/values/striga_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-9305
PWN-9305 - fixes in topUp bottomsheet
=> PWN-9305 - fixes in topUp bottomsheet

app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletContract.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletPresenter.kt
Enabling withdraw button if striga ff is enabled
=> NO-TICKET - enable wallet withdraw button when striga ff is on

app/src/main/java/org/p2p/wallet/newsend/analytics/NewSendAnalytics.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt, app/src/main/java/org/p2p/wallet/svl/ui/send/SendViaLinkPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8429
PWN-8429 - fix analytics SEND_CLICK_CHANGE_TOKEN_CHOSEN & SEND_CLICK_CHANGE_TOKEN_VALUE added in NewSendAnalytics.kt
fix AnalyticsSendFlow.SELL -> AnalyticsSendFlow.SEND_VIA_LINK in SendViaLinkPresenter.kt
=> PWN-8429 - analytics fixes

app/src/main/java/org/p2p/wallet/bridge/claim/ui/ClaimPresenter.kt, app/src/main/java/org/p2p/wallet/home/events/EthereumTokensLoader.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/EthTokenConverter.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumKitRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-9380
=> PWN-9380 - Fix bug with claiming status for eth tokens

app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletContract.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletPresenter.kt, app/src/main/res/values/main_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-9361
PWN-9361 - change toast text on copy address or username
=> PWN-9361 - change toast text on copy address or username

app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinPresenter.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/EthTokenConverter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9381
=> PWN-9381 - Fix token services request duplicates

app/src/main/java/org/p2p/wallet/home/ui/wallet/mapper/WalletMapper.kt, core/src/main/java/org/p2p/core/utils/AmountExtensions.kt
https://p2pvalidator.atlassian.net/browse/PWN-9389
https://p2pvalidator.atlassian.net/browse/PWN-9388
PWN-9389, PWN-9388 - fix balance formatting
=> PWN-9389, PWN-9388 - fix balance formatting

app/src/main/java/org/p2p/wallet/common/ui/widget/actionbuttons/ActionButtonsView.kt, app/src/main/res/layout/item_home_button.xml
https://p2pvalidator.atlassian.net/browse/PWN-9245
PWN-9245 - my crypto buttons fixed
=> PWN-9245 - my crypto buttons fixed

app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9387
PWN-9387 - fix checking on empty account for send logic
=> PWN-9387 - fix checking on empty account for send logic

app/src/main/java/org/p2p/wallet/home/model/TokenComparator.kt
https://p2pvalidator.atlassian.net/browse/PWN-9385
PWN-9385 - sorting changed -> now we sort by USD amount mostly
=> PWN-9385 - sorting changed -> now we sort by USD amount mostly

app/src/main/java/org/p2p/wallet/striga/offramp/mappers/StrigaOffRampSwapWidgetMapper.kt, app/src/main/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampFragment.kt
https://p2pvalidator.atlassian.net/browse/PWN-9405
fix initial zero overwriting
=> PWN-9405 - Striga. Off-ramp calculator: fix initial zero overwriting

app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletContract.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletPresenter.kt, app/src/main/res/layout/fragment_my_crypto.xml, app/src/main/res/layout/fragment_wallet.xml
https://p2pvalidator.atlassian.net/browse/PWN-9362
PWN-9362 - fix layout to make needed scroll behavior
=> PWN-9362 - fix layout to make needed scroll behavior

app/src/main/java/org/p2p/wallet/bridge/claim/ui/mapper/ClaimUiMapper.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/mapper/BridgeSendUiMapper.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt, app/src/main/java/org/p2p/wallet/transaction/model/NewShowProgress.kt, app/src/main/java/org/p2p/wallet/transaction/progresshandler/TransactionProgressHandler.kt, app/src/main/res/layout/dialog_new_transaction_progress.xml, core/src/main/java/org/p2p/core/model/TitleValue.kt
https://p2pvalidator.atlassian.net/browse/PWN-9275
PWN-9275 - migrate on cell models to show data in progress NewTransactionProgressBottomSheet.kt
=> PWN-9275 - migrate on cell models to show data in progress NewTransactionProgressBottomSheet.kt

app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoPresenter.kt, app/src/main/java/org/p2p/wallet/settings/interactor/SettingsInteractor.kt
https://p2pvalidator.atlassian.net/browse/PWN-9386
PWN-9386 - refresh tokens when show hide toggle changed
=> PWN-9386 - refresh tokens when show hide toggle changed

app/src/main/java/org/p2p/wallet/striga/wallet/api/StrigaWalletApi.kt, app/src/main/java/org/p2p/wallet/striga/wallet/api/request/StrigaInitEurOffRampRequest.kt, app/src/main/java/org/p2p/wallet/striga/wallet/api/response/StrigaInitEurOffRampResponse.kt, app/src/main/java/org/p2p/wallet/striga/wallet/models/StrigaInitEurOffRampDetails.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/StrigaWithdrawalsRepository.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/impl/StrigaWithdrawalsRemoteRepository.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/mapper/StrigaWithdrawalsMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-9402
=> PWN-9402 - Striga. send/initiate/bank/

app/src/main/java/org/p2p/wallet/auth/interactor/AuthInteractor.kt, app/src/main/java/org/p2p/wallet/home/events/AppLoader.kt, app/src/main/java/org/p2p/wallet/home/events/AppLoaderFacade.kt, app/src/main/java/org/p2p/wallet/home/events/HomeEventsModule.kt, app/src/main/java/org/p2p/wallet/home/events/OnboardingMetadataLoader.kt, app/src/main/java/org/p2p/wallet/home/events/PendingClaimBundlesLoader.kt, app/src/main/java/org/p2p/wallet/home/events/SocketSubscribeLoader.kt, app/src/main/java/org/p2p/wallet/home/events/SolanaObservationLoader.kt, app/src/main/java/org/p2p/wallet/home/events/StrigaFeatureLoader.kt, app/src/main/java/org/p2p/wallet/home/events/TokenServiceLoader.kt, app/src/main/java/org/p2p/wallet/splash/SplashPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9232
- Make AppLoader aware dependencies
- Await only for dependant loaders, otherwise it works in non-blocking mode
=> PWN-9232 - app loaders with dependencies

app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/mapper/WalletMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-9426
PWN-9426 - show 6 digits for usdc amount
=> PWN-9426 - show 6 digits for usdc amount

app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletPresenter.kt, app/src/main/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9354
PWN-9354 - remove reaction on `is UserTokensState.Error` not to show duplicated error bottomSheets
=> PWN-9354 - remove reaction on `is UserTokensState.Error` not to show duplicated error bottomSheets

app/src/main/java/org/p2p/wallet/striga/offramp/mappers/StrigaOffRampSwapWidgetMapper.kt, app/src/main/res/layout/fragment_striga_off_ramp.xml
https://p2pvalidator.atlassian.net/browse/PWN-9352
Fixed UI for striga off-ramp calculator
=> PWN-9352 - Striga. Calculator layout fixes

app/src/main/java/org/p2p/wallet/home/ui/topup/TopUpWalletBottomSheet.kt, app/src/main/java/org/p2p/wallet/home/ui/topup/TopUpWalletContract.kt, app/src/main/java/org/p2p/wallet/home/ui/topup/TopUpWalletPresenter.kt, app/src/main/res/values/striga_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-9434
PWN-9434 - Bank transfer fee 0% -> 1%
=> PWN-9434 - Bank transfer fee 0% -> 1%

app/src/main/java/org/p2p/wallet/striga/StrigaFragmentFactory.kt, app/src/main/java/org/p2p/wallet/striga/offramp/withdraw/StrigaWithdrawContract.kt, app/src/main/java/org/p2p/wallet/striga/offramp/withdraw/StrigaWithdrawFragment.kt, app/src/main/java/org/p2p/wallet/striga/offramp/withdraw/StrigaWithdrawFragmentType.kt, app/src/main/java/org/p2p/wallet/striga/offramp/withdraw/StrigaWithdrawPresenter.kt, app/src/main/java/org/p2p/wallet/striga/offramp/withdraw/interactor/StrigaWithdrawInteractor.kt, app/src/main/java/org/p2p/wallet/striga/wallet/interactor/StrigaWalletInteractor.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/StrigaWithdrawalsRepository.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/impl/StrigaWithdrawalsRemoteRepository.kt, app/src/main/res/values/striga_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-9271
=> PWN-9271 - Striga. Show progress on USDC -> Striga transfer

app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/container/mapper/BalanceMapper.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/mapper/WalletMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-9435
https://p2pvalidator.atlassian.net/browse/PWN-9388
PWN-9435 - USD -> USDC fix
PWN-9388 - fix balance formatting
=> PWN-9435, PWN-9388 - fix wallet balance formatting corner cases + bottom balance

app/src/main/java/org/p2p/wallet/home/ui/main/delegates/bridgeclaim/EthClaimTokenDelegate.kt, app/src/main/res/layout/item_token_to_claim.xml
https://p2pvalidator.atlassian.net/browse/PWN-9445
PWN-9445 - show claim like incoming_transfer
=> PWN-9445 - show claim like incoming_transfer

app/src/main/java/org/p2p/wallet/striga/offramp/StrigaOffRampContract.kt, app/src/main/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampFragment.kt, app/src/main/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9267
=> PWN-9267 - Striga. Show kyc pending bottomsheet on off-ramp

app/src/main/java/org/p2p/wallet/striga/offramp/mappers/StrigaOffRampSwapWidgetMapper.kt
https://p2pvalidator.atlassian.net/browse/PWN-9413
=> PWN-9413 - Striga. Don't show zero available balance

app/src/main/java/org/p2p/wallet/striga/offramp/models/StrigaOffRampTokenState.kt, app/src/main/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9404
=> PWN-9404 - Striga. Fix off ramp tokens amount in disabled state

app/src/main/java/org/p2p/wallet/striga/signup/steps/interactor/StrigaSignupInteractor.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/impl/StrigaWalletCachedRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-9232
=> PWN-9232 - Striga. Reduce user info requests when it's possible

app/src/main/java/org/p2p/wallet/svl/ui/linkresult/SendLinkGenerationResultFragment.kt
https://p2pvalidator.atlassian.net/browse/PWN-7910
=> PWN-7910 - Minor fixes with navigating back

app/src/main/java/org/p2p/wallet/home/ui/wallet/handlers/WalletStrigaHandler.kt
=> NO-TICKET - fix striga koin deps

app/src/main/res/layout/item_token_to_claim.xml
https://p2pvalidator.atlassian.net/browse/PWN-9445
PWN-9445 - fix textStyle for title of claim cell
=> PWN-9445 - fix textStyle for title of claim cell

app/src/main/java/org/p2p/wallet/alarmlogger/AlarmErrorsModule.kt, app/src/main/java/org/p2p/wallet/alarmlogger/logger/AlarmErrorsLogger.kt, app/src/main/java/org/p2p/wallet/alarmlogger/model/AlarmBridgeErrorConverter.kt, app/src/main/java/org/p2p/wallet/alarmlogger/model/AlarmDeviceShareChangeErrorConverter.kt, app/src/main/java/org/p2p/wallet/alarmlogger/model/AlarmFeatureConverter.kt, app/src/main/java/org/p2p/wallet/alarmlogger/model/AlarmSendErrorConverter.kt, app/src/main/java/org/p2p/wallet/alarmlogger/model/AlarmStrigaErrorConverter.kt, app/src/main/java/org/p2p/wallet/alarmlogger/model/AlarmSwapErrorConverter.kt, app/src/main/java/org/p2p/wallet/alarmlogger/model/AlarmThrowableFormatter.kt, app/src/main/java/org/p2p/wallet/alarmlogger/model/AlarmWeb3ErrorConverter.kt
- fix sending empty body when formatting throwable class
=> NO-TICKET - Fix sending empty alarms for send

token-service/src/main/java/org/p2p/token/service/api/response/TokenListResponse.kt
=> NO-TICKET - Fix field name for token-service

app/src/main/java/org/p2p/wallet/home/ui/container/mapper/WalletBalanceMapper.kt, app/src/test/java/org/p2p/wallet/home/ui/container/mapper/WalletBalanceMapperTest.kt, core/src/main/java/org/p2p/core/utils/AmountExtensions.kt
https://p2pvalidator.atlassian.net/browse/PWN-9470
PWN-9470 - fix last formatting case + tests
=> PWN-9470 - fix last formatting case + tests

token-service/src/main/java/org/p2p/token/service/repository/configurator/PricePercentDifferenceToShow.kt
https://p2pvalidator.atlassian.net/browse/PWN-9472
=> PWN-9472 -  Percent diff to show fixes

app/src/main/java/org/p2p/wallet/user/repository/UserTokensDatabaseRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-9457
=> PWN-9457 - Fix sol rates

app/src/main/java/org/p2p/wallet/striga/exchange/api/StrigaExchangeApi.kt, app/src/main/java/org/p2p/wallet/striga/onramp/interactor/StrigaOnRampInteractor.kt, app/src/main/java/org/p2p/wallet/striga/sms/signup/StrigaSignupSmsInputPresenter.kt, app/src/main/java/org/p2p/wallet/striga/user/api/StrigaApi.kt, app/src/main/java/org/p2p/wallet/striga/wallet/api/StrigaWalletApi.kt, core/src/main/res/values/environment_config.xml, core/src/release/res/values/environment_config.xml
https://p2pvalidator.atlassian.net/browse/PWN-9293
Fixed striga urls
=> PWN-9293 - striga. api urls fixes

app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerFragment.kt
https://p2pvalidator.atlassian.net/browse/PWN-9172
PWN-9172 - push notification fixes
=> PWN-9172 - push notification fixes

app/src/main/java/org/p2p/wallet/striga/offramp/withdraw/StrigaWithdrawFragment.kt, app/src/main/java/org/p2p/wallet/striga/wallet/repository/impl/StrigaWalletCachedRepository.kt, core/src/main/java/org/p2p/core/common/TextContainer.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/edittext/v2/NewUiKitEditText.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/edittext/v2/NewUiKitEditTextMutator.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/edittext/v2/NewUiKitEditTextStyleAttrsApplier.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/edittext/v2/NewUiKitEditTextTipState.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/edittext/v2/NewUiKitEditTextTipStateRenderer.kt, ui-kit/src/main/kotlin/org/p2p/uikit/components/edittext/v2/NewUiKitEditTextValues.kt, ui-kit/src/main/res/layout/widget_ui_kit_edit_text_new.xml, ui-kit/src/main/res/values/attrs.xml
=> NO-TICKET - Update UiKitEditText with tip renderer

app/src/main/java/org/p2p/wallet/App.kt, app/src/main/java/org/p2p/wallet/auth/interactor/CreateWalletInteractor.kt, app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt, app/src/main/java/org/p2p/wallet/common/analytics/AnalyticsModule.kt, app/src/main/java/org/p2p/wallet/common/analytics/AppPublicKeyObserver.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/provider/SeedPhraseProvider.kt
=> NO-TICKET - Observe pubkey for Sentry

app/src/main/java/org/p2p/wallet/user/interactor/TokenMetadataInteractor.kt, token-service/src/main/java/org/p2p/token/service/repository/metadata/TokenMetadataRemoteRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-9504
PWN-9504 - fixes according to comments
=> PWN-9504 - fixes according to comments

app/src/main/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9404
Don't show double toasts when no internet and rates request is failed
=> PWN-9404 - striga. observe rates only with internet

app/src/main/java/org/p2p/wallet/auth/widget/PhoneNumberInputView.kt, app/src/main/java/org/p2p/wallet/striga/signup/steps/first/StrigaSignUpFirstStepFragment.kt, app/src/main/java/org/p2p/wallet/striga/signup/steps/second/StrigaSignUpSecondStepFragment.kt, app/src/main/res/layout/fragment_striga_sign_up_first_step.xml, app/src/main/res/layout/fragment_striga_sign_up_second_step.xml, app/src/main/res/values/striga_strings.xml, ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitEditText.kt, ui-kit/src/main/res/layout/widget_ui_kit_edittext.xml, ui-kit/src/main/res/values/attrs.xml
https://p2pvalidator.atlassian.net/browse/PWN-9452
Striga signup polishing
=> PWN-9452 - striga. signup form polishing

app/src/main/java/org/p2p/wallet/home/events/AppLoaderFacade.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/handlers/WalletStrigaHandler.kt
https://p2pvalidator.atlassian.net/browse/PWN-9507
Added loading cancellation feature to AppLoaderFacade.
Fixing striga data loading.
=> PWN-9507 - app loaders. added loading cancellation feature

app/src/main/java/org/p2p/wallet/home/ui/topup/TopUpWalletBottomSheet.kt, app/src/main/java/org/p2p/wallet/home/ui/topup/TopUpWalletContract.kt, app/src/main/java/org/p2p/wallet/home/ui/topup/TopUpWalletPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletFragment.kt, app/src/main/java/org/p2p/wallet/striga/StrigaFragmentFactory.kt, app/src/main/java/org/p2p/wallet/striga/offramp/withdraw/StrigaWithdrawContract.kt, app/src/main/java/org/p2p/wallet/striga/offramp/withdraw/StrigaWithdrawFragment.kt, app/src/main/java/org/p2p/wallet/striga/offramp/withdraw/StrigaWithdrawPresenter.kt, app/src/main/java/org/p2p/wallet/striga/signup/onboarding/StrigaOpenAccountFragment.kt, app/src/main/java/org/p2p/wallet/striga/sms/onramp/StrigaOtpConfirmFragment.kt, app/src/main/java/org/p2p/wallet/striga/sms/signup/StrigaSignupSmsInputFragment.kt, app/src/main/res/drawable/ic_cat_checkmark.xml, app/src/main/res/layout/fragment_sms_input.xml, app/src/main/res/layout/fragment_striga_open_account.xml, app/src/main/res/layout/fragment_striga_signup_finish.xml, app/src/main/res/values/onboarding_strings.xml, app/src/main/res/values/striga_strings.xml, ui-kit/src/main/kotlin/org/p2p/uikit/utils/SpanUtils.kt, ui-kit/src/main/res/drawable/ic_hand_wallet.xml
https://p2pvalidator.atlassian.net/browse/PWN-9454 
- changed OTP texts and style
- changed striga signup finish style and texts
- added "striga open account" screen for future flow
=> PWN-9454 - striga. stuff polishing

app/src/main/java/org/p2p/wallet/auth/model/CountryCode.kt, app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsContract.kt, app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsFragment.kt, app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsInteractor.kt, app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsMapper.kt, app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsPresenter.kt, app/src/main/java/org/p2p/wallet/settings/SettingsModule.kt, app/src/main/java/org/p2p/wallet/settings/interactor/SettingsInteractor.kt, app/src/main/java/org/p2p/wallet/settings/mapper/SettingsEntityMapper.kt, app/src/main/java/org/p2p/wallet/settings/mapper/SettingsItemMapper.kt, app/src/main/java/org/p2p/wallet/settings/model/SettingsItemMapper.kt, app/src/main/java/org/p2p/wallet/settings/model/UserCountrySettingsEntity.kt, app/src/main/java/org/p2p/wallet/settings/ui/settings/SettingsContract.kt, app/src/main/java/org/p2p/wallet/settings/ui/settings/SettingsFragment.kt, app/src/main/java/org/p2p/wallet/settings/ui/settings/SettingsPresenter.kt, app/src/main/res/drawable/ic_settings_country.xml, app/src/main/res/values/settings_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-9530
- added country settings row on the Settings screen
- added debug options to reset current user country
- also a bit cleaned up debug view
- changed icon for feature toggles
=> PWN-9530 - settings. add country selection + row

app/src/main/java/org/p2p/wallet/common/ui/widget/actionbuttons/ActionButtonViewHolder.kt, app/src/main/java/org/p2p/wallet/common/ui/widget/actionbuttons/ActionButtonsView.kt, app/src/main/res/values/ids.xml
https://p2pvalidator.atlassian.net/browse/PWN-9544
=> PWN-9544 - Add ids to Action buttons

app/src/main/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9267
=> PWN-9267 - striga. fix button state after submit

app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/HistorySwapBannerViewHolder.kt, app/src/main/res/layout/item_usd_usdt_swap_banner.xml, app/src/main/res/values/bridges_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-9139
PWN-9139 - USDC -> USDCet changed to dynamic values from item model
=> PWN-9139 - USDC -> USDCet changed to dynamic values from item model

app/src/main/java/org/p2p/wallet/history/interactor/mapper/RpcHistoryTransactionConverter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8689
PWN-8689 - fix fees for claim on details
=> PWN-8689 - fix fees for claim on details

app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensMapper.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensPresenter.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/model/ERC20Tokens.kt, ethereumkit/src/main/java/org/p2p/ethereumkit/external/repository/EthereumKitRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-9464
PWN-9464 - remove `Matic` from claim and receive supported tokens
=> PWN-9464 - remove `Matic` from claim and receive supported tokens

app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsContract.kt, app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsFragment.kt, app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsMapper.kt, app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsPresenter.kt, app/src/main/java/org/p2p/wallet/infrastructure/network/provider/TokenKeyProvider.kt, app/src/main/res/values/settings_strings.xml, core/src/main/java/org/p2p/core/network/environment/NetworkServicesUrlProvider.kt, core/src/main/res/values/environment_config.xml, core/src/release/res/values/environment_config.xml
https://p2pvalidator.atlassian.net/browse/PWN-9581
=> PWN-9581 - Token Service Base url

app/src/main/java/org/p2p/wallet/history/analytics/HistoryAnalytics.kt, app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt, core/src/main/java/org/p2p/core/analytics/constants/EventNames.kt
https://p2pvalidator.atlassian.net/browse/PWN-9412
=> PWN-9412 - Amplitude corrections

app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/ReserveUsernamePresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9473
=> PWN-9473 - Username registration fix

app/src/main/java/org/p2p/wallet/home/ui/wallet/handlers/WalletStrigaHandler.kt
https://p2pvalidator.atlassian.net/browse/PWN-9518
clear challengeId after success striga on/off ramp
=> PWN-9518 - striga. clear challengeId after success on/off ramp

app/src/main/java/org/p2p/wallet/bridge/send/BridgeSendModule.kt, app/src/main/java/org/p2p/wallet/bridge/send/interactor/BridgeSendInteractor.kt, app/src/main/java/org/p2p/wallet/home/events/SolanaTokensLoader.kt, app/src/main/java/org/p2p/wallet/home/model/TokenConverter.kt, app/src/main/java/org/p2p/wallet/home/ui/new/NewSelectTokenPresenter.kt, app/src/main/java/org/p2p/wallet/infrastructure/swap/JupiterSwapStorage.kt, app/src/main/java/org/p2p/wallet/jupiter/JupiterModule.kt, app/src/main/java/org/p2p/wallet/jupiter/SwapInitialTokenSelectorFactory.kt, app/src/main/java/org/p2p/wallet/jupiter/interactor/SwapTokensInteractor.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/model/JupiterSwapToken.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/tokens/JupiterSwapTokensRemoteRepository.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateManager.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/token_selector/CommonSwapTokenSelector.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/token_selector/PreinstallTokenASelector.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/token_selector/PreinstallTokensBySymbolSelector.kt, app/src/main/java/org/p2p/wallet/newsend/SendModule.kt, app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt, app/src/main/java/org/p2p/wallet/receive/tokenselect/ReceiveTokensPresenter.kt, app/src/main/java/org/p2p/wallet/sell/interactor/SellInteractor.kt, app/src/main/java/org/p2p/wallet/svl/ui/send/SendViaLinkPresenter.kt, app/src/main/java/org/p2p/wallet/tokenservice/TokenServiceCoordinator.kt, app/src/main/java/org/p2p/wallet/user/interactor/UserTokensInteractor.kt, app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterBaseTest.kt, app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapTestHelpers.kt, core/src/main/java/org/p2p/core/token/Token.kt, core/src/main/java/org/p2p/core/token/TokenExtensions.kt, core/src/main/java/org/p2p/core/token/TokenMetadata.kt, token-service/src/main/java/org/p2p/token/service/repository/configurator/TokenExtensionsConfigurator.kt
https://p2pvalidator.atlassian.net/browse/PWN-9424
PWN-9424 - integrate token service and tokenExtension in all screens and features
=> PWN-9424 - integrate token service and tokenExtension in all screens and features

app/src/main/java/org/p2p/wallet/bridge/interactor/EthereumInteractor.kt
https://p2pvalidator.atlassian.net/browse/PWN-9424
PWN-9424 - build fix coin
=> PWN-9424 - build fix coin

app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoFragment.kt, core/src/main/java/org/p2p/core/token/Token.kt
https://p2pvalidator.atlassian.net/browse/PWN-9475
PWN-9475 - can token be hidden extension usage implementation
=> PWN-9475 - can token be hidden extension usage implementation

app/src/main/java/org/p2p/wallet/deeplinks/AppDeeplinksManager.kt, app/src/main/java/org/p2p/wallet/notification/FcmPushNotificationData.kt
https://p2pvalidator.atlassian.net/browse/PWN-9172
PWN-9172 - push notifications fix parsing + switch tab after
=> PWN-9172 - push notifications fix parsing + switch tab after

app/src/main/java/org/p2p/wallet/history/interactor/mapper/RpcHistoryTransactionConverter.kt, app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetFragment.kt
https://p2pvalidator.atlassian.net/browse/PWN-8689
PWN-8689 - use emptyList to show free state not hide the line
=> PWN-8689 - use emptyList to show free state not hide the line

app/src/main/java/org/p2p/wallet/auth/gateway/repository/model/GatewayOnboardingMetadata.kt, app/src/main/java/org/p2p/wallet/auth/web3authsdk/mapper/Web3AuthClientMapper.kt, app/src/test/java/org/p2p/wallet/auth/web3authsdk/mapper/Web3AuthClientMapperTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-9622
PWN-9622 - StrigaMetadata.userId nullable + fix wrapping json from iOS
=> PWN-9622 - StrigaMetadata.userId nullable + fix wrapping json from iOS

app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletModule.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/WalletPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/interactor/WalletStrigaInteractor.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/model/WalletStrigaOnOffRampTokens.kt, app/src/main/java/org/p2p/wallet/home/ui/wallet/repository/WalletStrigaOnOffRampTokensRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-8904
Fixed double loading striga user wallets at the app startup.
Flow instead of direct requests.
=> PWN-8904 - striga. refactor wallet screen on/off ramp tokens flow

app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt, app/src/main/java/org/p2p/wallet/svl/ui/send/SendViaLinkPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-9643
PWN-9643 - fix rate checking on send screens
=> PWN-9643 - fix rate checking on send screens

app/src/main/java/org/p2p/wallet/common/analytics/interactor/ScreensAnalyticsInteractor.kt, app/src/main/java/org/p2p/wallet/home/analytics/BrowseAnalytics.kt, app/src/main/java/org/p2p/wallet/home/db/TokenDao.kt, app/src/main/java/org/p2p/wallet/home/interactor/MyCryptoInteractor.kt, app/src/main/java/org/p2p/wallet/home/model/TokenConverter.kt, app/src/main/java/org/p2p/wallet/home/ui/crypto/CryptoModule.kt, app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/crypto/handlers/BridgeClaimBundleClickHandler.kt, app/src/main/java/org/p2p/wallet/updates/handler/SolanaAccountUpdateHandler.kt, app/src/main/java/org/p2p/wallet/updates/handler/SplTokenProgramUpdateHandler.kt, app/src/main/java/org/p2p/wallet/user/UserModule.kt, app/src/main/java/org/p2p/wallet/user/interactor/TokenMetadataInteractor.kt, app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt, app/src/main/java/org/p2p/wallet/user/interactor/UserTokensInteractor.kt, app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt, app/src/main/java/org/p2p/wallet/user/repository/UserLocalRepository.kt, app/src/main/java/org/p2p/wallet/user/repository/UserTokensDatabaseRepository.kt, app/src/main/java/org/p2p/wallet/user/repository/UserTokensLocalRepository.kt, core/src/main/java/org/p2p/core/token/TokenExtensions.kt, token-service/src/main/java/org/p2p/token/service/api/mapper/TokenServiceMapper.kt, token-service/src/main/java/org/p2p/token/service/repository/configurator/CalculateInTotalBalanceConfigurator.kt, token-service/src/main/java/org/p2p/token/service/repository/configurator/CanBeHiddenConfigurator.kt, token-service/src/main/java/org/p2p/token/service/repository/configurator/PricePercentDifferenceToShow.kt, token-service/src/main/java/org/p2p/token/service/repository/configurator/RuleOfFractionalPartConfigurator.kt, token-service/src/main/java/org/p2p/token/service/repository/configurator/RuleProcessingTokenConfigurator.kt, token-service/src/main/java/org/p2p/token/service/repository/configurator/SetupTokenCellVisibilityConfigurator.kt, token-service/src/main/java/org/p2p/token/service/repository/configurator/SetupTokenVisibilityConfigurator.kt, token-service/src/main/java/org/p2p/token/service/repository/configurator/TokenConfigurator.kt, token-service/src/main/java/org/p2p/token/service/repository/configurator/TokenExtensionsConfigurator.kt, token-service/src/main/java/org/p2p/token/service/repository/metadata/TokenMetadataRemoteRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-9633
1. We got rid of early token metadata requests: 
```
No user token found for mint So11111111111111111111111111111111111111112
No user token found for mint 8HGyAAB1yoM1ttS7pXjHMa3dukTFGQggnFFH3hJZgzQh
No user token found for mint ATLASXmbPQxBUYbxPsV97usA3fPQYEqzQBUHgiFCUsXx
No user token found for mint 8upjSpvjcdpuzhfR1zriwg5NXkwDruejqNE9WNbPRtyA
No user token found for mint SCYfrGCw8aDiqdgcpdGjV6jp4UVVQLuphxTDLNWu36f
No user token found for mint Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
No user token found for mint MERt85fc5boKw3BW1eYdxonEuJNvXbiMbs6hvheau5K
No user token found for mint MAPS41MDahZ9QdKXhVa4dWB9RuyfV4XqhyAZ8XcYepb
No user token found for mint F6v4wfAdJB8D8p77bMXZgYt8TDKsYxLYxH5AFhUkYx9W
```
2. Removed double check for …
=> PWN-9633 - Various optimizations related to user tokens, metadata and extensions

app/src/main/java/org/p2p/wallet/appsflyer/AppsFlyerService.kt, buildSrc/src/main/java/Dependencies.kt
=> NO-TICKET - Fix appsflyer crashes

app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoContract.kt, app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoPresenter.kt, app/src/main/res/layout/fragment_my_crypto.xml
Made MyCryptoFragment as new home, removed token filters
=> NO-TICKET - get back our tokens and old home

app/src/main/java/org/p2p/wallet/jupiter/repository/model/SwapFailure.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/routes/JupiterSwapRoutesRemoteRepository.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapStateRoutesRefresher.kt
https://linear.app/etherean/issue/ETH-667/[android]-keyapp-swap-oshibka-seti-pri-popytke-svopnut-malenkie-summy
=> ETH-667 - user friendly swap route searching error

app/src/main/java/org/p2p/wallet/home/ui/wallet/mapper/WalletMapper.kt, app/src/main/java/org/p2p/wallet/moonpay/interactor/BuyInteractor.kt, app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyPresenter.kt, app/src/main/java/org/p2p/wallet/striga/exchange/repository/mapper/StrigaExchangeRepositoryMapper.kt, app/src/main/java/org/p2p/wallet/striga/offramp/interactor/polling/StrigaOffRampExchangeRateNotifier.kt, app/src/main/java/org/p2p/wallet/striga/offramp/mappers/StrigaOffRampMapper.kt, app/src/main/java/org/p2p/wallet/striga/offramp/models/StrigaOffRampTokenType.kt, app/src/test/java/org/p2p/wallet/striga/exchange/repository/StrigaExchangeRepositoryTest.kt, app/src/test/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampPresenterBaseTest.kt, core/src/main/java/org/p2p/core/model/CurrencyMode.kt, core/src/main/java/org/p2p/core/token/Token.kt, core/src/main/java/org/p2p/core/utils/Constants.kt
https://linear.app/etherean/issue/ETH-671/[android]-key-app-vne-zavisimosti-ot-vybrannogo-fiata-v-shtorke-vybora
Fixed fiat amount - moonpay api has changed so it doesn't allow to get exchange rate of GBP of 1, changed to 100
=> ETH-671 - fixed fiat amount in buy

app/src/main/java/org/p2p/wallet/home/onofframp/OnOffRampNavigator.kt, app/src/main/java/org/p2p/wallet/settings/mapper/SettingsItemMapper.kt
https://linear.app/etherean/issue/ETH-675/[android][keyapp]-ubrat-vybor-strany-pri-perehode-v-buy
removed country selection but left the code for future use
=> ETH-675 - remove country selection

app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoPresenter.kt, app/src/main/java/org/p2p/wallet/utils/StringExtensions.kt, app/src/main/res/layout/layout_home_toolbar.xml
https://linear.app/etherean/issue/ETH-683/[android][keyapp]-dobavit-otobrazhenie-imeniadresa-na-glavnyj-ekran
=> ETH-683 - return ens and address to home

app/src/main/java/org/p2p/wallet/auth/repository/RestoreUserResultHandler.kt, app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt, app/src/main/res/values/onboarding_strings.xml
https://linear.app/etherean/issue/ETH-728/[android]-[key-app]-ubrat-iz-onbordinga-knopku-support
=> ETH-728 - hide last support buttons

app/src/main/java/org/p2p/wallet/send/ui/NewSendPresenter.kt, core/src/main/java/org/p2p/core/token/Token.kt
https://linear.app/etherean/issue/ETH-670/[android]-key-app-pri-perehode-na-ekran-send-ne-predvybran-usdc
=> ETH-670 - now stablecoins in send are first, then tokens sorted by balance

app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt
https://linear.app/etherean/issue/ETH-692/[android]-key-app-pri-vvode-summy-bolshe-chem-est-na-balanse-na-ekrane
Show swap rate always when it's possible
=> ETH-692 - show swap rate always when possible

app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendFragment.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/BridgeSendPresenter.kt, app/src/main/java/org/p2p/wallet/bridge/send/ui/mapper/BridgeSendUiMapper.kt
https://linear.app/etherean/issue/ETH-727/[android][key-app]-ubrat-ispolzovanie-usd-v-send-pri-otpravke-v
disable usd amount on bridge's send; fees in token instead of usd
=> ETH-727 - disable usd amount on bridge's send; fees in token instead of usd

app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyPresenter.kt
https://linear.app/etherean/issue/ETH-736/[android]-minimalnaya-summa-v-buy-30dollar-vmesto-40
=> ETH-736 - fixed minimal buy amount is 40 in any currency

app/src/main/java/org/p2p/wallet/home/events/HomeEventsModule.kt, app/src/main/java/org/p2p/wallet/rpc/repository/account/RpcAccountRemoteRepository.kt, app/src/main/java/org/p2p/wallet/updates/subscribe/Token2022ProgramSubscriber.kt, solana/src/main/java/org/p2p/solanaj/programs/SystemProgram.kt, solana/src/main/java/org/p2p/solanaj/programs/TokenProgram.java
https://linear.app/etherean/issue/ETH-704/[android][keyapp]-proverit-otobrazhenie-memtokenov-i-token2022-na
display token2022 and listen for websocket updates for it
=> ETH-704 - display token2022 and listen for websocket updates for it

app/src/main/java/org/p2p/wallet/deeplinks/SwapDeeplinkHandler.kt
https://linear.app/etherean/issue/ETH-707/[android]-[keyapp]-razreshit-ispolzovanie-tikera-simvola-strikt
fixed typo in the variable name
=> ETH-707 - fixed swap deeplink parsing

app/src/main/java/org/p2p/wallet/jupiter/interactor/JupiterSwapInteractor.kt, app/src/main/java/org/p2p/wallet/jupiter/interactor/SwapTokensInteractor.kt, app/src/main/java/org/p2p/wallet/jupiter/statemanager/SwapUserTokensChangeHandler.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapContract.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapFragment.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenter.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/mapper/SwapWidgetMapper.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/widget/SwapWidget.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/main/widget/SwapWidgetModel.kt, app/src/main/res/layout/widget_swap.xml, app/src/main/res/menu/menu_jupiter_swap.xml
=> PWN-737 PWN-743 - Swap token icons and share button

app/src/main/java/org/p2p/wallet/common/InAppFeatureFlags.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/di/FeatureTogglesModule.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/ReferralProgramEnabledFeatureToggle.kt, app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsMapper.kt
https://linear.app/etherean/issue/ETH-771/[android]✨-feature-toggle-dlya-vklvykl-funkcionalnosti-ref-programmy
- added feature toggle for referral program (false by default)
- removed striga from debug menu
=> ETH-771 - added referral feature toggle, removed striga from debug menu

app/src/main/java/org/p2p/wallet/jupiter/repository/tokens/JupiterSwapTokensRemoteRepository.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/tokens/db/SwapTokensDao.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/tokens/db/SwapTokensDaoDelegate.kt, buildSrc/src/main/java/AppVersions.kt
=> PWN-849 - Fix swap cache

app/src/main/java/org/p2p/wallet/jupiter/interactor/SwapTokensInteractor.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/model/JupiterSwapToken.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/tokens/JupiterSwapTokensRemoteRepository.kt, app/src/main/java/org/p2p/wallet/jupiter/repository/tokens/db/SwapTokensDao.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/tokens/presenter/SearchSwapTokensMapper.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/tokens/presenter/SwapTokensAMapper.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/tokens/presenter/SwapTokensBMapper.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/tokens/presenter/SwapTokensCommonMapper.kt, app/src/main/java/org/p2p/wallet/jupiter/ui/tokens/presenter/SwapTokensPresenter.kt
=> PWN-832 - add sortings by strict tokens

app/src/main/java/org/p2p/wallet/common/InAppFeatureFlags.kt, app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/inapp/ReferralRewardTxMockFlag.kt, app/src/main/java/org/p2p/wallet/history/api/model/RpcHistoryTransactionInfoResponse.kt, app/src/main/java/org/p2p/wallet/history/api/model/RpcHistoryTypeResponse.kt, app/src/main/java/org/p2p/wallet/history/interactor/mapper/RpcHistoryTransactionConverter.kt, app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryTransaction.kt, app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryTransactionType.kt, app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetFragment.kt, app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsContract.kt, app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsPresenter.kt, app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt, app/src/main/res/layout/dialog_history_transaction_details.xml, app/src/main/res/values/history_strings.xml
https://linear.app/etherean/issue/ETH-781/[android]-🍕referral-reward-v-istorii-tranzakcij
=> ETH-781 - referral in history

app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoFragment.kt, app/src/main/java/org/p2p/wallet/home/ui/crypto/MyCryptoPresenter.kt, app/src/main/java/org/p2p/wallet/home/ui/crypto/mapper/MyCryptoMapper.kt, app/src/main/java/org/p2p/wallet/pnl/interactor/PnlDataObserver.kt, app/src/main/java/org/p2p/wallet/pnl/interactor/PnlDataState.kt, app/src/main/java/org/p2p/wallet/pnl/ui/PnlUiMapper.kt, app/src/main/res/layout/fragment_my_crypto.xml
https://linear.app/etherean/issue/ETH-770/[android]-🥋-banner-s-tochkoj-vhoda-na-referalnuyu-programmu
https://linear.app/etherean/issue/ETH-855/[android]-pri-vhode-novym-polzovatelem-otobrazhaetsya-blok-pnl
besides these tasks, fixed crypto tab scrolling on small devices
=> ETH-855, ETH-770 - fixing empty tokens states for ref banner and pnl
