p2p-org/key-app-android

- app/src/main/java/org/p2p/wallet/home/HomeModule.kt
- app/src/main/java/org/p2p/wallet/home/model/VisibilityState.kt
- app/src/main/java/org/p2p/wallet/home/repository/HomeDatabaseRepository.kt
- app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt
- app/src/main/java/org/p2p/wallet/home/ui/main/HomeElementItemMapper.kt
- app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
- app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
- app/src/main/java/org/p2p/wallet/infrastructure/network/environment/EnvironmentManager.kt
- app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/RpcInterceptor.kt
- app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
https://p2pvalidator.atlassian.net/browse/PWN-305
I tried to split the new "ViewState" changes and some renamings but haven't managed to do it properly. Please forgive me.
So, the main thing here is that now we have presenter's ViewState that caches the main things that Fragment needs. 
- When we launch Fragment the first time - the presenter loads tokens, update local storage and starts polling for tokens. Also, it subscribes to env changes.
- When we leave Fragment (onDestoyView), polling stops, but the presenter still lives with cached values. Env changes subscription lives on.
- When we change env, the presenter calls the `refresh` method and updates ONLY local storage with the new env.
- When we select Fragment next time (onCreateView) - it starts polling for tokens and gets new …
> PWN-3065 - update main screen after environment is changed

- app/src/main/java/org/p2p/wallet/common/ui/widget/ActionButtonsView.kt
https://p2pvalidator.atlassian.net/browse/PWN-3335
`requestLayout()` should not be called while the view hierarchy is currently in a layout pass (`isInLayout`)
> PWN-3335 - Fix improper requestLayout() calls

- app/src/main/java/org/p2p/wallet/restore/ui/keys/adapter/SecretKeyViewHolder.kt
- app/src/main/java/org/p2p/wallet/restore/ui/keys/adapter/SecretPhraseAdapter.kt
https://p2pvalidator.atlassian.net/browse/PWN-3244
set text to null (clear text) after adding new key to SeedPhrase to prevent restoring it in a field after adding new item
> PWN-3244 - Fix security key input field on the "Manually restore a wallet" screen

- .circleci/config.yml
- app/build.gradle
https://p2pvalidator.atlassian.net/browse/PWN-3753
So CI couldn't find AAB to upload because taskNumber returns the string with the '/' that creates new folder instead of using it in the name.
before
`p2p_wallet_106000}_1.6.0_release/`
- `1.6.0.aab`
after
`p2p_wallet_106000}_1.6.0_release-1.6.0.aab`
> PWN-3753 - fix release/develop AAB upload RELEASE

- .circleci/config.yml
- app/build.gradle
https://p2pvalidator.atlassian.net/browse/PWN-3753
So CI couldn't find AAB to upload because taskNumber returns the string with the '/' that creates new folder instead of using it in the name.
before
`p2p_wallet_106000}_1.6.0_release/`
`1.6.0.aab`
after
`p2p_wallet_106000}_1.6.0_release-1.6.0.aab`
> PWN-3753 - Fix API keys filling for develop

- app/src/main/java/org/p2p/wallet/deeplinks/AppDeeplinksManager.kt
- app/src/main/java/org/p2p/wallet/home/MainFragment.kt
https://p2pvalidator.atlassian.net/browse/PWN-3767
PWN-3767 - dismiss last screen if it is bottomSheet as popBackStackImmediate to fragment does not closes bottomSheets
> PWN-3767 - dismiss last screen on deeplink navigation

- app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
- app/src/main/java/org/p2p/wallet/utils/ViewExtensions.kt
https://p2pvalidator.atlassian.net/browse/PWN-3601
Bug was caused by fragments caching and calling `onViewCreated()` on back press. 
SendFragment visibility check was added before opening keyboard.
> PWN-3601 - Fix keyboard appearance on Home screen

- app/src/main/java/org/p2p/wallet/history/model/HistoryTransaction.kt
- app/src/main/java/org/p2p/wallet/home/model/Token.kt
- app/src/main/java/org/p2p/wallet/utils/AmountExtensions.kt
https://p2pvalidator.atlassian.net/browse/PWN-3781
`scaleShort()` could return 0 in case of small number, and `asUsd()` turned it into `<0.01`
Removed `scaleShort()` function calls before `asUsd()`.
> PWN-3781 - Fix zero tokens formatting

- app/src/main/java/org/p2p/wallet/auth/repository/FileRepository.kt
- app/src/main/java/org/p2p/wallet/auth/ui/security/SecurityKeyPresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-3595
Save images with timestamp to make not override latest images of QRCodes
> PWN-3595 - save images with timestamp to make not override latest images of QRCodes

- app/src/main/java/org/p2p/wallet/common/ui/widget/PinView.kt
- app/src/main/res/layout/widget_keyboard.xml
https://p2pvalidator.atlassian.net/browse/PWN-3873
Display the button "X" on the pin-code screen even though nothing is entered
> PWN-3873 - display the button "X" on the pin-code screen even though nothing is entered

- ui-kit/src/main/res/values/styles_buttons.xml
No ticket
Added `android:minHeight` to all UI Kit buttons styles
> NO-TICKET - Add `android:minHeight` to styles_buttons.xml

- app/src/main/java/org/p2p/wallet/App.kt
https://p2pvalidator.atlassian.net/browse/PWN-4567
workManagerFactory inside calls WorkManager.initialize that causes IllegalStateException
reason: WorkManager.initialize should be called ONLY ONCE but called twice when user logouts
> PWN-4567 - fix crash when user logouts due to dependency graph recreation

- app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinFragment.kt
###Jira Ticket
https://p2pvalidator.atlassian.net/browse/PWN-5147
Navigate to `MainFragment` independently from `Snackbar`, instead of calling it in `onDismiss()`
> PWN-5147 - Create Pin crash fix

- app/src/main/java/org/p2p/wallet/home/MainFragment.kt
https://p2pvalidator.atlassian.net/browse/PWN-5712
PWN-5712 - clear onCreateActions after execute them once, also fixes PWN-5720
> PWN-5712, PWN-5720 - clear onCreateActions after execute

- app/src/main/java/org/p2p/wallet/newsend/SendFeeRelayerManager.kt
- app/src/main/java/org/p2p/wallet/newsend/ui/NewSendContract.kt
- app/src/main/java/org/p2p/wallet/newsend/ui/NewSendFragment.kt
- app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
- app/src/main/java/org/p2p/wallet/send/interactor/SendInteractor.kt
- app/src/main/res/layout/fragment_send_new.xml
PWN-6405 - Fee payer change screen showing logic fixed 
PWN-6389 - Disabled token change if send is launched from token details 
NO-TICKET - Added debug info from fee relayer
https://p2pvalidator.atlassian.net/browse/PWN-6412
https://p2pvalidator.atlassian.net/browse/PWN-6405
https://p2pvalidator.atlassian.net/browse/PWN-6389
https://p2pvalidator.atlassian.net/browse/PWN-6437
PWN-6412 - Fraction input fixes
PWN-6405 - Fee payer change screen showing logic fixed
PWN-6389 - Disabled token change if send is launched from token details
PWN-6437 - Token comparator updated. Now we have this priority: USDC -> USDT -> Total lamports. (No SOL priority rn) 
NO-TICKET - Added debug info from fee relayer
NO-TICKET - Moved initial data loading to splash screen and other fixes
Screenshot #1 | …
> PWN-6412 - Fraction input fixes

- core/src/main/java/org/p2p/core/utils/AmountExtensions.kt
https://p2pvalidator.atlassian.net/browse/PWN-7796
Added `setScale(0)` before returning the zero string of BigDecimal. 
`BigDecimal.toString()` behaves differently on various android versions and apparently across different vendors.
> PWN-7796 - fixed scientific notation for zero values

- app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
https://p2pvalidator.atlassian.net/browse/PWN-8245
Reverted the snackbar error that occurs when unable to load token rates.
Originally, it was accidentially removed down there [link](https://github.com/p2p-org/key-app-android/pull/1547/files#diff-7d20ada08a280cc7d4172bc771d6c4a73602cb105ebd010f0f0aba4425fcc229L404)
> PWN-8245 - show rates loading warning in snackbar how it was before

- app/src/main/java/org/p2p/wallet/auth/interactor/MetadataInteractor.kt
~~https://p2pvalidator.atlassian.net/browse/~~
Since EthereumKitRepository.init is only called after the object's construction, the default value should not be initialized during the construction process.
It leads to crash at the app starting process when koin initializes metadata dependencies
> NO-TICKET - fix metadata initializer

- app/src/main/java/org/p2p/wallet/bridge/analytics/SendBridgesAnalytics.kt
- app/src/main/java/org/p2p/wallet/history/analytics/HistoryAnalytics.kt
- app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryFragment.kt
- app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryPresenter.kt
- app/src/main/java/org/p2p/wallet/home/HomeModule.kt
- app/src/main/java/org/p2p/wallet/home/analytics/HomeAnalytics.kt
- app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerContract.kt
- app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerFragment.kt
- app/src/main/java/org/p2p/wallet/home/ui/container/MainContainerPresenter.kt
- app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt
- app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
- app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
- app/src/main/java/org/p2p/wallet/home/ui/main/adapter/SingleBannerViewHolder.kt
- app/src/main/java/org/p2p/wallet/moonpay/analytics/BuyAnalytics.kt
- app/src/main/java/org/p2p/wallet/newsend/analytics/NewSendAnalytics.kt
- app/src/main/java/org/p2p/wallet/receive/analytics/ReceiveAnalytics.kt
- app/src/main/java/org/p2p/wallet/sell/analytics/SellAnalytics.kt
- app/src/main/java/org/p2p/wallet/settings/SettingsModule.kt
- app/src/main/java/org/p2p/wallet/settings/ui/settings/SettingsContract.kt
- app/src/main/java/org/p2p/wallet/settings/ui/settings/SettingsFragment.kt
- app/src/main/java/org/p2p/wallet/settings/ui/settings/SettingsPresenter.kt
- app/src/main/java/org/p2p/wallet/settings/ui/settings/SettingsPresenterAnalytics.kt
- app/src/main/java/org/p2p/wallet/svl/analytics/SendViaLinkAnalytics.kt
- app/src/main/java/org/p2p/wallet/svl/ui/send/SendViaLinkPresenter.kt
- app/src/main/java/org/p2p/wallet/swap/analytics/SwapAnalytics.kt
https://p2pvalidator.atlassian.net/browse/PWN-8614
> PWN-8614 - Add new amplitude events, and modify current

- app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
- app/src/main/java/org/p2p/wallet/auth/gateway/parser/CountryCodeXmlParser.kt
- app/src/main/java/org/p2p/wallet/auth/gateway/repository/mapper/BorshSerializable.kt
- app/src/main/java/org/p2p/wallet/auth/gateway/repository/mapper/GatewayServiceCreateWalletMapper.kt
- app/src/main/java/org/p2p/wallet/auth/gateway/repository/mapper/GatewayServiceUpdateMetadataMapper.kt
- app/src/main/java/org/p2p/wallet/auth/interactor/MetadataChangesLogger.kt
- app/src/main/java/org/p2p/wallet/auth/interactor/MetadataInteractor.kt
- app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthDurationTracker.kt
- app/src/main/java/org/p2p/wallet/debug/pushservice/DebugWeb3Fragment.kt
- app/src/main/java/org/p2p/wallet/infrastructure/network/NetworkModule.kt
- app/src/main/java/org/p2p/wallet/sell/interactor/SellInteractor.kt
- app/src/main/res/layout/fragment_debug_web3.xml
- app/src/main/res/layout/fragment_striga_sign_up_first_step.xml
- ethereumkit/src/main/java/org/p2p/ethereumkit/external/api/EthereumNetworkModule.kt
- you can decipher now `metadata` field on `get_metadata` and `update_metadata` requests
- in Debug build there is inner mechanism that collects all the changes to metadata to understand what's going on: what changed, when, and which fields. helpful to understand what went wrong
> NO-TICKET - Add metadata change logs

- app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt
- app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
- app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
- app/src/main/java/org/p2p/wallet/striga/di/StrigaSignupModule.kt
- app/src/main/java/org/p2p/wallet/striga/finish/StrigaSignupFinishContract.kt
- app/src/main/java/org/p2p/wallet/striga/finish/StrigaSignupFinishFragment.kt
- app/src/main/java/org/p2p/wallet/striga/finish/StrigaSignupFinishPresenter.kt
- app/src/main/java/org/p2p/wallet/striga/ui/StrigaKycPendingBottomSheet.kt
- app/src/main/res/layout/dialog_striga_kyc_pending.xml
- app/src/main/res/values/striga_strings.xml
- app/src/main/res/values/strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-9014
- striga kyc pending bottomsheet
> PWN-9014 - striga. kyc pending bottom sheet

- app/src/main/java/org/p2p/wallet/auth/repository/RestoreFlowDataLocalRepository.kt
- app/src/main/java/org/p2p/wallet/auth/ui/restore_error/RestoreErrorScreenFragment.kt
- app/src/main/java/org/p2p/wallet/settings/ui/devices/DevicesPresenter.kt
- app/src/main/java/org/p2p/wallet/smsinput/updatedevice/UpdateDeviceSmsInputFragment.kt
- app/src/main/java/org/p2p/wallet/smsinput/updatedevice/UpdateDeviceSmsInputPresenter.kt
- app/src/main/res/values/settings_strings.xml
https://p2pvalidator.atlassian.net/browse/PWN-9042
https://p2pvalidator.atlassian.net/browse/PWN-9043
https://p2pvalidator.atlassian.net/browse/PWN-9057
https://p2pvalidator.atlassian.net/browse/PWN-9050
https://p2pvalidator.atlassian.net/browse/PWN-9046
PWN-9042 - set torusKeyTimestamp to 0 if torus key is null (on error cases)
PWN-9043 - text for incorrect account updated
PWN-9057 - errors handling fixed 
PWN-9050 - backStack return fix
PWN-9046 - fix intercom on restore flow
> PWN-9042, PWN-9043, PWN-9057, PWN-9050, PWN-9046 - device share fixes

- app/src/main/java/org/p2p/wallet/striga/wallet/api/StrigaWalletApi.kt
- app/src/main/java/org/p2p/wallet/striga/wallet/api/request/StrigaUserWalletsRequest.kt
- app/src/main/java/org/p2p/wallet/striga/wallet/api/response/StrigaUserWalletAccountResponse.kt
- app/src/main/java/org/p2p/wallet/striga/wallet/api/response/StrigaUserWalletDetailsResponse.kt
- app/src/main/java/org/p2p/wallet/striga/wallet/api/response/StrigaUserWalletsResponse.kt
- app/src/main/java/org/p2p/wallet/striga/wallet/models/StrigaUserWallet.kt
- app/src/main/java/org/p2p/wallet/striga/wallet/models/StrigaUserWalletAccount.kt
- app/src/main/java/org/p2p/wallet/striga/wallet/repository/StrigaUserWalletsMapper.kt
- app/src/main/java/org/p2p/wallet/striga/wallet/repository/StrigaWalletRemoteRepository.kt
- app/src/main/java/org/p2p/wallet/striga/wallet/repository/StrigaWalletRepository.kt
- app/src/test/java/org/p2p/wallet/striga/wallet/repository/StrigaWalletRepositoryEnrichAccountTest.kt
- app/src/test/java/org/p2p/wallet/striga/wallet/repository/StrigaWalletRepositoryGetUserWalletTest.kt
https://p2pvalidator.atlassian.net/browse/PWN-8904
> PWN-8904 - Striga API. get_user_wallets

- app/src/main/java/org/p2p/wallet/auth/ui/animationscreen/AnimationProgressFragment.kt
https://p2pvalidator.atlassian.net/browse/PWN-9117
PWN-9117 - commit -> commitAllowingStateLoss to allow call in a background of app after handling error done
> PWN-9117 - commit -> commitAllowingStateLoss

- app/src/test/java/org/p2p/wallet/auth/gateway/parser/CountryCodeXmlParserTest.kt
- app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterBackPressTest.kt
- app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterExecuteTransactionTest.kt
- app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterInitialStateTest.kt
- app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterPriceImpactTest.kt
- app/src/test/java/org/p2p/wallet/jupiter/ui/main/JupiterSwapPresenterTokenAmountChangeTest.kt
- app/src/test/java/org/p2p/wallet/striga/signup/ui/StrigaSignupFirstStepPresenterTest.kt
- app/src/test/java/org/p2p/wallet/striga/signup/ui/StrigaSignupSecondStepPresenterTest.kt
- app/src/test/java/org/p2p/wallet/striga/signup/validation/PhoneNumberInputValidatorTest.kt
- app/src/test/java/org/p2p/wallet/striga/user/StrigaStorageTest.kt
- app/src/test/java/org/p2p/wallet/utils/TimberTestUtils.kt
after planting timber it was not uprooting so every timber logged in console a lot of stuff
> NO-TICKET - Fix removing redundant logs in Unit tests

- app/src/main/java/org/p2p/wallet/striga/offramp/ui/StrigaOffRampPresenter.kt
- app/src/main/java/org/p2p/wallet/striga/user/storage/StrigaStorage.kt
- app/src/main/java/org/p2p/wallet/striga/wallet/interactor/StrigaWalletInteractor.kt
Don't load striga account statement when app starts, instead it should be loaded on "next" button in striga off-ramp calculator
> NO-TICKET - Striga. Load statement only on calculator

- app/src/main/java/org/p2p/wallet/user/interactor/TokenMetadataInteractor.kt
- token-service/src/main/java/org/p2p/token/service/repository/metadata/TokenMetadataRemoteRepository.kt
https://p2pvalidator.atlassian.net/browse/PWN-9504
PWN-9504 - fix setting metadata from memory if not InitialTokensLoaded
> PWN-9504 - fix setting metadata from memory if not InitialTokensLoaded

- app/src/main/java/org/p2p/wallet/jupiter/ui/main/widget/SwapWidget.kt
https://linear.app/etherean/issue/ETH-650/[android]-key-app-swap-nevozmozhno-vvesti-drobnoe-chislo-pri-bystrom
> ETH-636 - added support for trailing dot in swapwidget when comparing amounts

- app/src/main/java/org/p2p/wallet/common/ui/widget/actionbuttons/ActionButtonViewHolder.kt
- app/src/main/java/org/p2p/wallet/common/ui/widget/actionbuttons/ActionButtonsAdapter.kt
- app/src/main/res/layout/item_home_button.xml
https://linear.app/etherean/issue/ETH-854/[android]-navbar-ne-umeshaetsya-na-ekranah-s-nebolshim-razresheniem
since density of a screen does not change due to dynamic resolution on modern devices, it seems it's just impossible to define different layouts to handle this case
> ETH-854 - adjust action buttons for lowres
