p2p-org/key-app-android

app/src/main/java/com/p2p/wallet/infrastructure/network/ErrorCode.kt
app/src/main/java/com/p2p/wallet/infrastructure/network/NetworkModule.kt
app/src/main/java/com/p2p/wallet/infrastructure/network/ServerError.kt
app/src/main/java/com/p2p/wallet/infrastructure/network/ServerException.kt
app/src/main/java/com/p2p/wallet/infrastructure/network/interceptor/CompareTokenInterceptor.kt
app/src/main/java/com/p2p/wallet/infrastructure/network/interceptor/ServerErrorInterceptor.kt
app/src/main/java/com/p2p/wallet/main/MainModule.kt
app/src/main/java/com/p2p/wallet/main/ui/main/MainPresenter.kt
app/src/main/java/com/p2p/wallet/swap/interactor/SwapInteractor.kt
app/src/main/java/com/p2p/wallet/user/UserModule.kt
app/src/main/java/com/p2p/wallet/user/interactor/UserInteractor.kt
app/src/main/java/com/p2p/wallet/user/repository/UserInMemoryRepository.kt
app/src/main/java/com/p2p/wallet/user/repository/UserLocalRepository.kt
app/src/main/java/com/p2p/wallet/user/repository/UserRepository.kt
app/src/main/java/com/p2p/wallet/utils/NetworkExtensions.kt
app/src/main/res/values/strings.xml

- Added Error interceptor
- Fixed loading data bugs

- Refactored SDK

---

app/build.gradle
app/src/main/java/org/p2p/wallet/main/ui/transaction/TransactionStatusBottomSheet.kt
app/src/main/java/org/p2p/wallet/swap/interactor/SwapSerializationInteractor.kt
app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaSwapInteractor.kt
app/src/main/java/org/p2p/wallet/swap/interactor/serum/SerumSwapInteractor.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
app/src/main/java/org/p2p/wallet/transaction/SendTransactionExecutor.kt
app/src/main/java/org/p2p/wallet/transaction/TransactionSendManager.kt
app/src/main/java/org/p2p/wallet/transaction/model/AppTransaction.kt
app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
app/src/main/java/org/p2p/wallet/utils/DialogExtensions.kt

Closes [P2PW-1118]
Closes [P2PW-1114]

[P2PW-1114] - Send transaction manager fix

---

app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpFragment.kt
app/src/main/java/org/p2p/wallet/common/ui/textwatcher/PrefixTextWatcher.kt
app/src/main/java/org/p2p/wallet/history/ui/history/HistoryFragment.kt
app/src/main/java/org/p2p/wallet/moonpay/ui/BuySolanaFragment.kt
app/src/main/java/org/p2p/wallet/utils/ViewExtensions.kt
app/src/main/res/layout/fragment_settings_network.xml

1. keyboard fix on touch outside screen
2. Apply ',' and '.' in InputField
3. Use validation to enable continue button

[P2PW-1286] buy screen fixes

---

app/src/main/java/org/p2p/wallet/auth/ui/onboarding/OnboardingFragment.kt
app/src/main/res/layout/fragment_onboarding.xml

* fix video sizes to support small devices
* fix black VideoView background when video do not prepared by adding animationVideoViewPlaceHolder above VideoView and hide it onVideoPrepared state

P2PW-1291 video on Onboarding Fixes

---

app/src/main/java/org/p2p/wallet/auth/ui/onboarding/OnboardingFragment.kt
app/src/main/res/layout/fragment_onboarding.xml

* fix video sizes not to be shifted
* fix black VideoView background when video do not started

[P2PW-1291] video fixes on Onboarding screen again

---

.github/CODEOWNERS

После этого изменения, ревьюверы будут добавляться автоматически

[NO-TICKET] - Code owners added

---

app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-3049
Remove *You can also skip this step and reserve a username later* text in Reserve Username in case of opening it from Home

PWN-3049 - Disable skip for ReserveUsernameFragment opened from Home

---

app/src/main/res/layout/fragment_select_token.xml
app/src/main/res/layout/item_token_simple.xml

https://p2pvalidator.atlassian.net/browse/PWN-3108
Fix layout and constraints
Screenshot 1 |
:------------:

PWN-3108 - fix layout item_token_simple.xml

---

app/build.gradle
app/src/main/java/org/p2p/wallet/App.kt
app/src/main/java/org/p2p/wallet/AppModule.kt
app/src/main/java/org/p2p/wallet/common/AppFeatureFlags.kt
app/src/main/java/org/p2p/wallet/debugdrawer/ConfigurationModule.kt
app/src/main/java/org/p2p/wallet/home/HomeModule.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
app/src/main/java/org/p2p/wallet/settings/SettingsModule.kt
app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkContract.kt
app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkFragment.kt
app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkPresenter.kt
app/src/main/res/layout/fragment_settings_network.xml
app/src/main/res/layout/view_debug_drawer_configure_environment.xml

https://p2pvalidator.atlassian.net/browse/PWN-3079
Make an option to hide or show DevNetbut hide it on ProdBuilds

PWN-3079 - hide devNet on builds for prod

---

app/src/main/java/org/p2p/wallet/home/HomeModule.kt
app/src/main/java/org/p2p/wallet/home/MainFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenAdapter.kt
app/src/main/java/org/p2p/wallet/intercom/IntercomService.kt
app/src/main/java/org/p2p/wallet/utils/viewbinding/FragmentViewBindingPropertyDelegate.kt
app/src/main/java/org/p2p/wallet/utils/viewbinding/ViewBindingDelegateExtensions.kt

https://p2pvalidator.atlassian.net/browse/PWN-3081
fix disabled broken state by switching single -> factory

PWN-3081 - Fixed disabled broken state on HomeScreen

---

app/src/main/java/org/p2p/wallet/home/model/VisibilityState.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
app/src/main/java/org/p2p/wallet/user/UserModule.kt
app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt

https://p2pvalidator.atlassian.net/browse/PWN-3172
- Fix hidden tokens click action
- Save hidden tokens visibility state to `SharedPreferences` and restore it on app restart

PWN-3172 - Save and restore hidden tokens visibility state

---

app/src/main/java/org/p2p/wallet/auth/ui/onboarding/OnboardingFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-3144
Fix white screen on back press from `OnboardingFragment`

PWN-3144 - Back press fix in OnboardingFragment

---

app/build.gradle
app/src/main/java/org/p2p/wallet/AppModule.kt
app/src/main/java/org/p2p/wallet/common/analytics/Analytics.kt
app/src/main/java/org/p2p/wallet/common/analytics/TrackersFactory.kt
app/src/main/java/org/p2p/wallet/common/analytics/trackers/AmplitudeTracker.kt

https://p2pvalidator.atlassian.net/browse/PWN-3159
- events with suffix _debug send to Amplitude if feature build

PWN-3159 - Add _debug events in analytics for feature builds

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/p2p/wallet/App.kt
app/src/main/java/org/p2p/wallet/AppModule.kt
app/src/main/java/org/p2p/wallet/common/di/ServiceScope.kt
app/src/main/java/org/p2p/wallet/infrastructure/InfrastructureModule.kt
app/src/main/java/org/p2p/wallet/notification/AppNotificationManager.kt
app/src/main/java/org/p2p/wallet/notification/FcmPushNotificationData.kt
app/src/main/java/org/p2p/wallet/push_notifications/AppFirebaseMessagingService.kt
app/src/main/java/org/p2p/wallet/push_notifications/PushTokenRepository.kt

https://p2pvalidator.atlassian.net/browse/PWN-3111
Get device token ✅ 
Pushes on foreground and background ✅ 
Pushes on `.feature` build ✅

PWN-3111 - FCM integration

---

app/build.gradle
app/src/main/java/org/p2p/wallet/history/ui/history/HistoryFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/SwapDetailsView.kt
app/src/main/res/layout/fragment_history.xml
app/src/main/res/layout/item_history_shimmer.xml

https://p2pvalidator.atlassian.net/browse/PWN-3246
Add shimmer view to history page

PWN-3246 - History shimmer view

---

app/src/main/java/org/p2p/wallet/rpc/interactor/TransactionAddressInteractor.kt
app/src/main/java/org/p2p/wallet/send/interactor/SendInteractor.kt

Jira Ticket
--
https://p2pvalidator.atlassian.net/browse/PWN-3169
Description of Work
--
Disable cache on getting account info from send screen.
Screenshot
--

PWN-3169 - Fix cached user error on send

---

app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
app/src/main/java/org/p2p/wallet/auth/ui/done/AuthDonePresenter.kt
app/src/main/java/org/p2p/wallet/push_notifications/PushNotificationsModule.kt
app/src/main/java/org/p2p/wallet/push_notifications/ineractor/PushNotificationsInteractor.kt

https://p2pvalidator.atlassian.net/browse/PWN-3114
Retry device token send request after a minute in case of ServerException

PWN-3114 - Device token send retry

---

app/src/main/java/org/p2p/wallet/common/ui/widget/TransactionImageView.kt
app/src/main/java/org/p2p/wallet/common/ui/widget/TransactionSwapImageView.kt
app/src/main/java/org/p2p/wallet/history/HistoryModule.kt
app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/TransactionDetailsBottomSheetContract.kt
app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/TransactionDetailsBottomSheetFragment.kt
app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/TransactionDetailsBottomSheetPresenter.kt
app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/TransactionViewHolder.kt
app/src/main/res/layout/dialog_transaction_details.xml
app/src/main/res/layout/widget_transaction_image.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/dimens.xml

https://p2pvalidator.atlassian.net/browse/PWN-3253
Connect TransactionImageView and TransactionSwapImageView to details bottomSheet

PWN-3253 - Connect TransactionImageView and TransactionSwapImageView to details bottomSheet

---

app/src/main/res/layout/dialog_transaction_details.xml

https://p2pvalidator.atlassian.net/browse/3253

PWN-3253 - Fix navigation color

---

app/src/main/java/org/p2p/wallet/auth/interactor/AuthLogoutInteractor.kt
app/src/main/java/org/p2p/wallet/push_notifications/ineractor/PushNotificationsInteractor.kt
app/src/main/java/org/p2p/wallet/settings/ui/settings/SettingsPresenter.kt
app/src/main/res/values/environment_config.xml

https://p2pvalidator.atlassian.net/browse/PWN-3342
Fix user log out by wrapping deleteDeviceToken() request to try / catch and calling it after storage clearing

PWN-3342 Fix user log out

---

app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-3278
CalculateFees before calculateAmount as fees could be null in calculateAmount

PWN-3278 - calculateFees before calculateAmount as fees could be null in calculateAmount

---

app/src/main/java/org/p2p/wallet/history/ui/history/HistoryFragment.kt
app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt
app/src/main/res/drawable/bg_circle_stroke_icon_secondary.xml
app/src/main/res/drawable/ic_history_error_placeholder.xml
app/src/main/res/layout/fragment_history.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-3401
Add error state view for history screen

PWN-3401 - Add error state for history screen

---

app/src/main/java/org/p2p/wallet/history/ui/history/HistoryContract.kt
app/src/main/java/org/p2p/wallet/history/ui/history/HistoryFragment.kt
app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-3403
Add scroll to top on refresh history screen

PWN-3403 - Add scroll to top on refresh

---

app/src/main/java/org/p2p/wallet/common/ui/widget/ProgressButton.kt
app/src/main/java/org/p2p/wallet/restore/BackupModule.kt
app/src/main/java/org/p2p/wallet/restore/ui/keys/SecretKeyFragment.kt
app/src/main/java/org/p2p/wallet/restore/ui/keys/SecretKeyPresenter.kt
app/src/main/java/org/p2p/wallet/utils/ContextExtensions.kt
app/src/main/res/drawable/bg_gray_secondary_stroked.xml
app/src/main/res/layout/dialog_btc_network_info.xml
app/src/main/res/layout/dialog_btc_topup_info.xml
app/src/main/res/layout/fragment_auth_done.xml
app/src/main/res/layout/fragment_create_wallet.xml
app/src/main/res/layout/fragment_derivable_accounts.xml
app/src/main/res/layout/fragment_onboarding.xml
app/src/main/res/layout/fragment_reserve_username.xml
app/src/main/res/layout/fragment_reset_seed_phrase.xml
app/src/main/res/layout/fragment_secret_key.xml
app/src/main/res/layout/fragment_security_key.xml
app/src/main/res/layout/widget_progress_button.xml
app/src/main/res/layout/widget_qr_view.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-3250
- disable button
- make framelayout red when validation fails
- (optional) cleanup SecretKeyFragment according to code style

PWN-3250 - Show error when incorrect seed phrase is entered

---

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-2963
Pass username to Intercom if it's exists. Otherwise pass the publicKey

PWN-2963 - Intercom username fix

---

app/src/main/java/org/p2p/wallet/transaction/ui/ProgressBottomSheet.kt

https://p2pvalidator.atlassian.net/browse/PWN-3219
Fix transaction details link in explorer

PWN-3219 - Fix link to transaction details in progress bottom sheet

---

.github/pull_request_template.md

https://p2pvalidator.atlassian.net/browse/PWN-3448
[ We don't have `Mandatory` in the description. Screenshots are still optional and can be removed if there are no screenshots ]

PWN-3448 - Update PR template description

---

app/src/main/java/org/p2p/wallet/send/model/Target.kt

https://p2pvalidator.atlassian.net/browse/PWN-3472
PWN-3472 - fix validationaon search using value

PWN-3472 - fix validationaon search

---

app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaSwapInteractor.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-3419
https://p2pvalidator.atlassian.net/browse/PWN-3420
PWN-3419 - setFeePayerToken on source if it was changed
PWN-3420 - count fee with getFeesInPayingToken if feePayerToken isNotSOL

PWN-3419 - Swap screen fee counting fixes

---

app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-3475
Added EmptyDataException for one catch above

PWN-3475 - History empty state

---

app/src/main/res/layout/fragment_network_selection.xml

https://p2pvalidator.atlassian.net/browse/PWN-3481
set backgrount to root layout

PWN-3481 - fix fragment_network_selection.xml layout setting background to root layout

---

app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerAccountInteractor.kt
app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerInteractor.kt
app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerSwapInteractor.kt
app/src/main/java/org/p2p/wallet/feerelayer/model/TokenInfo.kt
app/src/main/java/org/p2p/wallet/send/interactor/SendInteractor.kt
app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaSwapInteractor.kt
app/src/main/java/org/p2p/wallet/utils/AmountExtensions.kt

https://p2pvalidator.atlassian.net/browse/PWN-3040
Fee relayer fixes with SOL participation. 
https://github.com/p2p-org/p2p-wallet-android/pull/406 - previous PR is closed

PWN-3040 - Fixed swapping SOL -> SPL or SPL -> SPL with SOL fee payer

---

app/build.gradle
build.gradle
scripts/dependencies.gradle

https://p2pvalidator.atlassian.net/browse/PWN-3511
PWN-3511 - kotlinVersion - 1.6.10 -> 1.6.21, build:gradle - 7.1.2 -> 7.1.3, roomVersion - 2.4.1 -> 2.4.2, org.robolectric:robolectric - 4.5.1 -> 4.6.1

PWN-3511 - Libs version update

---

.circleci/config.yml

https://p2pvalidator.atlassian.net/browse/PWN-3564
CI Triggers for hotfix branches

PWN-3564 - CI triggers for hotfix branches

---

app/src/main/AndroidManifest.xml
app/src/main/res/xml/network_security_config.xml

https://p2pvalidator.atlassian.net/browse/PWN-3578
PWN-3578 - make support of charles and other proxy like apps

PWN-3578 - make support of charles and other proxy like apps

---

app/src/main/java/org/p2p/wallet/transaction/TransactionManager.kt
app/src/main/java/org/p2p/wallet/transaction/ui/ProgressBottomSheet.kt

https://p2pvalidator.atlassian.net/browse/PWN-3220
Fix progress bottom sheet state when user go out from screen and go back

PWN-3220 - Fix progress bottom sheet state

---

app/src/main/java/org/p2p/wallet/feerelayer/api/FeeRelayerInfoRequest.kt
app/src/main/java/org/p2p/wallet/feerelayer/api/RelayTopUpSwapRequest.kt
app/src/main/java/org/p2p/wallet/feerelayer/api/SendTransactionRequest.kt
app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerInteractor.kt
app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerTopUpInteractor.kt
app/src/main/java/org/p2p/wallet/feerelayer/model/FeeRelayerConverter.kt
app/src/main/java/org/p2p/wallet/feerelayer/model/FeeRelayerStatistics.kt
app/src/main/java/org/p2p/wallet/feerelayer/model/RelayAccount.kt
app/src/main/java/org/p2p/wallet/feerelayer/repository/FeeRelayerRemoteRepository.kt
app/src/main/java/org/p2p/wallet/feerelayer/repository/FeeRelayerRepository.kt
app/src/main/java/org/p2p/wallet/send/interactor/SendInteractor.kt
app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaSwapInteractor.kt
app/src/main/java/org/p2p/wallet/utils/Constants.kt
solanaj/src/main/java/org/p2p/solanaj/core/OperationType.kt

https://p2pvalidator.atlassian.net/browse/PWN-3575
Added changes due to analytics and fixed transactions with min required balance for relay account

PWN-3575 - Added info object to all fee relayer transactions and fixed fees for top up

---

app/src/main/java/org/p2p/wallet/auth/analytics/OnboardingAnalytics.kt
app/src/main/java/org/p2p/wallet/auth/ui/verify/VerifySecurityKeyContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/verify/VerifySecurityKeyFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/verify/VerifySecurityKeyPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-3436
- no Wallet_Created event was received lately, so I fixed it

PWN-3436 - fix Wallet_Created event send

---

.circleci/config.yml
app/src/main/java/org/p2p/wallet/send/interactor/SearchInteractor.kt
app/src/main/java/org/p2p/wallet/send/interactor/SendInteractor.kt
app/src/main/java/org/p2p/wallet/send/model/SendFee.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendContract.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
app/src/main/res/layout/fragment_send.xml
app/src/main/res/layout/widget_progress_button.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-3617
Prohibit user from sending less than 0.0009 SOL for empty balance recipient

PWN-3617 - Send screen warning message for recipient with 0 SOL

---

.circleci/config.yml
app/src/main/java/org/p2p/wallet/debugdrawer/CiConfigDrawerModule.kt
app/src/main/java/org/p2p/wallet/debugdrawer/CustomTimberModule.kt
app/src/main/java/org/p2p/wallet/debugdrawer/DebugDrawer.kt
app/src/main/java/org/p2p/wallet/utils/StringExtensions.kt
app/src/main/res/layout/view_debug_drawer_ci_config.xml

NO_TICKET
- add debug info about API keys in debug drawer

NO_TICKET - fix API keys addition from CI

---

scripts/dependencies.gradle

NO-TICKET - Ktlint version bump

---

app/src/main/java/org/p2p/wallet/auth/ui/username/ReserveUsernameContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/username/ReserveUsernameFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/username/ReserveUsernamePresenter.kt
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-3299
Show error state on username longer then 15 characters

PWN-3299 - Add username length validation

---

app/build.gradle
app/src/main/java/org/p2p/wallet/debug/featuretoggles/FeatureTogglesContract.kt
app/src/main/java/org/p2p/wallet/debug/featuretoggles/FeatureTogglesFragment.kt
app/src/main/java/org/p2p/wallet/debug/featuretoggles/FeatureTogglesPresenter.kt
app/src/main/res/layout/fragment_feature_toggles.xml

+ fix group in firebase app distrub
NO_TICKET
-  fix crash when opening feature toggle screen

NO_TICKET - fix crash when opening feature toggle screen

---

app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt
app/src/main/res/layout/fragment_swap_orca.xml

https://p2pvalidator.atlassian.net/browse/PWN-3509
Made source token symbol and arrow clickable the same as image

PWN-3509 - Source token clicks

---

app/src/main/java/org/p2p/wallet/AppModule.kt
app/src/main/java/org/p2p/wallet/common/ResourcesProvider.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseFragment.kt
app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsPresenter.kt
app/src/main/java/org/p2p/wallet/history/HistoryModule.kt
app/src/main/java/org/p2p/wallet/history/ui/details/TransactionDetailsPresenter.kt
app/src/main/java/org/p2p/wallet/home/HomeModule.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-3750
PWN-3750 - migrate from resources.getColor -> context.getColor with ResourcesProvider.kt

PWN-3750 - migrate from resources.getColor -> context.getColor with ResourcesProvider.kt

---

app/src/main/java/org/p2p/wallet/common/ui/textwatcher/AmountFractionTextWatcher.kt
app/src/main/java/org/p2p/wallet/moonpay/ui/BuySolanaContract.kt
app/src/main/java/org/p2p/wallet/moonpay/ui/BuySolanaFragment.kt
app/src/main/java/org/p2p/wallet/moonpay/ui/BuySolanaPresenter.kt
app/src/main/java/org/p2p/wallet/utils/Constants.kt

https://p2pvalidator.atlassian.net/browse/PWN-3286
Do not enable continue button if amount is 0 (ZERO)

PWN-3286 - do not enable continue button if amount is 0 (ZERO)

---

app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt
app/src/main/java/org/p2p/wallet/auth/repository/FileRepository.kt
app/src/main/java/org/p2p/wallet/auth/ui/username/UsernamePresenter.kt
app/src/main/java/org/p2p/wallet/receive/renbtc/ReceiveRenBtcPresenter.kt
app/src/main/java/org/p2p/wallet/receive/solana/ReceiveSolanaPresenter.kt
app/src/main/java/org/p2p/wallet/receive/token/ReceiveTokenPresenter.kt
app/src/main/java/org/p2p/wallet/renbtc/ui/main/RenBTCPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-3779
save in private storage if we need to share only

PWN-3779 - save in private storage if we need to share only

---

app/src/main/java/org/p2p/wallet/home/api/CryptoCompareApi.kt
app/src/main/java/org/p2p/wallet/restore/BackupModule.kt
app/src/main/java/org/p2p/wallet/restore/interactor/SecretKeyInteractor.kt
app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsFragment.kt
app/src/main/java/org/p2p/wallet/user/repository/UserRemoteRepository.kt
app/src/main/java/org/p2p/wallet/user/repository/prices/TokenPricesRemoteRepository.kt
app/src/main/java/org/p2p/wallet/user/repository/prices/impl/TokenPricesCoinGeckoRepository.kt
app/src/main/java/org/p2p/wallet/user/repository/prices/impl/TokenPricesCryptoCompareRepository.kt

https://p2pvalidator.atlassian.net/browse/PWN-3724
Since token rates are requested on `HomeFragment` we don't have it on `DerivableAccountsFragment`. I requested `SOL` price only on `DerivableAccountsFragment` to calculate total USD balances.

PWN-3724 - Fix SOL price on Derivable Accounts

---

app/src/main/java/org/p2p/wallet/home/ui/select/SelectTokenContract.kt
app/src/main/java/org/p2p/wallet/home/ui/select/SelectTokenFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/select/SelectTokenPresenter.kt
app/src/main/res/layout/fragment_select_token.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-3853
show no tokens empty text when no tokens found by checking through search

PWN-3853 - show no tokens text when no tokens found by checking through search

---

app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt
app/src/main/java/org/p2p/wallet/auth/model/LookupResult.kt
app/src/main/java/org/p2p/wallet/auth/repository/UsernameRemoteRepository.kt
app/src/main/java/org/p2p/wallet/auth/repository/UsernameRepository.kt
app/src/main/java/org/p2p/wallet/renbtc/RenBtcModule.kt
app/src/main/java/org/p2p/wallet/renbtc/interactor/BurnBtcInteractor.kt
app/src/main/java/org/p2p/wallet/restore/interactor/SecretKeyInteractor.kt
app/src/main/java/org/p2p/wallet/send/interactor/SearchInteractor.kt
app/src/main/java/org/p2p/wallet/send/model/AddressState.kt
app/src/main/java/org/p2p/wallet/send/model/SearchResult.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
app/src/main/java/org/p2p/wallet/send/ui/search/SearchPresenter.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchViewHolder.kt

https://p2pvalidator.atlassian.net/browse/PWN-3658
Validation corrections

PWN-3658 - Bitcoin address validation states

---

app/src/main/java/org/p2p/wallet/restore/ui/keys/SecretKeyContract.kt
app/src/main/java/org/p2p/wallet/restore/ui/keys/SecretKeyFragment.kt
app/src/main/java/org/p2p/wallet/restore/ui/keys/SecretKeyPresenter.kt
app/src/main/res/layout/fragment_secret_key.xml

https://p2pvalidator.atlassian.net/browse/PWN-3775

PWN-3775 - Fix restore key button state

---

app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-3280

PWN-3280 - Remove 'Caution' word

---

ui-kit/build.gradle
ui-kit/src/main/kotlin/org/p2p/uikit/atoms/UiKitButton.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/DimensionsExtensions.kt
ui-kit/src/main/res/color/text_button_background_color_selector.xml
ui-kit/src/main/res/values/attrs.xml
ui-kit/src/main/res/values/dimens.xml
ui-kit/src/main/res/values/styles_buttons.xml

https://p2pvalidator.atlassian.net/browse/PWN-3686
https://www.figma.com/file/13KdUCrfZ6VPBdfT6sLVbi/Android-UI-Kit?node-id=167%3A2243
UI Kit buttons implementation.
```xml
<style name="UiKit.Atoms.Button" parent="Widget.MaterialComponents.Button.UnelevatedButton" />
<style name="UiKit.Atoms.Button.Large" />
<style name="UiKit.Atoms.Button.Medium" />
<style name="UiKit.Atoms.Button.Small" />
<style name="UiKit.Atoms.Button.Large.Text" />
<style name="UiKit.Atoms.Button.Medium.Text" />
<style name="UiKit.Atoms.Button.Small.Text" />
```
```xml
<org.p2p.uikit.atoms.UiKitButton
android:id="@+id/buttonLarge"
style="@style/UiKit.Atoms.Button.Large"
android:layout_width="wrap_content"
android:layout_height="@dimen/ui_kit_button_large_height"
android:backgroundTint="@color/bg_night" …
```

PWN-3686 - UI Kit Buttons

---

app/src/main/res/layout/fragment_main.xml

NO-TICKET
- remove BottomNavigationView replacement with new UiKitBottomNavigationView

NO-TICKET - develop fix after UiKitBottomNavigationView

---

app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-3783

PWN-3783 - Minor amount parsing fix

---

app/src/main/res/layout/fragment_receive_network_type.xml

https://p2pvalidator.atlassian.net/browse/PWN-3770
Removed Solana image margin by design.

PWN-3770 - Receive network design fix

---

app/src/main/java/org/p2p/wallet/history/interactor/HistoryInteractor.kt
app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-3974
Fix token History by reloading if no transactions

PWN-3974 - fix token History by reloading if no transactions

---

app/src/main/java/org/p2p/wallet/moonpay/api/MoonpayApi.kt
app/src/main/java/org/p2p/wallet/moonpay/api/MoonpayBuyCurrencyResponse.kt

https://p2pvalidator.atlassian.net/browse/PWN-3979
Fix moonpay fee by adding additional params to request

PWN-3979 - fix moonpay fee by adding additional params to request

---

app/src/main/java/org/p2p/wallet/send/model/Target.kt

https://p2pvalidator.atlassian.net/browse/PWN-4042
Timm by dot name and search

PWN-4042 - timm by dot name and search

---

.circleci/config.yml

[NO-TICKET] - Release AAB upload fix

---

.github/actions/setup-sentry/action.yml
.github/workflows/android-feature-workflow.yml
app/build.gradle
buildSrc/src/main/groovy/PropertiesFile.groovy
ui-kit/build.gradle

- enable Sentry on feature upload
- add more logs when working with .properties file

[NO-TICKET] - Turn on Sentry when deploying and add more logs

---

.github/workflows/android-release-workflow.yml

No Jira ticket, update main CI workflow

NO-TICKET - Add release workflow

---

app/src/main/java/org/p2p/wallet/infrastructure/network/environment/NetworkEnvironmentManager.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/RpcInterceptor.kt

https://p2pvalidator.atlassian.net/browse/PWN-4283
- Fix addition of the RPC_POOL api key

PWN-4283 - Fix addition of the RPC_POOL api key

---

ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitButton.kt
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitTip.kt
ui-kit/src/main/res/drawable/ic_tip_arrow.xml
ui-kit/src/main/res/layout/widget_tip_view.xml
ui-kit/src/main/res/values/dimens.xml
ui-kit/src/main/res/values/ids.xml
ui-kit/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-3946
- Added `UiKitTip` utils.
- Tip could be shown under or above the anchor view.
- Arrow position is calculated programmatically to point the center of anchor view.

PWN-3946 - UI Kit Tip

---

ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitTip.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/TextViewExtensions.kt
ui-kit/src/main/res/layout/widget_tip_view.xml

https://p2pvalidator.atlassian.net/browse/PWN-3946
Added `enum TipColors` with `SNOW, NIGHT, LIME` variations and `data class TipConfig` with `tipColor` and `withArrow` settings.

PWN-3946 - UiKitTip colors and arrow visibility

---

ui-kit/src/main/kotlin/org/p2p/uikit/atoms/UiKitBadgeView.kt
ui-kit/src/main/kotlin/org/p2p/uikit/atoms/UiKitEndAmountView.kt
ui-kit/src/main/kotlin/org/p2p/uikit/atoms/UiKitSkeletonRectangle.kt
ui-kit/src/main/kotlin/org/p2p/uikit/atoms/UiKitStartAmountView.kt
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitButton.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/UiKitSectionHeader.kt

No ticket
Fix `use` function imports from `androidx` package

NO-TICKET - Fix `use` imports from androidx package

---

.github/workflows/android-feature-workflow.yml

Update CI, to support PR from feature/* to feature/* branches

NO-TICKET - Add launch CI when PR created on "feature/*" branches

---

app/src/main/java/org/p2p/wallet/infrastructure/network/data/ErrorCode.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/feerelayer/ErrorTypeConverter.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/feerelayer/FeeRelayerErrorMapper.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/feerelayer/FeeRelayerErrorType.kt
app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaSwapInteractor.kt
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-3661
If there is an error with blockhash on transactions - retry this transaction once

PWN-3661 - Blockhash not found issue fix

---

app/build.gradle

NO-TICKET - fix feature builds

---

.github/actions/setup-apikey/action.yml
app/build.gradle
app/proguard-rules.pro
app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt
app/src/main/java/org/p2p/wallet/auth/ui/username/ReserveUsernameFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/verify/VerifySecurityKeyFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/verify/VerifySecurityKeyPresenter.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/DebugHttpLoggingLogger.kt
app/src/main/java/org/p2p/wallet/intercom/IntercomService.kt
app/src/main/java/org/p2p/wallet/restore/BackupModule.kt
app/src/main/java/org/p2p/wallet/restore/interactor/SecretKeyInteractor.kt

https://p2pvalidator.atlassian.net/browse/PWN-4377
- Skip the step of creating a username (old registration flow)

PWN-4377 PWN-4369 - Temporary disable nameservice + fix Intercom button

---

app/src/main/res/layout/fragment_home.xml
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitBottomNavigationView.kt

https://p2pvalidator.atlassian.net/browse/PWN-4483
Fix bottom padding

PWN-4483 - Fix bottom navigation

---

app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/bottomsheet/ActionsBottomSheet.kt
app/src/main/res/layout/dialog_home_actions.xml
app/src/main/res/values/main_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-4398
PWN-4488 - Change text on Actions modal window

PWN-4398 - Bottomsheet fixes

---

app/build.gradle
app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4121
Use sol to pay compensations if no pools found

PWN-4121 - use sol to pay compensations if no pools found

---

app/src/main/java/org/p2p/wallet/home/model/Token.kt
app/src/main/java/org/p2p/wallet/home/ui/main/empty/PopularTokenViewHolder.kt
app/src/main/java/org/p2p/wallet/user/repository/UserRemoteRepository.kt

https://p2pvalidator.atlassian.net/browse/PWN-4494
UsdRateOrZero on every token + show rates for popular tokens

PWN-4494 - show Rates on Popular tokens

---

app/src/main/java/org/p2p/wallet/common/ui/widget/ActionButtonsView.kt
app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryPresenter.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
app/src/main/res/layout/fragment_buy.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_receive.xml
app/src/main/res/layout/fragment_receive_ren_btc.xml
app/src/main/res/layout/fragment_receive_solana.xml
app/src/main/res/layout/fragment_receive_token.xml
app/src/main/res/layout/fragment_ren_btc.xml
app/src/main/res/layout/fragment_send.xml
app/src/main/res/layout/layout_home_balance.xml
app/src/main/res/values/main_strings.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-4523
- show empty home screen on first load

PWN-4523 - show empty home screen on first load

---

app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/view_home_buy_token_banner.xml

https://p2pvalidator.atlassian.net/browse/PWN-4395
- fix text color to rain
- show banner to QA

PWN-4395 - New main. Banner check

---

app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4521
Open `ReserveUsername` or `Settings` depending on username existence

PWN-4521 - Toolbar profile click

---

app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-4524
Fixed tokens random scrolling. `homeRecyclerView.adater` was updated on every tokens fetch even if it says the same.

PWN-4524 - New home random scroll fix

---

app/src/main/res/layout/fragment_home.xml

https://p2pvalidator.atlassian.net/browse/PWN-4381
Build fix for release

PWN-4381 - build fix for release

---

app/src/main/res/layout/view_action_item.xml
app/src/main/res/values/main_strings.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-4546
- some texts were changed

PWN-4546 - Main change text

---

app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4570
Minor fixes

PWN-4570 - Address copy fixed

---

app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsContract.kt
app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsFragment.kt
app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4571

PWN-4571 - Skip username reservation step

---

app/src/main/res/layout/item_big_banner.xml
app/src/main/res/values/main_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-4546
- change texts on new main banners

PWN-4546 - change texts on new main #2

---

app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/WalletFoundFragment.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/GoogleSignInHelper.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpActivity.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpBottomSheet.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpFragment.kt
app/src/main/java/org/p2p/wallet/common/mvp/MvpView.kt
app/src/main/java/org/p2p/wallet/updates/ConnectionStateProvider.kt
app/src/main/java/org/p2p/wallet/utils/ViewExtensions.kt
app/src/main/res/drawable/bg_night_rounded.xml
app/src/main/res/layout/widget_snackbar.xml
app/src/main/res/values/onboarding_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-4267
PWN-4434 - make toast according to designs
PWN-4428 - keep calm if there is no connection

PWN-4267 - onboarding fixes

---

app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingPresenter.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/UserSignUpInteractor.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApi.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApiClient.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthErrorMapper.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthErrorResponse.kt

- fix communication channel with Web3Auth
- error handling

NO-TICKET - fix communication channel with Web3Auth

---

app/src/main/res/layout/fragment_wallet_found.xml
app/src/main/res/menu/menu_question.xml

https://p2pvalidator.atlassian.net/browse/PWN-4420
Fix "wallet found screen" according to designs

PWN-4420 - fix wallet found screen according to designs

---

app/src/main/res/layout/widget_snackbar.xml

https://p2pvalidator.atlassian.net/browse/PWN-4434
PWN-4434 - snackbar text color textIconButtonPrimary -> text_cloud

PWN-4434 - snackbar text color fix

---

app/src/main/java/org/p2p/wallet/auth/web3authsdk/UserSignUpDetailsStorage.kt
app/src/main/java/org/p2p/wallet/common/crypto/keystore/EncoderDecoderMarshmallow.kt
app/src/main/java/org/p2p/wallet/common/crypto/keystore/KeyStoreWrapper.kt
app/src/main/java/org/p2p/wallet/infrastructure/security/SecureStorage.kt

instead of `contains` before, I started to use `getObject` that throws IllegalArgumentException

NO-TICKET - Onboarding fix crash on root fragment

---

app/src/main/assets/index.html
app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApiClient.kt

- update index.html
- add new parameters to Torus
cherry-picked from author: @kabramovp2p

NO-TICKET - fix Web3Auth SDK usage

---

app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/SliderFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/continuestep/ContinueOnboardingFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootFragment.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseFragment.kt
app/src/main/java/org/p2p/wallet/splash/SplashFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-4346
SystemBars changes in code to color status and navigationbar
Screenshot 1 | Screenshot 2
:------------:|:-------------:
[![Screenshot_20220822_160125](https://user-images.githubusercontent.com/99185280/185928769-5296ba20-a73a-4b31-9da5-b4f410180dd0.png)] | [![Screenshot_20220822_160146](https://user-images.githubusercontent.com/99185280/185928799-fa8256f2-30ae-46bc-94e1-b5dacea0e4ac.png)]

PWN-4346 - systemBars changes in code to color status and navigationbar

---

ui-kit/src/main/res/values/white_palette.xml

https://p2pvalidator.atlassian.net/browse/PWN-4452
- change the LIME color in the screens to DDFA2B

PWN-4452 - change the LIME color in the screens to DDFA2B

---

app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4730 
Save last phone number what user make to auth - and do not call api if it is same

PWN-4730 - do not call API on same number

---

app/src/main/java/org/p2p/wallet/home/MainFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeElementItemMapper.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenAdapter.kt
app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenAdapterDiffCallback.kt
app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenButtonViewHolder.kt
app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenHiddenViewHolder.kt
app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenViewHolder.kt
app/src/main/java/org/p2p/wallet/settings/interactor/SettingsInteractor.kt
app/src/main/java/org/p2p/wallet/settings/ui/settings/SettingsPresenter.kt
app/src/main/java/org/p2p/wallet/settings/ui/zerobalances/SettingsZeroBalancesPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4629
Added diff utils for main screen
Now we don't hide hidden tokens, we are not showing them at all

PWN-4629 - Main screen polishing

---

app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
app/src/main/java/org/p2p/wallet/auth/interactor/OnboardingInteractor.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/continuestep/ContinueOnboardingFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/continuestep/ContinueOnboardingPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/found/WalletFoundContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/found/WalletFoundFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/found/WalletFoundPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputPresenter.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseFragment.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpActivity.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpBottomSheet.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpFragment.kt
app/src/main/java/org/p2p/wallet/common/mvp/MvpView.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsFragment.kt
app/src/main/java/org/p2p/wallet/splash/SplashFragment.kt
app/src/main/res/layout/fragment_wallet_found.xml
app/src/main/res/values/onboarding_strings.xml
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitButton.kt
ui-kit/src/main/kotlin/org/p2p/uikit/natives/UiKitSnackbar.kt

https://p2pvalidator.atlassian.net/browse/PWN-4760
https://p2pvalidator.atlassian.net/browse/PWN-4763
https://p2pvalidator.atlassian.net/browse/PWN-4767
PWN-4760 - add style to snackbar to override in each fragment 
PWN-4763 - remove back navigation when flow is create wallet
PWN-4767 - fix icon disappear after setLoading called twice
Screenshot #1 |
:------------:|

PWN-4767 PWN-4763 PWN-4767 - Onboarding fixes

---

solanaj/src/main/java/org/p2p/solanaj/programs/SystemProgram.kt

https://p2pvalidator.atlassian.net/browse/PWN-4816
Critical bug with transaction amount fixed:
https://p2p-validator.slack.com/archives/C0397T19555/p1661664653707059

PWN-4816 - Transaction amount bugfix

---

app/src/main/java/org/p2p/wallet/restore/RestoreModule.kt
app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt
app/src/main/java/org/p2p/wallet/restore/ui/seedphrase/SeedPhraseContract.kt
app/src/main/java/org/p2p/wallet/restore/ui/seedphrase/SeedPhraseFragment.kt
app/src/main/java/org/p2p/wallet/restore/ui/seedphrase/SeedPhrasePresenter.kt
app/src/main/java/org/p2p/wallet/settings/ui/reset/seedphrase/ResetSeedPhraseFragment.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/seedphrase/SeedPhraseWord.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/seedphrase/adapter/SecretPhraseAdapter.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/seedphrase/adapter/SeedPhraseFormatter.kt

- fix navigation on valid seed phrase
- some renaming, removal of old 'key' word

NO-TICKET - fix navigation on valid seed phrase

---

app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4464
Fix navigation to main screen after creating PIN code

PWN-4464 fix bug after pin create

---

app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputFragment.kt
app/src/main/java/org/p2p/wallet/splash/SplashFragment.kt
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-4449
Add toast message, when user click on back button, in CreatePinFragment, also close application if it was clicked twice

PWN-4440 - Add toast on back button pressed

---

app/src/main/java/org/p2p/wallet/auth/model/CountryCode.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/countrypicker/CountryCodePickerAdapter.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/countrypicker/CountryCodePickerPresenter.kt
app/src/main/res/layout/item_country_code.xml

https://p2pvalidator.atlassian.net/browse/PWN-4784

PWN-4784 - Country code reverted back sorting

---

app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/found/WalletFoundFragment.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/UiKitToolbar.kt

https://p2pvalidator.atlassian.net/browse/PWN-4763
Remove back arrow in "Create wallet flow", and fix UIKIT Toolbar margin

PWN-4763 Remove back arrow in "Create wallet flow", and fix UIKIT Toolbar margin

---

app/src/main/java/org/p2p/wallet/common/feature_toggles/di/FeatureTogglesModule.kt
app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/BuyWithTransferFeatureToggle.kt

https://p2pvalidator.atlassian.net/browse/PWN-4722
Buy with bank transfer feature toggle added

PWN-4722 - buy with bank transfer feature toggle added

---

app/src/main/java/org/p2p/wallet/auth/interactor/CreateWalletInteractor.kt
app/src/main/java/org/p2p/wallet/auth/repository/SignUpFlowDataLocalRepository.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputPresenter.kt
app/src/main/res/layout/fragment_onboarding_general_error_timer.xml

https://p2pvalidator.atlassian.net/browse/PWN-4733
Fix Onboarding Error state bugs

PWN-4733 Fix Onboarding Error state bugs

---

app/src/main/java/org/p2p/wallet/settings/ui/network/SelectNetworkViewHolder.kt
app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkBottomSheet.kt
app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkContract.kt
app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkPresenter.kt
app/src/main/res/layout/fragment_settings_network.xml
app/src/main/res/layout/item_select_network.xml

https://p2pvalidator.atlassian.net/browse/feature/PWN-4897

PWN-4897 - Network screen minor changes

---

app/src/main/java/org/p2p/wallet/auth/gateway/parser/CountryCodeHelper.kt
app/src/main/java/org/p2p/wallet/auth/interactor/UserSignUpInteractor.kt
app/src/main/java/org/p2p/wallet/auth/repository/CountryCodeInMemoryRepository.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinPresenter.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApi.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApiClient.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/mapper/Web3AuthClientMapper.kt

- convert Web3Auth JS callbacks to coroutines

NO-TICKET - convert Web3Auth JS callbacks to coroutines

---

app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkBottomSheet.kt
app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkContract.kt
app/src/main/java/org/p2p/wallet/settings/ui/network/SettingsNetworkPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4897
minor changes

PWN-4897 - Changed the selection behavior

---

app/src/main/java/org/p2p/wallet/settings/ui/newreset/pin/NewResetPinFragment.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/pin/UiKitPinCodeView.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/pin/UiKitPinView.kt

https://p2pvalidator.atlassian.net/browse/PWN-4942

PWN-4942 - Minor pin code view fixes

---

app/src/main/java/org/p2p/wallet/settings/ui/newreset/pin/NewResetPinPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4942

PWN-4942 - Minor pin view fix

---

app/src/main/java/org/p2p/wallet/auth/gateway/api/request/ConfirmRegisterWalletRequest.kt
app/src/main/java/org/p2p/wallet/auth/gateway/repository/GatewayServiceCreateWalletMapper.kt

https://p2pvalidator.atlassian.net/browse/PWN-4958
Fix bug on confirm_create_wallet request

PWN-4958 Fix bug on OTP request

---

app/src/main/java/org/p2p/wallet/auth/interactor/CreateWalletInteractor.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/timer/OnboardingGeneralErrorTimerContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/timer/OnboardingGeneralErrorTimerFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/timer/OnboardingGeneralErrorTimerPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4774
Fix error state onboarding bugs

PWN-4774 - Fix error state bugs

---

app/src/main/res/values/buy_strings.xml

https://p2pvalidator.atlassian.net/browse/NO-TICKET
Change card payment period string to `Instant`

NO-TICEKT - Card payment  period string fix

---

app/src/main/res/menu/menu_onboarding_help.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-4877
Removed onboarding help menu title

PWN-4877 - Remove onboarding help menu title

---

app/src/main/java/org/p2p/wallet/auth/ui/pin/signin/SignInPinContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/signin/SignInPinFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/signin/SignInPinPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/username/ReserveUsernameFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/verify/VerifySecurityKeyFragment.kt
app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsFragment.kt
app/src/main/res/layout/fragment_sign_in_pin.xml
app/src/main/res/values/onboarding_strings.xml
app/src/main/res/values/strings.xml
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/pin/UiKitNumberKeyboardView.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/pin/UiKitPinView.kt
ui-kit/src/main/res/drawable/ic_new_fingerprint.xml
ui-kit/src/main/res/layout/widget_ui_kit_keyboard.xml

https://p2pvalidator.atlassian.net/browse/PWN-5065
Use new sign in UI + logic + connect all new screens

PWN-5065 - use new sign in UI and logic

---

app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/found/WalletFoundFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputFragment.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/GoogleSignInHelper.kt
app/src/main/res/values/onboarding_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-4786
- add mock for testing
- add error snackbar special for Google API error

PWN-4786 - Google dialog error snackbar

---

app/src/main/java/org/p2p/wallet/auth/web3authsdk/GoogleSignInHelper.kt

https://p2pvalidator.atlassian.net/browse/PWN-4786
- remove throw expression that was used for testing the tast

PWN-4786 - remove Google throw error for testing

---

app/src/main/res/values/onboarding_strings.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-5002 

PWN-5002 - Onboarding text updates

---

app/src/main/res/layout/item_country_code.xml

https://p2pvalidator.atlassian.net/browse/PWN-4806

PWN-4806  - Country name minor fix

---

app/src/main/java/org/p2p/wallet/auth/ui/pin/biometrics/BiometricsFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/signin/SignInPinFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-4346
Fixed incorrect status and navigation bar colors in Onboarding

PWN-4346 - Status bar color

---

app/src/main/java/org/p2p/wallet/auth/interactor/restore/SocialShareRestoreInteractor.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestorePresenter.kt
app/src/main/res/layout/fragment_common_restore.xml
app/src/main/res/values/onboarding_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-4857
Show No Wallet Found if shares does not matches

PWN-4857 - show No Wallet Found if shares does not matches

---

app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
app/src/main/java/org/p2p/wallet/auth/interactor/FileInteractor.kt
app/src/main/java/org/p2p/wallet/auth/repository/FileRepository.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/timer/OnboardingGeneralErrorTimerContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/timer/OnboardingGeneralErrorTimerFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/timer/OnboardingGeneralErrorTimerPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingPresenter.kt
app/src/main/java/org/p2p/wallet/utils/FragmentExtensions.kt
app/src/main/java/org/p2p/wallet/utils/SpanUtils.kt
app/src/main/res/layout/fragment_new_onboarding.xml
app/src/main/res/layout/fragment_onboarding_general_error.xml
app/src/main/res/layout/fragment_onboarding_general_error_timer.xml
app/src/main/res/values/onboarding_strings.xml
ui-kit/src/main/res/values/white_palette.xml

https://p2pvalidator.atlassian.net/browse/PWN-5099
Open *Terms of Use* and *Privacy Policy* files in onboarding

PWN-5099 - Terms and Policy

---

app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
app/src/main/java/org/p2p/wallet/auth/interactor/AuthInteractor.kt
app/src/main/java/org/p2p/wallet/auth/repository/UserSignUpDetailsStorage.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestorePresenter.kt
app/src/main/java/org/p2p/wallet/infrastructure/account/AccountStorage.kt
app/src/main/java/org/p2p/wallet/infrastructure/account/AccountStorageContract.kt

https://p2pvalidator.atlassian.net/browse/PWN-5120
Show restore when needed on logout except of start screen

PWN-5120 - show restore when needed on logout except of start screen

---

app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterFragment.kt
app/src/main/java/org/p2p/wallet/auth/widget/PhoneNumberInputView.kt
app/src/main/res/layout/widget_phone_input_view.xml

https://p2pvalidator.atlassian.net/browse/PNW-5064
https://p2pvalidator.atlassian.net/browse/PWN-4918
Remove phone number mask form number enter field

PWN-5064 - Remove phone number mask

---

app/src/main/res/raw/ccp_english.xml

https://p2pvalidator.atlassian.net/browse/PWN-4806
Fix country code names

PWN-4806-Fix country code names

---

app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/signin/SignInPinFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-4346
Fix nav bar color on pin create and on sign in 

PWN-4346 - Fix nav bar color

---

app/src/main/java/org/p2p/wallet/restore/ui/seedphrase/SeedPhraseFragment.kt
app/src/main/java/org/p2p/wallet/restore/ui/seedphrase/SeedPhrasePresenter.kt
app/src/main/java/org/p2p/wallet/settings/ui/reset/seedphrase/ResetSeedPhraseFragment.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/seedphrase/UiKitSeedPhraseView.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/seedphrase/adapter/SeedPhraseAdapter.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/seedphrase/adapter/SeedPhraseWordViewHolder.kt
ui-kit/src/main/res/layout/item_secret_key.xml
ui-kit/src/main/res/layout/widget_seed_phrase_view.xml

https://p2pvalidator.atlassian.net/browse/PWN-5148
- Last secret is now changeable and focusable
- Crash fixed

PWN-5148 - Seed phrase fixes

---

app/src/main/java/org/p2p/wallet/auth/interactor/AuthLogoutInteractor.kt
app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputPresenter.kt
app/src/main/java/org/p2p/wallet/debug/torus/DebugTorusFragment.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/provider/TokenKeyProvider.kt
app/src/main/java/org/p2p/wallet/push_notifications/ineractor/PushNotificationsInteractor.kt
app/src/main/java/org/p2p/wallet/rpc/repository/account/RpcAccountRemoteRepository.kt

- add more logging
- fix restore flow for device + custom share

PWN-5171 - Restore flow fix and add more logging

---

app/src/main/java/org/p2p/wallet/auth/interactor/CreateWalletInteractor.kt
app/src/main/java/org/p2p/wallet/auth/interactor/restore/CustomShareRestoreInteractor.kt
app/src/main/java/org/p2p/wallet/auth/interactor/restore/RestoreWalletInteractor.kt
app/src/main/java/org/p2p/wallet/auth/repository/RestoreFlowDataLocalRepository.kt
app/src/main/java/org/p2p/wallet/auth/repository/SignUpFlowDataLocalRepository.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-5121
Fix bug with sending requset on create and restore wallet

PWN-5121 - Fix phone number send error, on create and restore wallet

---

app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputPresenter.kt

- show debug menu on long tap on button "Seed phrase"

NO-TICKET - add debug menu on restore, remove debug sms code

---

app/src/main/java/org/p2p/wallet/auth/ui/pin/signin/SignInPinContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/signin/SignInPinFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/signin/SignInPinPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-5173
PWN-5173 - do not show progress on pin-code sign in

PWN-5173 - do not show progress on pin-code sign in

---

app/src/main/java/org/p2p/wallet/moonpay/interactor/MoonpayBuyInteractor.kt
app/src/main/java/org/p2p/wallet/moonpay/model/BuyDetailsState.kt
app/src/main/java/org/p2p/wallet/moonpay/model/MoonpayBuyResult.kt
app/src/main/java/org/p2p/wallet/moonpay/ui/BuySolanaPresenter.kt
app/src/main/java/org/p2p/wallet/moonpay/ui/bottomsheet/BuyDetailsBottomSheet.kt
app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyPresenter.kt
app/src/main/res/layout/dialog_buy_details_part.xml
app/src/main/res/values/buy_strings.xml
app/src/main/res/values/strings.xml
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitAmountsView.kt

https://p2pvalidator.atlassian.net/browse/PWN-4992
- Handle max amount error
- Show max amount error state in `BuyDetailsBottomSheet`
- Fix error with formatted value change in token / currency amount fields

PWN-4992 - Max amount error

---

app/src/main/java/org/p2p/wallet/auth/ui/phone/countrypicker/CountryCodePickerPresenter.kt
app/src/main/res/raw/ccp_english.xml

https://p2pvalidator.atlassian.net/browse/PWN-4811
https://p2pvalidator.atlassian.net/browse/PWN-5184
Fix country codes in file, fix search by text

PWN-4811 - Fix country codes

---

app/src/main/java/org/p2p/wallet/auth/interactor/CreateWalletInteractor.kt
app/src/main/java/org/p2p/wallet/auth/interactor/restore/CustomShareRestoreInteractor.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4875
Add error handling on enter phone number

PWN-4875 - Add error handling on enter phone number

---

app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/timer/OnboardingGeneralErrorTimerFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/continuestep/ContinueOnboardingFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-5120
PWN-5120 - go to OnboardingRootFragment except of NewOnboardingFragment to make same common logic

PWN-5120 - fix starting screen

---

app/src/main/java/org/p2p/wallet/restore/ui/keys/adapter/SecretKeyViewHolder.kt
app/src/main/java/org/p2p/wallet/restore/ui/keys/adapter/SecretPhraseAdapter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4391 
Don't forget to apply in new onboarding as well

PWN-4391 - Fixed crash in seed phrase

---

app/src/main/res/layout/fragment_splash.xml
app/src/main/res/values/onboarding_strings.xml
app/src/main/res/values/settings_strings.xml
app/src/main/res/values/theme.xml

https://p2pvalidator.atlassian.net/browse/PWN-5100

PWN-5100 - Hiding Key app brand until release

---

app/src/main/java/org/p2p/wallet/auth/interactor/restore/CustomShareRestoreInteractor.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputPresenter.kt
app/src/main/res/layout/fragment_new_sms_input.xml
app/src/main/res/layout/fragment_phone_number_enter.xml
app/src/main/res/values/onboarding_strings.xml
app/src/main/res/values/strings.xml
ui-kit/src/main/res/drawable/background_input_stroke_oval_error.xml
ui-kit/src/main/res/layout/component_large_input_four_digits.xml

https://p2pvalidator.atlassian.net/browse/PWN-4862
The OTP code input screen does not meet the requirements - fixes

PWN-4862 - The OTP code input screen does not meet the requirements

---

app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
app/src/main/res/layout/fragment_onboarding_general_error.xml

https://p2pvalidator.atlassian.net/browse/PWN-5192
Remove terms from error screen

PWN-5192 - remove terms from error screen

---

app/src/main/java/org/p2p/wallet/auth/repository/UserSignUpDetailsStorage.kt
app/src/main/java/org/p2p/wallet/debug/torus/DebugTorusFragment.kt
app/src/main/res/layout/fragment_debug_torus.xml

https://p2pvalidator.atlassian.net/browse/PWN-5209
Show device share and have an ability to remove it from Debug settings

PWN-5209 - ability to delete device share from debug meny

---

app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-5193
Add logic on OnboardingGeneralErrorPresenter.kt same that we have on CommonRestore

PWN-5193 - Add google logic on OnboardingGeneralErrorPresenter

---

app/src/main/java/org/p2p/wallet/auth/gateway/api/request/ConfirmRegisterWalletRequest.kt
app/src/main/java/org/p2p/wallet/auth/gateway/repository/GatewayServiceCreateWalletMapper.kt

https://p2pvalidator.atlassian.net/browse/PWN-5213
- temporary mock new back-end field

PWN-5213 - pass empty metadata

---

app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/continuestep/ContinueOnboardingFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
app/src/main/res/layout/fragment_common_restore.xml
app/src/main/res/layout/fragment_onboarding_general_error.xml
app/src/main/res/values/onboarding_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-5190
* Ellipsize="middle" for showing emails
* ContinueOnboardingFragment.kt navigate to NewOnboardingFragment except of OnboardingRootFragment

PWN-5190 - emails fix to fit 1 line

---

app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
app/src/main/res/layout/fragment_common_restore.xml
app/src/main/res/values/onboarding_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-5182
Set starting screen button except of seed restore button

PWN-5182 - set starting screen except of seed restore

---

app/src/main/java/org/p2p/wallet/auth/gateway/repository/GatewayServiceCreateWalletMapper.kt

https://p2pvalidator.atlassian.net/browse/PWN-5213
- add a signature field

PWN-5213 - mock new gateway field

---

app/src/main/java/org/p2p/wallet/auth/interactor/restore/RestoreWalletInteractor.kt
app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt
app/src/main/java/org/p2p/wallet/auth/model/PhoneNumber.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/GeneralErrorScreenError.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt
app/src/main/res/layout/fragment_onboarding_general_error.xml
app/src/main/res/values/onboarding_strings.xml

…phone number not exists
https://p2pvalidator.atlassian.net/browse/PWN-5181
Refactor general error scree, and error new error state

PWN-5181 - Add phone not found error state

---

app/src/main/java/org/p2p/wallet/auth/interactor/CreateWalletInteractor.kt
app/src/main/java/org/p2p/wallet/auth/interactor/restore/RestoreWalletInteractor.kt
app/src/main/java/org/p2p/wallet/auth/repository/RestoreFlowDataLocalRepository.kt
app/src/main/java/org/p2p/wallet/auth/repository/SignUpFlowDataLocalRepository.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-5214
Add reset for max enter phone number tries counter

PWN-5214 - Add reset for max enter phone number tries counter

---

app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/signin/SignInPinFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-4346
Fix pin screens  nav bar color

PWN-4346 - Fix pin screens  nav bar color

---

app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-5120
PWN-5120 - fix going to root not starting

PWN-5120 - fix going to root not starting

---

app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-5234
PWN-5234 - restore default county code if it was selected

PWN-5234 - restore default county code if it was selected

---

app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4991
Select **Card** payment method if user from UK choses different from *GBP* currency

PWN-4991 - Fix currency auto selection

---

ui-kit/src/main/kotlin/org/p2p/uikit/organisms/seedphrase/UiKitSeedPhraseView.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/seedphrase/adapter/SeedPhraseWordViewHolder.kt

https://p2pvalidator.atlassian.net/browse/PWN-5148

PWN-5148 - Keyboard fixes

---

app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
app/src/main/java/org/p2p/wallet/auth/gateway/api/response/GatewayServiceErrorDataResponse.kt
app/src/main/java/org/p2p/wallet/auth/gateway/api/response/GatewayServiceResponse.kt
app/src/main/java/org/p2p/wallet/auth/gateway/repository/GatewayServiceError.kt
app/src/main/java/org/p2p/wallet/auth/gateway/repository/GatewayServiceErrorMapper.kt
app/src/main/java/org/p2p/wallet/auth/interactor/restore/RestoreWalletInteractor.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/timer/GeneralErrorTimerScreenError.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/timer/OnboardingGeneralErrorTimerFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/timer/OnboardingGeneralErrorTimerPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputPresenter.kt
app/src/main/res/values/strings.xml
app/src/test/java/org/p2p/wallet/swap/koin/CheckModulesTest.kt

https://p2pvalidator.atlassian.net/browse/PWN-4791
https://p2pvalidator.atlassian.net/browse/PWN-5181

PWN-4791 - Add logic for fetching left time to unfreeze

---

app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApiClient.kt

https://p2pvalidator.atlassian.net/browse/PWN-5258

PWN-5258 - generate mnemonics on client and pass it to Web3Auth

---

app/src/main/java/org/p2p/wallet/auth/ui/generalerror/GeneralErrorScreenError.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterPresenter.kt
app/src/main/res/layout/fragment_onboarding_general_error.xml
app/src/main/res/values/onboarding_strings.xml

Fix onboarding error screen bugs

NO-TICKET - Fix onboarding error screen bugs

---

app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
app/src/main/res/values/onboarding_strings.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-5002

PWN-5002 - Text updates

---

app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-5195
Fix navigation

PWN-5195 - Fix navigation on General error screen

---

app/src/main/assets/index.html

https://p2pvalidator.atlassian.net/browse/PWN-3713
PWN-3713 - index update

PWN-3713 - Web3Auth 1.1.10 -> 1.1.12

---

app/src/main/assets/index.html
app/src/main/java/org/p2p/wallet/auth/repository/RestoreFlowDataLocalRepository.kt
app/src/main/java/org/p2p/wallet/auth/repository/SignUpFlowDataLocalRepository.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApiClient.kt
app/src/main/java/org/p2p/wallet/debug/torus/DebugTorusFragment.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/environment/NetworkServicesUrlProvider.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/environment/TorusEnvironment.kt
app/src/main/res/layout/fragment_debug_torus.xml

https://p2pvalidator.atlassian.net/browse/PWN-3713
PWN-3713 - add subVerifier and changes to support 1.2.0 Web3Auth

PWN-3713 - add subVerifier and changes to support 1.2.0 Web3Auth

---

app/src/main/java/org/p2p/wallet/auth/repository/UserSignUpDetailsStorage.kt
app/src/main/java/org/p2p/wallet/debug/torus/DebugTorusFragment.kt
app/src/main/java/org/p2p/wallet/infrastructure/account/AccountStorage.kt
app/src/main/java/org/p2p/wallet/infrastructure/account/AccountStorageContract.kt

https://p2pvalidator.atlassian.net/browse/PWN-5306
Remove all shares on remove device share button debug menu

PWN-5306 - remove all shares on remove device share button debug menu

---

app/build.gradle
app/src/main/java/P2pSdk.kt
app/src/main/java/org/p2p/wallet/App.kt

https://p2pvalidator.atlassian.net/browse/PWN-5301
- .so files and JNI interface

PWN-5301 - SolendSDK: so files and JNI interface

---

app/src/main/java/org/p2p/wallet/common/analytics/Analytics.kt
app/src/main/java/org/p2p/wallet/common/analytics/trackers/AmplitudeTracker.kt
app/src/main/java/org/p2p/wallet/common/analytics/trackers/AnalyticsTracker.kt
app/src/main/java/org/p2p/wallet/common/analytics/trackers/TimberTracker.kt
app/src/main/java/org/p2p/wallet/home/analytics/HomeAnalytics.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-4817

PWN-4817 - Log balance when account is empty

---

app/src/main/java/org/p2p/wallet/auth/interactor/restore/SocialShareRestoreInteractor.kt
app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt
app/src/main/java/org/p2p/wallet/auth/model/RestoreUserResult.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/GeneralErrorScreenError.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestorePresenter.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/response/Web3AuthErrorResponse.kt
app/src/main/res/layout/fragment_common_restore.xml
app/src/main/res/values/onboarding_strings.xml
app/src/main/res/values/settings_strings.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-5254

PWN-5452- Fix restore error screen state

---

app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt
app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestoreFragment.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/GoogleSignInHelper.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/response/Web3AuthErrorResponse.kt

https://p2pvalidator.atlassian.net/browse/PWN-5197
Flow fixes with custom + device share

PWN-5197 - flow fixes with custom + device share

---

app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt

https://p2pvalidator.atlassian.net/browse/PWN-5356

PWN-5356 - Remove check token expiration

---

app/build.gradle
app/src/main/java/org/p2p/wallet/common/ui/widget/ExpandView.kt
build.gradle
scripts/dependencies.gradle
solanaj/build.gradle
ui-kit/build.gradle

NO-TICKET - Updated libs

---

app/build.gradle
app/src/main/java/org/p2p/wallet/auth/gateway/GatewayServiceModule.kt
app/src/main/java/org/p2p/wallet/auth/gateway/api/request/GatewayOnboardingMetadataCiphered.kt
app/src/main/java/org/p2p/wallet/auth/gateway/repository/mapper/ChaCha20Poly1305SymmetricKeyGenerator.kt
app/src/main/java/org/p2p/wallet/auth/gateway/repository/mapper/GatewayServiceOnboardingMetadataCipher.kt
app/src/main/java/org/p2p/wallet/renbtc/interactor/BurnBtcInteractor.kt
app/src/test/java/org/p2p/wallet/auth/gateway/repository/mapper/ChaCha20Poly1305SymmetricKeyGeneratorTest.kt
app/src/test/java/org/p2p/wallet/auth/gateway/repository/mapper/GatewayServiceOnboardingMetadataCipherTest.kt
solanaj/src/main/java/org/p2p/solanaj/crypto/Bip44CustomDerivation.kt
solanaj/src/main/java/org/p2p/solanaj/utils/crypto/Base64Utils.kt

https://p2pvalidator.atlassian.net/browse/PWN-5304

PWN-5304 - Unify metadata cipher algorithn 

---

app/src/main/java/org/p2p/wallet/App.kt
app/src/main/java/org/p2p/wallet/AppCreatedAction.kt
app/src/main/java/org/p2p/wallet/AppModule.kt
app/src/main/java/org/p2p/wallet/common/feature_toggles/di/FeatureTogglesModule.kt
app/src/main/java/org/p2p/wallet/common/feature_toggles/remote_config/AppFirebaseRemoteConfig.kt
app/src/main/java/org/p2p/wallet/common/feature_toggles/remote_config/FeatureTogglesValuesSource.kt
app/src/main/java/org/p2p/wallet/common/feature_toggles/remote_config/RemoteConfigValuesProvider.kt
app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/RemoteFeatureToggle.kt
app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/SolendEnabledFeatureToggle.kt
app/src/main/java/org/p2p/wallet/sdk/di/P2PSdkModule.kt
app/src/main/java/org/p2p/wallet/sdk/facade/SolendSdkFacade.kt
app/src/main/java/org/p2p/wallet/sdk/facade/SolendSdkLogger.kt
app/src/main/java/org/p2p/wallet/sdk/facade/mapper/SolendMethodResultMapper.kt
app/src/main/java/org/p2p/wallet/sdk/facade/model/SolendConfigResponse.kt
app/src/main/java/org/p2p/wallet/sdk/facade/model/SolendConfigRootResponse.kt
app/src/main/java/org/p2p/wallet/sdk/facade/model/SolendMethodResultException.kt
app/src/main/java/org/p2p/wallet/solend/SolendModule.kt
app/src/main/java/org/p2p/wallet/solend/data/SolendConfigurationLocalRepository.kt
app/src/main/java/org/p2p/wallet/solend/data/SolendConfigurationRepository.kt
app/src/main/java/org/p2p/wallet/solend/data/SolendUserDepositsRemoteRepository.kt
app/src/main/java/org/p2p/wallet/solend/data/SolendUserDepositsRepository.kt
app/src/main/java/org/p2p/wallet/solend/data/mapper/SolendConfigurationRepositoryMapper.kt
app/src/main/java/org/p2p/wallet/solend/model/SolendConfiguration.kt

https://p2pvalidator.atlassian.net/browse/PWN-5032
- fix using default value if value is not found in default config
- extract actions that should be done on app create into a separate entity
- load Solend conifg if toggle is true

PWN-5032 - Solend. Add feature toggle

---

.editorconfig
.idea/codeStyles/Project.xml
app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
app/src/main/java/org/p2p/wallet/auth/gateway/GatewayServiceModule.kt
app/src/main/java/org/p2p/wallet/auth/interactor/OnboardingInteractor.kt
app/src/main/java/org/p2p/wallet/auth/interactor/RestoreStateMachine.kt
app/src/main/java/org/p2p/wallet/auth/interactor/UserSignUpInteractor.kt
app/src/main/java/org/p2p/wallet/auth/interactor/restore/RestoreWalletInteractor.kt
app/src/main/java/org/p2p/wallet/auth/interactor/restore/TorusKeyInteractor.kt
app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt
app/src/main/java/org/p2p/wallet/auth/model/RestoreUserResult.kt
app/src/main/java/org/p2p/wallet/auth/repository/GatewayServiceErrorHandler.kt
app/src/main/java/org/p2p/wallet/auth/repository/RestoreFlowDataLocalRepository.kt
app/src/main/java/org/p2p/wallet/auth/repository/RestoreUserResultHandler.kt
app/src/main/java/org/p2p/wallet/auth/repository/SignUpFlowDataLocalRepository.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/common/CommonRestorePresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/found/WalletFoundPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore_error/RestoreErrorScreenPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputPresenter.kt
app/src/main/java/org/p2p/wallet/auth/web3authsdk/Web3AuthApi.kt
app/src/main/java/org/p2p/wallet/common/crashlogging/helpers/TimberCrashTree.kt
app/src/main/res/values/onboarding_strings.xml

https://p2pvalidator.atlassian.net/browse/NO-TICKET
#813

NO-TICKET - Fix comments from 5330

---

app/src/main/java/org/p2p/wallet/auth/interactor/UserSignUpInteractor.kt
app/src/main/java/org/p2p/wallet/auth/interactor/restore/TorusKeyInteractor.kt
app/src/main/java/org/p2p/wallet/auth/repository/RestoreUserResultHandler.kt
app/src/main/java/org/p2p/wallet/auth/repository/UserSignUpDetailsStorage.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingPresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/found/WalletFoundPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-5396

PWN-5396 - Change error case title

---

app/src/main/java/org/p2p/wallet/common/ui/widget/earnwidget/EarnWidget.kt
app/src/main/java/org/p2p/wallet/solend/SolendModule.kt
app/src/main/java/org/p2p/wallet/solend/model/SolendDepositToken.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/SolendEarnContract.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/SolendEarnFragment.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/SolendEarnPresenter.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/adapter/SolendEarnAdapter.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/adapter/SolendEarnViewHolder.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/bottomsheet/SolendTopUpBottomSheetContract.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/bottomsheet/SolendTopUpBottomSheetFragment.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/bottomsheet/SolendTopUpBottomSheetPresenter.kt
app/src/main/res/layout/dialog_solend_top_up.xml
app/src/main/res/layout/widget_earn_view.xml
app/src/main/res/values/solend_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-5021
* deposit actions (SolendTopUpBottomSheet)
* deposit go to buy and receive implemented

PWN-5021 - deposit actions implementation

---

app/src/main/java/org/p2p/wallet/auth/interactor/AuthInteractor.kt
app/src/main/java/org/p2p/wallet/auth/repository/UserSignUpDetailsStorage.kt
app/src/main/java/org/p2p/wallet/auth/ui/phone/PhoneNumberEnterFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/smsinput/NewSmsInputFragment.kt
app/src/main/java/org/p2p/wallet/infrastructure/InfrastructureModule.kt
app/src/main/java/org/p2p/wallet/infrastructure/account/AccountStorage.kt
app/src/main/java/org/p2p/wallet/infrastructure/account/AccountStorageContract.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/provider/TokenKeyProvider.kt
app/src/main/java/org/p2p/wallet/infrastructure/security/SecureStorage.kt
app/src/main/java/org/p2p/wallet/infrastructure/security/SecureStorageContract.kt
app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt
app/src/main/java/org/p2p/wallet/restore/ui/seedphrase/SeedPhrasePresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-5408
https://p2pvalidator.atlassian.net/browse/PWN-5377
https://p2pvalidator.atlassian.net/browse/PWN-5049

PWN-5408 PWN-5377 PWN-5049 - Onboarding fixes and crashes

---

app/src/main/java/org/p2p/wallet/auth/ui/phone/countrypicker/CountryCodePickerFragment.kt
app/src/main/java/org/p2p/wallet/utils/NavigationExtensions.kt

https://p2pvalidator.atlassian.net/browse/PWN-5236

PWN-5236 - Keyboard behavior fix

---

app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-5440

PWN-5440 - Fix pin confirmation snackbar show

---

app/src/main/assets/index.html
app/src/main/java/org/p2p/wallet/common/crypto/keystore/EncoderDecoder.kt
app/src/main/java/org/p2p/wallet/common/crypto/keystore/EncoderDecoderMarshmallow.kt
app/src/main/java/org/p2p/wallet/common/crypto/keystore/KeyStoreWrapper.kt
app/src/main/java/org/p2p/wallet/infrastructure/InfrastructureModule.kt
app/src/main/java/org/p2p/wallet/infrastructure/account/AccountStorage.kt
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/NO-TICKET

NO-TICKET - Device share correct decoding after logout

---

app/src/main/java/org/p2p/wallet/auth/ui/generalerror/timer/OnboardingGeneralErrorTimerFragment.kt
app/src/main/res/layout/fragment_onboarding_general_error_timer.xml

https://p2pvalidator.atlassian.net/browse/PWN-5342

PWN-5342 - add intercom to timer screen

---

app/src/main/java/org/p2p/wallet/infrastructure/InfrastructureModule.kt

https://p2pvalidator.atlassian.net/browse/PWN-5457

PWN-5457 - fix crash

---

app/src/main/res/layout/dialog_btc_network_info.xml

https://p2pvalidator.atlassian.net/browse/PWN-5519

PWN-5519 - Fix background color

---

app/proguard-rules.pro
app/src/main/java/org/p2p/wallet/appsfly/AppsFlyerService.kt
app/src/main/java/org/p2p/wallet/infrastructure/InfrastructureModule.kt
app/src/main/java/org/p2p/wallet/push_notifications/AppFirebaseMessagingService.kt

https://p2pvalidator.atlassian.net/browse/PWN-5522

PWN-5522 - Add log for app delete 

---

app/src/main/java/org/p2p/wallet/solend/ui/deposit/SolendDepositFragment.kt
app/src/main/java/org/p2p/wallet/solend/ui/deposit/SolendDepositPresenter.kt
app/src/main/java/org/p2p/wallet/solend/ui/deposits/SolendUserDepositsFragment.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/SolendEarnContract.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/SolendEarnFragment.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/SolendEarnPresenter.kt
app/src/main/java/org/p2p/wallet/solend/ui/withdraw/SolendWithdrawContract.kt
app/src/main/java/org/p2p/wallet/solend/ui/withdraw/SolendWithdrawFragment.kt
app/src/main/java/org/p2p/wallet/solend/ui/withdraw/SolendWithdrawPresenter.kt
app/src/main/res/layout/fragment_solend_withdraw.xml
app/src/main/res/values/solend_strings.xml
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitDoubleInputView.kt

https://p2pvalidator.atlassian.net/browse/PWN-5027
PWN-5318 - fix ticker to reset on destroy to update valid ticker os start session in next deposit open
PWN-5027 - reset input on depositTokenSelect
PWN-5027 - other fixes + SolendWithdrawFragment.kt copy logic from Deposit

PWN-5027 - latest UI fixes for Solend

---

app/src/main/java/org/p2p/wallet/solend/ui/earn/SolendEarnFragment.kt
app/src/main/res/layout/fragment_solend_earn.xml
app/src/main/res/layout/item_solend_deposit_shimmer.xml

https://p2pvalidator.atlassian.net/browse/PWN-5027
Fix with layout changes as library apply this animation only to 1 shimmer at the screen (super fail) so we need to make only one shimmer on whole screen at once

PWN-5027 - six of shimmer Animation

---

app/src/main/res/drawable/ic_chevron_right.xml
app/src/main/res/layout/dialog_select_token.xml
app/src/main/res/layout/dialog_send_confirm.xml
app/src/main/res/layout/dialog_swap_confirm.xml
app/src/main/res/layout/dialog_swap_settings.xml
app/src/main/res/layout/dialog_transaction_progress.xml
app/src/main/res/layout/fragment_new_buy.xml
app/src/main/res/layout/fragment_receive_ren_btc.xml
app/src/main/res/layout/fragment_ren_btc.xml
app/src/main/res/layout/fragment_send.xml
app/src/main/res/layout/item_ren_transaction.xml
app/src/main/res/layout/item_settings_complex.xml
app/src/main/res/layout/widget_account_fee_view.xml
app/src/main/res/layout/widget_double_text_view.xml
app/src/main/res/layout/widget_receive_card_view.xml
app/src/main/res/layout/widget_swap_details.xml

https://p2pvalidator.atlassian.net/browse/PWN-5210
PWN-5210 - chevron is chevron - arrow is arrow (make icons at needed places with correct names)

PWN-5210 - icons fix

---

app/src/main/java/org/p2p/wallet/auth/AuthModule.kt
app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt
app/src/main/java/org/p2p/wallet/auth/model/ResolvedUsernames.kt
app/src/main/java/org/p2p/wallet/auth/model/Username.kt
app/src/main/java/org/p2p/wallet/auth/ui/done/AuthDonePresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/username/UsernameFragment.kt
app/src/main/java/org/p2p/wallet/common/feature_toggles/di/FeatureTogglesModule.kt
app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/RemoteFeatureToggle.kt
app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/UsernameDomainFeatureToggle.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/NetworkModule.kt
app/src/main/java/org/p2p/wallet/receive/solana/ReceiveSolanaFragment.kt
app/src/main/java/org/p2p/wallet/receive/solana/ReceiveSolanaPresenter.kt
app/src/main/java/org/p2p/wallet/receive/token/ReceiveTokenFragment.kt
app/src/main/java/org/p2p/wallet/receive/token/ReceiveTokenPresenter.kt
app/src/main/java/org/p2p/wallet/receive/widget/QrView.kt
app/src/main/java/org/p2p/wallet/send/interactor/SearchInteractor.kt
app/src/main/java/org/p2p/wallet/send/model/Target.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
app/src/main/java/org/p2p/wallet/send/ui/search/SearchContract.kt
app/src/main/java/org/p2p/wallet/send/ui/search/SearchFragment.kt
app/src/main/java/org/p2p/wallet/send/ui/search/SearchPresenter.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchAdapter.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchViewHolder.kt
app/src/main/java/org/p2p/wallet/settings/model/SettingsItemMapper.kt
app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
app/src/main/res/layout/fragment_reserve_username.xml
app/src/main/res/layout/fragment_username.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-5169
- add username_domain feature-toggle
- remove p2p.sol postfix

PWN-5169 - New nameservice username domain

---

app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt
app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/OnboardingReserveUsernameContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/OnboardingReserveUsernameFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/OnboardingReserveUsernamePresenter.kt
app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/ReserveUsernameOpenedFrom.kt
app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/UsernameValidator.kt
app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/widget/ReserveUsernameInputView.kt
app/src/main/java/org/p2p/wallet/auth/username/api/response/CreateNameResponse.kt
app/src/main/java/org/p2p/wallet/auth/username/repository/UsernameRemoteRepository.kt
app/src/main/java/org/p2p/wallet/auth/username/repository/UsernameRepository.kt
app/src/main/java/org/p2p/wallet/auth/username/repository/mapper/RegisterUsernameServiceApiMapper.kt
app/src/main/java/org/p2p/wallet/common/crashlogging/helpers/CrashHttpLoggingInterceptor.kt
app/src/main/java/org/p2p/wallet/common/crashlogging/helpers/TimberCrashTree.kt
app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt
app/src/main/java/org/p2p/wallet/rpc/repository/solana/RpcSolanaRemoteRepository.kt
app/src/main/java/org/p2p/wallet/settings/ui/settings/NewSettingsFragment.kt
app/src/main/java/org/p2p/wallet/utils/NetworkExtensions.kt
app/src/main/res/values/environment_config.xml
solanaj/src/main/java/org/p2p/solanaj/rpc/RpcSolanaRepository.kt

https://p2pvalidator.atlassian.net/browse/PWN-5390
- add debug logs if feature build is in test
- Nameservice API integration with new screen
- Entry point only in settings

PWN-5390 - Nameservice API integration with new screen

---

app/src/main/java/org/p2p/wallet/home/MainFragment.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/SolendEarnContract.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/SolendEarnFragment.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/SolendEarnPresenter.kt
app/src/main/java/org/p2p/wallet/solend/ui/earn/StubSolendEarnFragment.kt
app/src/main/res/drawable/ic_solend_stub_earn.xml
app/src/main/res/layout/fragment_solend_stub_earn.xml
app/src/main/res/values/solend_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-5599
Solend invest stub fragment

PWN-5599 - solend invest stub fragment

---

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-5210
Fix isAccountEmpty state checking

PWN-5210 - fix isAccountEmpty state checking

---

app/src/main/java/org/p2p/wallet/solana/SolanaNetworkObserver.kt

https://p2pvalidator.atlassian.net/browse/PWN-5653

PWN-5653 - Additional fixes for solana degradation

---

app/src/main/java/org/p2p/wallet/history/strategy/context/OrcaSwapParsingContext.kt

https://p2pvalidator.atlassian.net/browse/PWN-5606
Add new swap instruction

PWN-5606 - Update swap instructions

---

app/src/main/java/org/p2p/wallet/AppPrefsBackupAgent.kt
app/src/main/java/org/p2p/wallet/auth/repository/UserSignUpDetailsStorage.kt
app/src/main/java/org/p2p/wallet/common/crypto/keystore/EncoderDecoderMarshmallow.kt
app/src/main/java/org/p2p/wallet/infrastructure/InfrastructureModule.kt
app/src/main/java/org/p2p/wallet/infrastructure/account/AccountStorage.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/provider/TokenKeyProvider.kt
app/src/main/java/org/p2p/wallet/infrastructure/security/SecureStorage.kt

https://p2pvalidator.atlassian.net/browse/PWN-5569
- LOG EVERYTHING!!
- DO NOT ALLOW APP TO CRASH WHILE LAUNCHING WITH get()

PWN-5669 - Keystore crash

---

.github/CODEOWNERS
.github/workflows/android-feature-workflow.yml
.github/workflows/android-release-workflow.yml
.gitignore
.idea/codeStyles/Project.xml
app/build.gradle
app/gradle.properties
app/src/feature/res/values/environment_config.xml
app/src/main/res/drawable/ic_launcher_foreground.xml
app/src/release/res/values/environment_config.xml
scripts/properties.gradle
scripts/versioning.gradle

https://p2pvalidator.atlassian.net/browse/PWN-5665

PWN-5665 - Versioning and CI/CD improvements

---

app/src/test/java/org/p2p/wallet/send/ui/main/SendPresenterTest.kt

NO-TICKET - fix SendPresenterTest.kt

---

app/src/main/java/org/p2p/wallet/home/MainFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-5681
Make feedback button not checkable and reselect last selected item on feedback item selected

PWN-5681 - make feedback button not checkable

---

app/src/main/java/org/p2p/wallet/AppPrefsBackupAgent.kt
app/src/main/java/org/p2p/wallet/auth/repository/UserSignUpDetailsStorage.kt
app/src/main/java/org/p2p/wallet/common/crypto/keystore/EncoderDecoderMarshmallow.kt
app/src/main/java/org/p2p/wallet/infrastructure/InfrastructureModule.kt
app/src/main/java/org/p2p/wallet/infrastructure/account/AccountStorage.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/provider/TokenKeyProvider.kt
app/src/main/java/org/p2p/wallet/infrastructure/security/SecureStorage.kt

QA requested the fix in the develop **now**

PWN-5669 - Keystore crash 1.14.1 to develop

---

app/gradle.properties
app/src/main/java/org/p2p/wallet/debug/torus/DebugTorusFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
app/src/main/java/org/p2p/wallet/utils/StringExtensions.kt
app/src/main/res/values/environment_config.xml

https://p2pvalidator.atlassian.net/browse/PWN-5732

PWN-5732 - Change copy address logic

---

app/gradle.properties
app/src/main/java/org/p2p/wallet/AppCreatedAction.kt
app/src/main/java/org/p2p/wallet/auth/interactor/UsernameInteractor.kt
app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt
app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/ReserveUsernameFragment.kt
app/src/main/java/org/p2p/wallet/debug/torus/DebugTorusFragment.kt
app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt
app/src/main/res/values/environment_config.xml

https://p2pvalidator.atlassian.net/browse/PWN-5729
- the subject sobstvenno

PWN-5729- Restore username on app create

---

app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
app/src/main/java/org/p2p/wallet/utils/StringExtensions.kt

https://p2pvalidator.atlassian.net/browse/PWN-5732

PWN-5732 - change home screen copy address logic to release

---

app/src/main/res/layout/layout_home_toolbar.xml

https://p2pvalidator.atlassian.net/browse/PWN-5730
Fix toolbar layout according to inner content

PWN-5730 - Toolbar fix

---

app/build.gradle

- Profile envelopes are sent directly from profiler (https://github.com/getsentry/sentry-java/pull/2298)
- Add support for using Encoder with logback.SentryAppender (https://github.com/getsentry/sentry-java/pull/2246)
- Report Startup Crashes (https://github.com/getsentry/sentry-java/pull/2277)
- HTTP Client errors for OkHttp (https://github.com/getsentry/sentry-java/pull/2287)
- Add option to enable or disable Frame Tracking (https://github.com/getsentry/sentry-java/pull/2314)
- Fixed AbstractMethodError when getting Lifecycle (https://github.com/getsentry/sentry-java/pull/2228)
- Missing unit fields for Android measurements (https://github.com/getsentry/sentry-java/pull/2204)
- Avoid sending empty profiles (https://github.com/getsentry/sentry-java/pull/2232)
- Fix file descriptor leak …

NO-TICKET - update Sentry version to 6.6.0

---

app/src/main/java/org/p2p/wallet/auth/ui/pin/newcreate/NewCreatePinFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/reserveusername/ReserveUsernameFragment.kt
app/src/main/java/org/p2p/wallet/home/MainFragment.kt
app/src/main/java/org/p2p/wallet/restore/RestoreModule.kt
app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsFragment.kt
app/src/main/java/org/p2p/wallet/restore/ui/derivable/DerivableAccountsPresenter.kt
app/src/main/java/org/p2p/wallet/restore/ui/seedphrase/SeedPhraseFragment.kt
app/src/main/java/org/p2p/wallet/utils/BundleUtils.kt

https://p2pvalidator.atlassian.net/browse/PWN-5743
on the first time extractFromBundle result type was Array<MainOnCreateAction> but when getting app from the background - the type was Parcelable

PWN-5743 - fix crash when getting the app from background

---

ui-kit/src/main/kotlin/org/p2p/uikit/organisms/seedphrase/adapter/SeedPhraseAdapter.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/seedphrase/adapter/SeedPhraseWordViewHolder.kt

https://p2pvalidator.atlassian.net/browse/PWN-4391
PWN-4391 - seed phrase adapter fix - use lastIndex + remove textWatchers on recycle ViewHolder

PWN-4391 - SeedPhrase adapter fix

---

app/src/main/java/org/p2p/wallet/common/ui/widget/earnwidget/EarnWidget.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt
app/src/main/java/org/p2p/wallet/utils/AmountExtensions.kt
app/src/main/res/values/ids.xml
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitAmountsView.kt
ui-kit/src/main/kotlin/org/p2p/uikit/textwatcher/AmountFractionFormatter.kt
ui-kit/src/main/kotlin/org/p2p/uikit/textwatcher/AmountFractionTextWatcher.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/AmountExtensions.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/DecimalFormatter.kt
ui-kit/src/main/res/values/ids.xml

https://p2pvalidator.atlassian.net/browse/PWN-5103
Validation fixes

PWN-5103 - validation fix

---

app/src/main/java/org/p2p/wallet/restore/ui/seedphrase/SeedPhraseContract.kt
app/src/main/java/org/p2p/wallet/restore/ui/seedphrase/SeedPhraseFragment.kt
app/src/main/java/org/p2p/wallet/restore/ui/seedphrase/SeedPhrasePresenter.kt
app/src/main/java/org/p2p/wallet/settings/ui/reset/seedphrase/ResetSeedPhraseFragment.kt
app/src/main/res/layout/fragment_seed_phrase.xml
app/src/main/res/values/onboarding_strings.xml
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/seedphrase/UiKitSeedPhraseView.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/seedphrase/adapter/SeedPhraseAdapter.kt

https://p2pvalidator.atlassian.net/browse/PWN-5801
- remove all occurances of "secret word" to seed phrase

PWN-5801 - change subtitle on seed phrase

---

app/src/main/java/org/p2p/wallet/utils/ContextExtensions.kt

NO-TICKET - Hiding error resources for debug builds

---

app/src/main/java/org/p2p/wallet/history/interactor/mapper/HistoryTransactionMapper.kt
app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/TransactionViewHolder.kt
app/src/main/java/org/p2p/wallet/utils/TextViewExtensions.kt

https://p2pvalidator.atlassian.net/browse/PWN-5778

PWN-5778 - Fix usd price for sol transaction

---

app/src/main/AndroidManifest.xml
app/src/main/res/layout/fragment_scan_qr.xml

https://p2pvalidator.atlassian.net/browse/PWN-5771

PWN-5771 - Fix camera bugs

---

app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaInfoInteractor.kt
app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaPoolInteractor.kt
app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaSwapInteractor.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapContract.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
app/src/main/res/layout/fragment_swap_orca.xml

https://p2pvalidator.atlassian.net/browse/PWN-5885
implemented with:
https://github.com/p2p-org/OrcaSwapSwift/pull/7/files
https://github.com/p2p-org/p2p-wallet-ios/pull/687/files
@1sakov @isakovch please check

PWN-5885 - Transitive swap with inter token btc or eth

---

app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaInfoInteractor.kt
app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaPoolInteractor.kt
app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaSwapInteractor.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapContract.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
app/src/main/res/layout/fragment_swap_orca.xml

https://p2pvalidator.atlassian.net/browse/PWN-5885
Already approved and merged to develop in another PR
[#947](https://github.com/p2p-org/p2p-wallet-android/pull/947)

PWN-5885 - Transitive swap with inter token btc or eth to RELEASE 

---

app/src/main/java/org/p2p/wallet/receive/network/ReceiveNetworkTypeFragment.kt
app/src/main/java/org/p2p/wallet/renbtc/ui/info/RenBtcTopupBottomSheet.kt
app/src/main/java/org/p2p/wallet/utils/ContextExtensions.kt
app/src/main/res/layout/dialog_ren_btc_topup.xml

https://p2pvalidator.atlassian.net/browse/PWN-5817

PWN-5817 - share solana address from RenBtcTopUp dialog

---

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-5888

PWN-5888 - Sol account minor fixes

---

app/src/main/java/org/p2p/wallet/auth/gateway/GatewayServiceModule.kt
app/src/main/java/org/p2p/wallet/auth/gateway/api/GatewayServiceApi.kt
app/src/main/java/org/p2p/wallet/auth/gateway/api/request/GatewayServiceJsonRpcMethod.kt
app/src/main/java/org/p2p/wallet/auth/gateway/api/request/GetOnboardingMetadataRequest.kt
app/src/main/java/org/p2p/wallet/auth/gateway/api/response/GetOnboardingMetadataResponse.kt
app/src/main/java/org/p2p/wallet/auth/gateway/repository/GatewayServiceRemoteRepository.kt
app/src/main/java/org/p2p/wallet/auth/gateway/repository/GatewayServiceRepository.kt
app/src/main/java/org/p2p/wallet/auth/gateway/repository/mapper/GatewayServiceGetOnboardingMetadataMapper.kt
app/src/main/java/org/p2p/wallet/auth/gateway/repository/mapper/GatewayServiceOnboardingMetadataCipher.kt
app/src/main/java/org/p2p/wallet/auth/interactor/restore/UserRestoreInteractor.kt
app/src/main/java/org/p2p/wallet/infrastructure/security/SecureStorageContract.kt
app/src/main/java/org/p2p/wallet/utils/chacha/ChaCha20Poly1305Decryptor.kt
app/src/main/java/org/p2p/wallet/utils/chacha/ChaCha20Poly1305Encryptor.kt
app/src/main/java/org/p2p/wallet/utils/chacha/ChaCha20Poly1305SymmetricKeyGenerator.kt
app/src/test/java/org/p2p/wallet/auth/gateway/repository/mapper/ChaCha20Poly1305SymmetricKeyGeneratorTest.kt
app/src/test/java/org/p2p/wallet/auth/gateway/repository/mapper/GatewayServiceOnboardingMetadataCipherTest.kt

https://p2pvalidator.atlassian.net/browse/PWN-5216

PWN-5216 - Gateway API. get_metadata added

---

app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetFragment.kt
app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetPresenter.kt
app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsContract.kt
app/src/main/java/org/p2p/wallet/root/RootActivity.kt
app/src/main/res/layout/activity_root.xml
app/src/main/res/layout/dialog_history_transaction_details.xml

https://p2pvalidator.atlassian.net/browse/PWN-5773

PWN-5773 - Minor fixes for transfer transactions details

---

.github/workflows/android-release-workflow.yml

NO-TICKET - fix release workflow

---

app/build.gradle

Torus properties were initializing 5 times instead of 1

NO-TICKET - Initializing torus properties only once

---

app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-4952

PWN-4952 - Fix amount validation after app comes back from background

---

.github/actions/setup-gradle/action.yml
.github/actions/setup-keystore-jks/action.yml
.github/actions/setup-project/action.yml
.github/actions/setup-slack/action.yml
.github/workflows/android-build-only-workflow.yml
.github/workflows/android-feature-workflow.yml
.github/workflows/android-release-workflow.yml
app/build.gradle
build.gradle
gradle.properties
scripts/changelog.gradle

NO-TICKET - Fix CI release flow on release branch

---

app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
app/src/main/res/values/environment_config.xml

https://p2pvalidator.atlassian.net/browse/PWN-6079
https://p2pvalidator.atlassian.net/browse/PWN-6083

PWN-6079 - Send screen callback fixes

---

app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-6064

PWN-6064 - Fix restore state text

---

app/src/main/java/org/p2p/wallet/receive/solana/ReceiveSolanaFragment.kt
app/src/main/java/org/p2p/wallet/receive/token/ReceiveTokenFragment.kt
app/src/main/java/org/p2p/wallet/receive/widget/ReceiveCardView.kt

https://p2pvalidator.atlassian.net/browse/PWN-6068
Removed bitcoin receive screen.
Stashed back sending renBTC to bitcoin network

PWN-6068 - Removed bitcoin network selection

---

app/src/main/java/org/p2p/wallet/common/mvp/BaseFragment.kt
app/src/main/java/org/p2p/wallet/home/HomeModule.kt
app/src/main/java/org/p2p/wallet/home/model/SelectTokenItem.kt
app/src/main/java/org/p2p/wallet/home/model/SelectableTokenRoundedState.kt
app/src/main/java/org/p2p/wallet/home/ui/new/NewSelectTokenContract.kt
app/src/main/java/org/p2p/wallet/home/ui/new/NewSelectTokenFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/new/NewSelectTokenPresenter.kt
app/src/main/java/org/p2p/wallet/home/ui/new/adapter/CategoryTitleViewHolder.kt
app/src/main/java/org/p2p/wallet/home/ui/new/adapter/NewSelectTokenAdapter.kt
app/src/main/java/org/p2p/wallet/home/ui/new/adapter/NewSelectTokenViewHolder.kt
app/src/main/java/org/p2p/wallet/home/ui/new/adapter/NewTokenAdapterDiffCallback.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendContract.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendPresenter.kt
app/src/main/res/layout/fragment_select_token_new.xml
app/src/main/res/layout/item_pick_token_category.xml
app/src/main/res/layout/item_pick_token_new.xml
app/src/main/res/layout/item_search_bar.xml
app/src/main/res/menu/menu_search.xml
app/src/main/res/values/send_strings.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-6089
Added new pick a token screen. 
It's hidden behind the debug feature flag for send flow

PWN-6089 - Pick a token screen for new send flow

---

app/src/main/java/org/p2p/wallet/auth/analytics/RestoreWalletAnalytics.kt
app/src/main/java/org/p2p/wallet/common/analytics/trackers/AmplitudeTracker.kt
app/src/main/java/org/p2p/wallet/home/analytics/HomeAnalytics.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-6051

PWN-6051 -  Fix amplitude user property and add some events

---

app/src/main/java/org/p2p/wallet/feerelayer/api/FeeRelayerInfoRequest.kt
app/src/main/java/org/p2p/wallet/feerelayer/model/FeeRelayerConverter.kt
app/src/main/java/org/p2p/wallet/feerelayer/model/FeeRelayerEnvironment.kt
app/src/main/java/org/p2p/wallet/feerelayer/model/FeeRelayerStatistics.kt

https://p2pvalidator.atlassian.net/browse/PWN-6123

PWN-6123 - Fee relayer environment statistics

---

app/src/main/java/org/p2p/wallet/newsend/NewSendFragment.kt
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitSendDetailsWidget.kt

https://p2pvalidator.atlassian.net/browse/PWN-6238
PWN-6238 - set token in UiKitSendDetailsWidget.kt

PWN-6238 - set token in UiKitSendDetailsWidget.kt

---

app/src/main/java/org/p2p/wallet/send/interactor/SearchInteractor.kt

https://p2pvalidator.atlassian.net/browse/PWN-6052
PWN-6052 - do not check balance for address

PWN-6052 - do not check balance for address

---

app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/NewSendEnabledFeatureToggle.kt
app/src/main/java/org/p2p/wallet/home/ui/new/NewSelectTokenFragment.kt
app/src/main/java/org/p2p/wallet/newsend/NewSendContract.kt
app/src/main/java/org/p2p/wallet/newsend/NewSendFragment.kt
app/src/main/java/org/p2p/wallet/newsend/NewSendPresenter.kt
app/src/main/java/org/p2p/wallet/newsend/noaccount/SendNoAccountFragment.kt
app/src/main/java/org/p2p/wallet/send/interactor/SendInteractor.kt
app/src/main/java/org/p2p/wallet/send/model/SendSolanaFee.kt
app/src/main/java/org/p2p/wallet/send/ui/dialogs/SendTransactionsDetailsBottomSheet.kt
app/src/main/res/values/environment_config.xml
app/src/main/res/values/send_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-6092

PWN-6092 - Update fee payer implementation

---

.github/actions/setup-apikey/action.yml
.github/actions/setup-project/action.yml
.github/workflows/android-feature-workflow.yml
.github/workflows/android-release-workflow.yml

https://p2pvalidator.atlassian.net/browse/NO-TICKET

NO-TICKET - add Moonpay Sandbox API key to CI

---

app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
app/src/main/java/org/p2p/wallet/home/ui/new/NewSelectTokenFragment.kt
app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyPresenter.kt
app/src/main/java/org/p2p/wallet/newsend/NewSendContract.kt
app/src/main/java/org/p2p/wallet/newsend/NewSendFragment.kt
app/src/main/java/org/p2p/wallet/newsend/NewSendPresenter.kt
app/src/main/java/org/p2p/wallet/newsend/model/CalculationMode.kt
app/src/main/java/org/p2p/wallet/newsend/noaccount/SendNoAccountFragment.kt
app/src/main/java/org/p2p/wallet/send/model/SendFeeTotal.kt
app/src/main/java/org/p2p/wallet/send/model/SendSolanaFee.kt
app/src/main/java/org/p2p/wallet/send/ui/SendNoTokensFragment.kt
app/src/main/java/org/p2p/wallet/send/ui/dialogs/SendTransactionsDetailsBottomSheet.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendDetailsView.kt
app/src/main/java/org/p2p/wallet/send/ui/search/NewSearchPresenter.kt
app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
app/src/main/java/org/p2p/wallet/utils/NavigationExtensions.kt
app/src/main/res/drawable/ic_send_buy.xml
app/src/main/res/drawable/ic_send_receive.xml
app/src/main/res/layout/dialog_send_transactions_details.xml
app/src/main/res/layout/fragment_send_no_token.xml
app/src/main/res/values/environment_config.xml
app/src/main/res/values/send_strings.xml
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitSendDetailsWidget.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/SpanUtils.kt
ui-kit/src/main/res/layout/widget_send_details_input.xml

https://p2pvalidator.atlassian.net/browse/PWN-6092
- Fixing state issues

PWN-6092 - Additional fixes for send

---

app/src/main/java/org/p2p/wallet/newsend/ui/search/NewSearchPresenter.kt
app/src/main/java/org/p2p/wallet/send/interactor/SearchInteractor.kt
app/src/main/java/org/p2p/wallet/send/model/SearchResult.kt
app/src/main/res/values/send_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-6393
PWN-6393 - check direct addresses and show error or preselect token if it was not selected

PWN-6393 - check direct addresses and show error or preselect token if it was not selected

---

app/src/main/java/org/p2p/wallet/newsend/ui/search/NewSearchFragment.kt
app/src/main/java/org/p2p/wallet/newsend/ui/search/NewSearchPresenter.kt
ui-kit/src/main/kotlin/org/p2p/uikit/organisms/UiKitToolbar.kt

https://p2pvalidator.atlassian.net/browse/PWN-6398
PWN-6398 - fix restore searched state

PWN-6398 - fix restore searched state

---

app/src/main/java/org/p2p/wallet/send/interactor/SearchInteractor.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchEmptyBalanceViewHolder.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchInvalidResultViewHolder.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchViewHolder.kt
app/src/main/res/values/send_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-6391
PWN-6391 - check own address and own token direct address

PWN-6391 - check own address and own token direct address

---

app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerTopUpInteractor.kt
app/src/main/java/org/p2p/wallet/feerelayer/model/FeeRelayerFee.kt
app/src/main/java/org/p2p/wallet/feerelayer/repository/FeeRelayerRemoteRepository.kt
app/src/main/java/org/p2p/wallet/home/HomeModule.kt
app/src/main/java/org/p2p/wallet/newsend/SendFeeRelayerManager.kt
app/src/main/java/org/p2p/wallet/newsend/model/NewSendButtonValidator.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendContract.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendFragment.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
app/src/main/java/org/p2p/wallet/newsend/ui/details/NewSendDetailsBottomSheet.kt
app/src/main/java/org/p2p/wallet/newsend/ui/details/NewSendDetailsContract.kt
app/src/main/java/org/p2p/wallet/newsend/ui/details/NewSendDetailsPresenter.kt
app/src/main/java/org/p2p/wallet/newsend/ui/search/NewSearchPresenter.kt
app/src/main/java/org/p2p/wallet/newsend/ui/stub/SendFeePayerPromptFragment.kt
app/src/main/java/org/p2p/wallet/root/RootPresenter.kt
app/src/main/java/org/p2p/wallet/send/SendModule.kt
app/src/main/java/org/p2p/wallet/send/interactor/SearchInteractor.kt
app/src/main/java/org/p2p/wallet/send/interactor/SendInteractor.kt
app/src/main/java/org/p2p/wallet/send/model/SearchResult.kt
app/src/main/java/org/p2p/wallet/send/model/SendSolanaFee.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchAdapter.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchViewHolder.kt
app/src/main/res/layout/dialog_new_send_details.xml
app/src/main/res/layout/fragment_send_new.xml
app/src/main/res/layout/item_search.xml
app/src/main/res/values/send_strings.xml
app/src/main/res/values/strings.xml
solana/src/main/java/org/p2p/solanaj/core/FeeAmount.kt

https://p2pvalidator.atlassian.net/browse/PWN-6464
https://p2pvalidator.atlassian.net/browse/PWN-6483 
https://p2pvalidator.atlassian.net/browse/PWN-6405
https://p2pvalidator.atlassian.net/browse/PWN-6484
PWN-6464 - Min SOL balances for sender and recipient logic
PWN-6405, PWN-6483 - Fee Payers Tokens async fetching and parsing fixed 
PWN-6484 - Crash fixed
NO-TICKET - Debug info fixes

PWN-6464 - Additional Send Screen fixes #7

---

app/src/main/java/org/p2p/wallet/newsend/ui/search/NewSearchContract.kt
app/src/main/java/org/p2p/wallet/newsend/ui/search/NewSearchFragment.kt
app/src/main/java/org/p2p/wallet/newsend/ui/search/NewSearchPresenter.kt
app/src/main/res/layout/fragment_new_search.xml

https://p2pvalidator.atlassian.net/browse/PWN-6052
PWN-6052 - remove continue button as not longer needed

PWN-6052 - remove continue button

---

app/src/main/java/org/p2p/wallet/home/MainFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/bottomsheet/HomeActionsBottomSheet.kt
app/src/main/java/org/p2p/wallet/moonpay/repository/sell/MoonpaySellFiatCurrency.kt
app/src/main/java/org/p2p/wallet/moonpay/repository/sell/MoonpaySellRemoteRepository.kt
app/src/main/java/org/p2p/wallet/sell/interactor/SellInteractor.kt
app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadFragment.kt
app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadPresenter.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt
app/src/main/res/layout/fragment_sell_payload.xml
app/src/main/res/values/main_strings.xml
app/src/main/res/values/strings.xml
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitAmountEditText.kt
ui-kit/src/main/res/drawable/bg_rounded_solid_snow_bottom_12.xml
ui-kit/src/main/res/drawable/bg_rounded_solid_snow_top_12.xml
ui-kit/src/main/res/layout/widget_ui_kit_amount_edit_text.xml

https://p2pvalidator.atlassian.net/browse/PWN-6478
https://p2pvalidator.atlassian.net/browse/PWN-6477
https://p2pvalidator.atlassian.net/browse/PWN-6457 
https://p2pvalidator.atlassian.net/browse/PWN-6312
https://p2pvalidator.atlassian.net/browse/PWN-6455
https://p2pvalidator.atlassian.net/browse/PWN-6454
fixes described in tickets

PWN-6454 - Off ramp. Bugfixes.

---

app/src/main/java/org/p2p/wallet/newsend/ui/NewSendFragment.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
app/src/main/java/org/p2p/wallet/send/model/SearchResult.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchInvalidResultViewHolder.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchViewHolder.kt
app/src/main/java/org/p2p/wallet/utils/KeyExtensions.kt
ui-kit/src/main/res/layout/widget_send_details_input.xml

https://p2pvalidator.atlassian.net/browse/PWN-6510
https://p2pvalidator.atlassian.net/browse/PWN-6537
https://p2pvalidator.atlassian.net/browse/PWN-6544
https://p2pvalidator.atlassian.net/browse/PWN-6545
PWN-6510 - Fee clickable area reduced
PWN-6537 - Empty search state of selection token screen fixes 
PWN-6544 - Main send screen username parsing
PWN-6545 - Empty balance tokens filtering enabled

PWN-6510 - Additional Send screen fixes

---

app/src/main/java/org/p2p/wallet/common/ui/widget/SlippageRadioView.kt
app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerInteractor.kt
app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerTopUpInteractor.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendContract.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendFragment.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaPoolInteractor.kt
app/src/main/java/org/p2p/wallet/swap/model/Slippage.kt
app/src/main/java/org/p2p/wallet/swap/model/orca/SwapState.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt
app/src/main/java/org/p2p/wallet/swap/ui/settings/SwapSettingsFragment.kt
build.gradle
core/build.gradle
scripts/dependencies.gradle
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitSendDetailsWidget.kt
ui-kit/src/main/res/layout/widget_send_details_input.xml

https://p2pvalidator.atlassian.net/browse/PWN-6551

PWN-6551 - Pool sorting optimized

---

app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpBottomSheet.kt
app/src/main/java/org/p2p/wallet/home/ui/main/bottomsheet/HomeActionsBottomSheet.kt
app/src/main/res/drawable/shape_bottomsheet_pointer.xml
app/src/main/res/layout/dialog_base_done.xml
app/src/main/res/layout/dialog_new_send_details.xml
app/src/main/res/layout/dialog_send_free_transactions_info.xml
app/src/main/res/layout/item_info_image_double_text.xml
app/src/main/res/values-v27/theme.xml

https://p2pvalidator.atlassian.net/browse/PWN-6538
PWN-6538 - transaction details bottomsheet ui and layout fixes

PWN-6538 - transaction details bottomsheet ui and layout fixes

---

app/src/main/java/org/p2p/wallet/common/mvp/BaseFragment.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseFragmentContract.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpActivity.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpBottomSheet.kt
app/src/main/java/org/p2p/wallet/common/mvp/MvpView.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-6554
Provide showToast in MvpView.kt and use it to show max on new Send

PWN-6554 - provide showToast everywhere!

---

app/src/main/java/org/p2p/wallet/home/ui/new/NewSelectTokenFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/new/adapter/NewSelectTokenViewHolder.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendFragment.kt
app/src/main/java/org/p2p/wallet/newsend/ui/details/NewSendDetailsBottomSheet.kt
app/src/main/java/org/p2p/wallet/root/RootActivity.kt
app/src/main/java/org/p2p/wallet/send/model/SearchResult.kt
app/src/main/java/org/p2p/wallet/send/model/SendSolanaFee.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendDetailsView.kt
app/src/main/res/layout/fragment_send_no_account.xml
app/src/main/res/layout/item_pick_token_new.xml

https://p2pvalidator.atlassian.net/browse/PWN-6552
https://p2pvalidator.atlassian.net/browse/PWN-6544
https://p2pvalidator.atlassian.net/browse/PWN-6559
PWN-6544 - Username parsing
PWN-6559 - Prompt screen corrections
PWN-6552 - Select token fixes

PWN-6552 - Select token fixes

---

app/src/main/java/org/p2p/wallet/newsend/db/RecipientsDao.kt

https://p2pvalidator.atlassian.net/browse/PWN-6560
PWN-6560 - table typo fix

PWN-6560 - remove recipients on logout

---

app/build.gradle
app/src/main/java/org/p2p/wallet/home/repository/HomeDatabaseRepository.kt
app/src/main/java/org/p2p/wallet/home/repository/HomeLocalRepository.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaPoolInteractor.kt
app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
app/src/main/res/layout/item_token.xml
app/src/main/res/layout/item_token_hidden.xml
app/src/main/res/values/theme.xml
scripts/config.gradle
scripts/signing.gradle

NO-TICKET - Optimized sorting
NO-TICKET - Fixed hide buttons on the main screen and behavior
NO-TICKET - Removed old colors from theme

NO-TICKET - random corrections

---

.github/workflows/android-release-workflow.yml
app/src/main/java/org/p2p/wallet/newsend/SendFeeRelayerManager.kt
app/src/main/java/org/p2p/wallet/newsend/model/FeeLoadingState.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendFragment.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitSendDetailsWidget.kt

NO-TICKET - Added delayed loading for send screen

---

app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/SellEnabledFeatureToggle.kt
app/src/main/java/org/p2p/wallet/home/HomeModule.kt
app/src/main/java/org/p2p/wallet/home/MainFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
app/src/main/java/org/p2p/wallet/settings/model/SettingsItemMapper.kt
app/src/main/java/org/p2p/wallet/settings/ui/settings/NewSettingsPresenter.kt
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitBottomNavigationView.kt
ui-kit/src/main/res/menu/menu_ui_kit_bottom_navigation_sell.xml

https://p2pvalidator.atlassian.net/browse/PWN-6312
- support button in settings

PWN-6312 - Add feedback button in settings

---

app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerInteractor.kt
app/src/main/java/org/p2p/wallet/newsend/SendFeeRelayerManager.kt
app/src/main/java/org/p2p/wallet/newsend/model/CalculationMode.kt
app/src/main/java/org/p2p/wallet/newsend/model/NewSendButtonState.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
app/src/main/java/org/p2p/wallet/newsend/ui/details/NewSendDetailsBottomSheet.kt
app/src/main/java/org/p2p/wallet/send/model/SendFeeTotal.kt
app/src/main/java/org/p2p/wallet/send/model/SendSolanaFee.kt
app/src/main/java/org/p2p/wallet/utils/MathUtils.kt
core/src/main/java/org/p2p/core/textwatcher/AmountFractionTextWatcher.kt
core/src/main/java/org/p2p/core/token/Token.kt
core/src/main/java/org/p2p/core/utils/AmountExtensions.kt
core/src/main/java/org/p2p/core/utils/DecimalFormatter.kt

https://p2pvalidator.atlassian.net/browse/PWN-6565
https://p2pvalidator.atlassian.net/browse/PWN-6566
https://p2pvalidator.atlassian.net/browse/PWN-6614
https://p2pvalidator.atlassian.net/browse/PWN-6613
PWN-6565 - Exact min required SOL balance fixes
PWN-6566 - Insufficient SOL funds fixes
PWN-6614 - USD input amount fixes
PWN-6613 - USD Rounding mode changed to DOWN mode

PWN-6565 - Various fixes

---

app/src/main/java/org/p2p/wallet/newsend/analytics/NewSendAnalytics.kt
app/src/main/java/org/p2p/wallet/newsend/model/NewSendButtonState.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
app/src/main/java/org/p2p/wallet/newsend/ui/dialogs/FreeTransactionsDetailsBottomSheet.kt
app/src/main/java/org/p2p/wallet/transaction/ui/ProgressStateWidget.kt
app/src/main/res/layout/fragment_history.xml
app/src/main/res/values/send_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-6193

PWN-6193 - Metrics and other minor fixes

---

app/build.gradle
app/src/main/java/org/p2p/wallet/AppModule.kt
app/src/main/java/org/p2p/wallet/common/crashlogging/CrashLogger.kt
app/src/main/java/org/p2p/wallet/common/crashlogging/impl/SentryFacade.kt
app/src/main/res/layout/fragment_history.xml
scripts/config.gradle

https://p2pvalidator.atlassian.net/browse/PWN-6505

PWN-6505 - Sentry optimize

---

app/src/main/java/org/p2p/wallet/home/ui/new/adapter/NewSelectTokenViewHolder.kt
app/src/main/java/org/p2p/wallet/newsend/model/CalculationMode.kt
app/src/main/res/layout/item_pick_token_new.xml
core/src/main/java/org/p2p/core/token/Token.kt
core/src/main/java/org/p2p/core/utils/AmountExtensions.kt
ui-kit/src/main/res/drawable/ic_lightning.xml

https://p2pvalidator.atlassian.net/browse/PWN-6600

PWN-6600 - Fee calculation fixed

---

app/src/main/java/org/p2p/wallet/auth/ui/generalerror/OnboardingGeneralErrorFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/restore/found/WalletFoundFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
app/src/main/java/org/p2p/wallet/moonpay/model/MoonpaySellError.kt
app/src/main/java/org/p2p/wallet/moonpay/repository/sell/MoonpaySellRepositoryErrorMapper.kt
app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt
app/src/main/java/org/p2p/wallet/sell/ui/error/SellErrorFragment.kt
app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadFragment.kt
app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadPresenter.kt
app/src/main/res/layout/fragment_sell_error.xml
app/src/main/res/values/onboarding_strings.xml
app/src/main/res/values/strings.xml
ui-kit/src/main/res/layout/widget_ui_kit_amount_edit_text.xml

https://p2pvalidator.atlassian.net/browse/PWN-6277
PWN-6277 - Off-ramp. remove action buttons if no internet
PWN-6277 PWN-6512 - Off-ramp. corner cases

PWN-6277 PWN-6512 - Off ramp. Corner cases

---

app/src/main/res/layout/fragment_send_unavailable.xml

https://p2pvalidator.atlassian.net/browse/PWN-6531
PWN-6531 - fix icons and colors

PWN-6531 - fix icons and colors

---

app/src/main/java/org/p2p/wallet/newsend/ui/stub/SendFeePayerPromptFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-6558
PWN-6558 - fix bottom navigation color making replaceFragment and check color according to args

PWN-6558 - fix bottom navigation color

---

ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitSliderSolidButton.kt
ui-kit/src/main/res/layout/widget_slider_solid_button.xml

https://p2pvalidator.atlassian.net/browse/PWN-6535
https://p2pvalidator.atlassian.net/browse/PWN-6553
PWN-6535 - remove slider button animation
PWN-6553 - update slider and make button above texts

PWN-6535, PWN-6553 - Slider fixes

---

app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenViewHolder.kt

https://p2pvalidator.atlassian.net/browse/PWN-6592
PWN-6592 - use updated token item after update balances only

PWN-6592 - token balances fix 

---

app/src/main/java/org/p2p/wallet/common/ui/widget/actionbuttons/ActionButtonsView.kt
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_token_history.xml
app/src/main/res/layout/layout_action_buttons.xml

https://p2pvalidator.atlassian.net/browse/PWN-6677
Single line recycler for ActionButton
[PWN-6677]: https://p2pvalidator.atlassian.net/browse/PWN-6677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PWN-6677 - Single line recycler for ActionButton

---

app/src/main/res/values/environment_config.xml

https://p2pvalidator.atlassian.net/browse/PWN-6699
PWN-6699 - endpoints update - https://push-service.wallet.p2p.org/ → https://push-service.key.app/ https://orca.wallet.p2p.org/ → https://orca.key.app/

PWN-6699 - endpoints update

---

app/src/main/java/org/p2p/wallet/send/interactor/SearchInteractor.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchErrorViewHolder.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchViewHolder.kt

https://p2pvalidator.atlassian.net/browse/PWN-6760
PWN-6760 - search checks fixes + make placeholder and error resource for loading token icons

PWN-6760 - search checks fixes

---

app/src/main/java/org/p2p/wallet/send/model/SendFeeTotal.kt

https://p2pvalidator.atlassian.net/browse/PWN-6736
PWN-6736 - fix total amount presentation

PWN-6736 - fix total amount presentation

---

app/src/main/res/layout/fragment_new_search.xml
ui-kit/src/main/res/layout/item_search_view.xml

https://p2pvalidator.atlassian.net/browse/PWN-6777
PWN-6777 - search screen UI fixes

PWN-6777 - search screen UI fixes

---

app/src/main/java/org/p2p/wallet/common/feature_toggles/di/FeatureTogglesModule.kt
app/src/main/java/org/p2p/wallet/common/feature_toggles/remote_config/LocalFeatureToggleStorage.kt
app/src/main/java/org/p2p/wallet/common/feature_toggles/remote_config/LocalFirebaseRemoteConfig.kt
app/src/main/java/org/p2p/wallet/common/feature_toggles/toggles/remote/SettingsNetworkListFeatureToggle.kt
app/src/main/java/org/p2p/wallet/debug/featuretoggles/FeatureToggleRow.kt
app/src/main/java/org/p2p/wallet/debug/featuretoggles/FeatureToggleRowItem.kt
app/src/main/java/org/p2p/wallet/debug/featuretoggles/FeatureToggleViewHolder.kt
app/src/main/java/org/p2p/wallet/debug/featuretoggles/FeatureTogglesAdapter.kt
app/src/main/java/org/p2p/wallet/debug/featuretoggles/FeatureTogglesContract.kt
app/src/main/java/org/p2p/wallet/debug/featuretoggles/FeatureTogglesFragment.kt
app/src/main/java/org/p2p/wallet/debug/featuretoggles/FeatureTogglesPresenter.kt
app/src/main/java/org/p2p/wallet/infrastructure/InfrastructureModule.kt
app/src/main/res/layout/fragment_feature_toggles.xml
app/src/main/res/layout/item_settings_toggle_item.xml

https://p2pvalidator.atlassian.net/browse/PWN-6723
Screenshot #1 |
:------------:|

PWN-6723 - Debug feature-toggles redesign and save

---

app/src/main/java/org/p2p/wallet/send/interactor/SearchInteractor.kt
app/src/main/java/org/p2p/wallet/send/model/SearchResult.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchErrorViewHolder.kt

https://p2pvalidator.atlassian.net/browse/PWN-6760
PWN-6760 - show correct error state when sending to own addresses

PWN-6760 - search fixes last one

---

app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt
app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryPresenter.kt
app/src/main/java/org/p2p/wallet/moonpay/model/SellTransaction.kt
app/src/main/java/org/p2p/wallet/moonpay/repository/sell/MoonpaySellRemoteRepository.kt
app/src/main/java/org/p2p/wallet/moonpay/repository/sell/MoonpaySellRepositoryMapper.kt
app/src/main/java/org/p2p/wallet/moonpay/serversideapi/response/MoonpaySellTransactionShortResponse.kt
app/src/main/java/org/p2p/wallet/moonpay/serversideapi/response/SellTransactionFailureReason.kt

https://p2pvalidator.atlassian.net/browse/PWN-6683
hide cancelled moonpay transactions

PWN-6683 - hide cancelled moonpay transactions

---

app/src/main/java/org/p2p/wallet/transaction/ui/NewTransactionProgressBottomSheet.kt
app/src/main/java/org/p2p/wallet/transaction/ui/ProgressStateWidget.kt

https://p2pvalidator.atlassian.net/browse/PWN-6561
PWN-6561 - make animation faster + fix locale for date format

PWN-6561 - transaction bottomsheet fixes

---

app/build.gradle
app/proguard-rules.pro
app/src/main/AndroidManifest.xml
app/src/main/java/org/p2p/wallet/appsflyer/AppsFlyerService.kt

https://p2pvalidator.atlassian.net/browse/PWN-6066
it was always been 00000-0000-0000...
https://developers.google.com/android/reference/com/google/android/gms/ads/identifier/AdvertisingIdClient.Info#public-string-getid

PWN-6066 - Fix GAID get for Appsflyer

---

ui-kit/src/main/kotlin/org/p2p/uikit/utils/ViewExtensions.kt

https://p2pvalidator.atlassian.net/browse/PWN-6628

PWN-6628 - Fix keyboard appearing on main screen

---

app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchErrorViewHolder.kt

https://p2pvalidator.atlassian.net/browse/PWN-6794
PWN-6794 - fix own token case text

PWN-6794 - fix own token case text

---

app/build.gradle
app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpBottomSheet.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpFragment.kt
app/src/main/java/org/p2p/wallet/common/ui/recycler/swipe/SwipeRevealLayout.kt
app/src/main/java/org/p2p/wallet/common/ui/widget/CustomSnackBar.kt
app/src/main/java/org/p2p/wallet/infrastructure/InfrastructureModule.kt
app/src/main/java/org/p2p/wallet/infrastructure/RoomModule.kt
app/src/main/java/org/p2p/wallet/infrastructure/StorageModule.kt
app/src/main/java/org/p2p/wallet/intercom/IntercomPushService.kt
app/src/main/java/org/p2p/wallet/qr/ui/ScanQrFragment.kt
app/src/main/java/org/p2p/wallet/updates/SocketUpdatesManager.kt
app/src/main/java/org/p2p/wallet/utils/NoOp.kt

https://p2pvalidator.atlassian.net/browse/PWN-5953
NoOp is no more
also extracted storage and room to separate module to make them readable

PWN-5953 - Replace NoOp -> Unit, small refactoring

---

ui-kit/src/main/res/layout/widget_send_details_input.xml

https://p2pvalidator.atlassian.net/browse/PWN-6779
PWN-6779 - font fix on new send screen

PWN-6779 - font fix on new send screen

---

.github/actions/setup-slack/action.yml
.github/workflows/android-release-workflow.yml
scripts/config.gradle

PWN-6722 - Testing release builds

---

app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt
app/src/main/java/org/p2p/wallet/user/repository/UserLocalRepository.kt
app/src/main/java/org/p2p/wallet/user/repository/UserRemoteRepository.kt

https://p2pvalidator.atlassian.net/browse/PWN-6593
fetch prices for new user tokens

PWN-6593 - fetch prices for new user tokens

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/p2p/wallet/deeplinks/AppDeeplinksManager.kt
app/src/main/java/org/p2p/wallet/home/HomeModule.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeContract.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt
app/src/main/java/org/p2p/wallet/infrastructure/InfrastructureModule.kt
app/src/main/java/org/p2p/wallet/intercom/IntercomDeeplinkManager.kt

https://p2pvalidator.atlassian.net/browse/PWN-6741

PWN-6741 - Add integration to Intercom deeplink universal link

---

app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-6782
do not requestFocus in case of OrcaSwapOpenedFrom.MAIN_SCREEN

PWN-6782 - OrcaSwap do not requestFocus

---

.github/workflows/android-develop-workflow.yml
.github/workflows/android-feature-workflow.yml

PWN-6722 - Jira manipulations

---

app/src/main/java/org/p2p/wallet/newsend/SendFeeRelayerManager.kt
app/src/main/java/org/p2p/wallet/newsend/model/NewSendButtonState.kt
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitSendDetailsWidget.kt

https://p2pvalidator.atlassian.net/browse/PWN-6783
PWN-6783 - fix error state when it is error on counting fees

PWN-6783 - fix error state when it is error on counting fees

---

app/src/main/res/layout/dialog_new_transaction_progress.xml

https://p2pvalidator.atlassian.net/browse/PWN-6561
PWN-6561 - fix background in dialog_new_transaction_progress

PWN-6561 - fix background in dialog_new_transaction_progress

---

.github/workflows/android-develop-workflow.yml
.github/workflows/android-feature-workflow.yml

PWN-6722 - Moved jira manipulations to a separate job

---

.github/workflows/android-develop-workflow.yml
.github/workflows/android-feature-workflow.yml
.github/workflows/android-release-workflow.yml

PWN-6722 - added feature manual builds for pull requests in release

---

app/src/main/java/org/p2p/wallet/newsend/model/NewSendButtonState.kt

https://p2pvalidator.atlassian.net/browse/PWN-6902
PWN-6902 - fix condition of Insufficient funds

PWN-6902 - fix condition of Insufficient funds

---

app/src/main/java/org/p2p/wallet/newsend/SendFeeRelayerManager.kt

https://p2pvalidator.atlassian.net/browse/PWN-6783

PWN-6783 - Fix bug with fee calculation on new send screen

---

app/src/main/java/org/p2p/wallet/history/interactor/HistoryFetchListResult.kt
app/src/main/java/org/p2p/wallet/history/interactor/stream/AccountStreamSource.kt
app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt
app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryFragment.kt
app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryPresenter.kt
app/src/main/res/layout/fragment_token_history.xml
app/src/main/res/layout/layout_token_history_error.xml
app/src/main/res/values/styles_fonts.xml

https://p2pvalidator.atlassian.net/browse/PWN-6353

PWN-6353 - Off ramp. History fixes

---

bash_scripts/slack_deploy_changelog.sh
scripts/changelog.gradle

PWN-6722 - changelog fixes

---

app/src/main/java/org/p2p/wallet/moonpay/repository/sell/MoonpaySellRemoteRepository.kt
app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadPresenter.kt
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitSellDetailsWidget.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/ViewExtensions.kt
ui-kit/src/main/res/layout/widget_sell_input_amount.xml

https://p2pvalidator.atlassian.net/browse/PWN-6891
fiat input for sell widget

PWN-6891 - fiat input for sell widget

---

app/src/main/java/org/p2p/wallet/newsend/ui/details/NewSendDetailsBottomSheet.kt

https://p2pvalidator.atlassian.net/browse/PWN-6616
PWN-6616 - show 0 $Token (0$) when there is no fee and no free transactions

PWN-6616 - fix for free transactions text

---

app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-6866
PWN-6866 - less then -> less than (typo fix)

PWN-6866 - less then -> less than (typo fix)

---

app/src/main/java/org/p2p/wallet/history/model/HistoryItem.kt
app/src/main/java/org/p2p/wallet/history/ui/history/HistoryFragment.kt
app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/MoonpayTransactionViewHolder.kt
app/src/main/java/org/p2p/wallet/moonpay/extensions/SellStubs.kt
app/src/main/java/org/p2p/wallet/moonpay/model/SellTransaction.kt
app/src/main/java/org/p2p/wallet/moonpay/model/SellTransactionAmounts.kt
app/src/main/java/org/p2p/wallet/moonpay/repository/sell/SellRepositoryMapper.kt
app/src/main/java/org/p2p/wallet/moonpay/repository/sell/SellTransactionFiatCurrency.kt
app/src/main/java/org/p2p/wallet/moonpay/serversideapi/MoonpayServerSideApi.kt
app/src/main/java/org/p2p/wallet/moonpay/ui/transaction/SellTransactionDetailsBottomSheet.kt
app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt
app/src/main/java/org/p2p/wallet/sell/ui/lock/SellLockedFragment.kt
app/src/main/java/org/p2p/wallet/sell/ui/lock/SellTransactionViewDetails.kt
app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadPresenter.kt
app/src/main/res/layout/layout_sell_transaction_details.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-6938
- replace all USD in Sell to selected fiat abbriviation
- design fixes

PWN-6938 - Off-ramp. Fiat formatting fixes

---

scripts/analytics.gradle
scripts/config.gradle

NO-TICKET - try to fix CI

---

scripts/analytics.gradle
scripts/config.gradle

Reverts p2p-org/key-app-android#1157

Revert "NO-TICKET - try to fix CI"

---

.github/actions/setup-project/action.yml
.github/workflows/android-develop-workflow.yml
.github/workflows/android-feature-workflow.yml
.github/workflows/android-release-workflow.yml
.gitignore
scripts/analytics.gradle
scripts/config.gradle
scripts/torus.gradle

PWN-6722 - Fix CI environment

---

app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-6858
switch currency mode and calculate new amount

PWN-6858 - sell widget switch currency

---

app/src/main/java/org/p2p/wallet/common/mvp/BaseMvpBottomSheet.kt
app/src/main/java/org/p2p/wallet/common/ui/bottomsheet/BaseBottomSheet.kt
app/src/main/java/org/p2p/wallet/common/ui/bottomsheet/BaseDoneBottomSheet.kt
app/src/main/java/org/p2p/wallet/root/DecorSystemBarsDelegate.kt
app/src/main/java/org/p2p/wallet/root/RootActivity.kt
app/src/main/res/values-v27/theme.xml
app/src/main/res/values/theme.xml

https://p2pvalidator.atlassian.net/browse/PWN-6978
add insets support for bottom sheet

PWN-6978 - add insets support for bottom sheet

---

app/src/main/java/org/p2p/wallet/common/mvp/BaseFragment.kt
app/src/main/java/org/p2p/wallet/root/DecorSystemBarsDelegate.kt
app/src/main/java/org/p2p/wallet/settings/ui/newreset/main/NewResetPinIntroFragment.kt
app/src/main/java/org/p2p/wallet/settings/ui/recovery/RecoveryKitFragment.kt
app/src/main/java/org/p2p/wallet/settings/ui/recovery/unlock_seed_phrase/SeedPhraseUnlockFragment.kt
app/src/main/java/org/p2p/wallet/settings/ui/recovery/user_seed_phrase/UserSeedPhraseFragment.kt
app/src/main/res/layout/fragment_recovery_kit.xml

https://p2pvalidator.atlassian.net/browse/PWN-6980
fixed system bars update, apply insets on some screens

PWN-6980 - fixed system bar, apply insets

---

app/src/main/java/org/p2p/wallet/auth/ui/onboarding/SliderFragment.kt
app/src/main/java/org/p2p/wallet/sell/ui/lock/SellLockedFragment.kt
app/src/main/res/layout/fragment_sell_lock.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-6879
fixed sell lock screen

PWN-6879 - fixed sell lock screen

---

app/src/main/java/org/p2p/wallet/auth/ui/onboarding/SliderFragment.kt
app/src/main/java/org/p2p/wallet/common/mvp/BaseFragment.kt
app/src/main/java/org/p2p/wallet/root/DecorSystemBarsDelegate.kt
app/src/main/java/org/p2p/wallet/sell/ui/error/SellErrorFragment.kt
app/src/main/java/org/p2p/wallet/sell/ui/lock/SellLockedFragment.kt
app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadContract.kt
app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadFragment.kt
app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadPresenter.kt
app/src/main/java/org/p2p/wallet/settings/ui/newreset/main/NewResetPinIntroFragment.kt
app/src/main/java/org/p2p/wallet/settings/ui/recovery/RecoveryKitFragment.kt
app/src/main/java/org/p2p/wallet/settings/ui/recovery/unlock_seed_phrase/SeedPhraseUnlockFragment.kt
app/src/main/java/org/p2p/wallet/settings/ui/recovery/user_seed_phrase/UserSeedPhraseFragment.kt
app/src/main/res/layout/fragment_recovery_kit.xml
app/src/main/res/layout/fragment_sell_lock.xml
app/src/main/res/layout/fragment_sell_payload.xml
app/src/main/res/values/strings.xml
core/src/main/java/org/p2p/core/utils/insets/InsetsExtensions.kt
core/src/main/res/values/ids.xml

https://p2pvalidator.atlassian.net/browse/PWN-6945
toolbar title, insets extensions

PWN-6945 - toolbar title, insets extensions

---

app/src/main/java/org/p2p/wallet/common/analytics/interactor/ScreensAnalyticsInteractor.kt
app/src/main/java/org/p2p/wallet/history/repository/remote/TransactionDetailsRpcRepository.kt
app/src/main/java/org/p2p/wallet/history/strategy/context/SolanaParsingContext.kt
app/src/main/java/org/p2p/wallet/history/strategy/types/UnknownParsingStrategy.kt
app/src/main/java/org/p2p/wallet/root/RootActivity.kt

more context on what transactions we couldn't parse
i know i know - we will have history service for that, but before that, i hope it helps and brings no harm

NO-TICKET - Add litle bit more logs for parsing context

---

app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/GatewayServiceInterceptor.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/MoonpayInterceptor.kt
app/src/main/java/org/p2p/wallet/moonpay/model/MoonpaySellError.kt
app/src/main/java/org/p2p/wallet/moonpay/repository/sell/MoonpaySellRemoteRepository.kt
app/src/main/java/org/p2p/wallet/moonpay/serversideapi/MoonpayServerSideApi.kt
app/src/main/java/org/p2p/wallet/sell/interactor/SellInteractor.kt

https://p2pvalidator.atlassian.net/browse/PWN-6463

PWN-6463 - Off-ramp. Fix cancel_transaction success handle

---

app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt
app/src/main/res/layout/activity_root.xml
app/src/main/res/layout/fragment_root_onboarding.xml
app/src/main/res/layout/fragment_swap_orca.xml
ui-kit/src/main/kotlin/org/p2p/uikit/atoms/UiKitRoundedImageView.kt

https://p2pvalidator.atlassian.net/browse/PWN-6974
https://p2pvalidator.atlassian.net/browse/PWN-6973
fix insets, UiKitRoundedImageView as ShapeableImageView

PWN-6973 PWN-6974 - fix insets, add ShapeableImageView

---

app/src/main/java/org/p2p/wallet/moonpay/ui/transaction/SellTransactionDetailsPresenter.kt
app/src/main/java/org/p2p/wallet/moonpay/ui/transaction/SellTransactionDetailsViewState.kt
app/src/main/java/org/p2p/wallet/sell/ui/lock/SellLockedFragment.kt
app/src/main/java/org/p2p/wallet/sell/ui/lock/SellLockedPresenter.kt
app/src/main/res/layout/layout_sell_transaction_details.xml
app/src/main/res/values/sell_strings.xml
app/src/main/res/values/strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-6977
https://p2pvalidator.atlassian.net/browse/PWN-6992
small ui fixes

PWN-6977, PWN-6992 - fix background, text

---

app/src/main/java/org/p2p/wallet/sell/ui/payload/CashOutButtonState.kt
app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadPresenter.kt
app/src/main/res/values/sell_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-6968
https://p2pvalidator.atlassian.net/browse/PWN-7013

PWN-6968 PWN-7013 - Off-ramp. Pre-release fixies

---

app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-7013
delay after first request

PWN-7013 - delay after first request

---

app/src/main/java/org/p2p/wallet/sell/ui/lock/SellLockedFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-7036
visible containerReceiver

PWN-7036 - visible containerReceiver

---

app/src/main/java/org/p2p/wallet/swap/interactor/orca/OrcaSwapInteractor.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapContract.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-7051

PWN-7051 - Swap state fixes

---

app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchErrorViewHolder.kt
app/src/main/java/org/p2p/wallet/send/ui/search/adapter/SearchViewHolder.kt
app/src/main/res/layout/dialog_send_confirm.xml
app/src/main/res/layout/fragment_send.xml
app/src/main/res/layout/fragment_transaction_transfer.xml
app/src/main/res/layout/item_search.xml
app/src/main/res/layout/item_search_invalid_result.xml

NO-TICKET
NO-TICKET - fix icons using content padding or frame to prevent issues with paddings

NO-TICKET - fix icons using content padding or frame to prevent issues with paddings

---

app/src/main/java/org/p2p/wallet/home/api/CoinGeckoApi.kt
app/src/main/java/org/p2p/wallet/home/api/CoinGeckoPriceResponse.kt
app/src/main/java/org/p2p/wallet/home/model/TokenConverter.kt
app/src/main/java/org/p2p/wallet/home/model/TokenPrice.kt
app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt
app/src/main/java/org/p2p/wallet/user/local/TokenListResponse.kt
app/src/main/java/org/p2p/wallet/user/repository/UserInMemoryRepository.kt
app/src/main/java/org/p2p/wallet/user/repository/UserLocalRepository.kt
app/src/main/java/org/p2p/wallet/user/repository/UserRemoteRepository.kt
app/src/main/java/org/p2p/wallet/user/repository/prices/TokenId.kt
app/src/main/java/org/p2p/wallet/user/repository/prices/TokenPricesRemoteRepository.kt
app/src/main/java/org/p2p/wallet/user/repository/prices/di/TokenPricesModule.kt
app/src/main/java/org/p2p/wallet/user/repository/prices/impl/TokenPricesCoinGeckoRepository.kt
app/src/main/java/org/p2p/wallet/user/repository/prices/impl/TokenPricesCryptoCompareRepository.kt
app/src/main/res/values/environment_config.xml
core/src/main/java/org/p2p/core/token/TokenData.kt

https://p2pvalidator.atlassian.net/browse/PWN-6865

PWN - 6865 - Fix Coingecko token price fetching

---

app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerTopUpInteractor.kt
app/src/main/java/org/p2p/wallet/newsend/SendFeeRelayerManager.kt
app/src/main/java/org/p2p/wallet/newsend/model/CalculationMode.kt
app/src/main/java/org/p2p/wallet/newsend/model/FeeRelayerState.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendFragment.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitSendDetailsWidget.kt

https://p2pvalidator.atlassian.net/browse/PWN-7046

PWN-7046 - Send state fixes

---

app/src/main/java/org/p2p/wallet/common/ui/widget/DoubleTextView.kt
app/src/main/java/org/p2p/wallet/send/ui/main/SendFragment.kt
ui-kit/build.gradle
ui-kit/src/main/kotlin/org/p2p/uikit/utils/ShapeAppearanceExtensions.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/ThemeExtensions.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/recycler/RoundedDecoration.kt

https://p2pvalidator.atlassian.net/browse/PWN-5814
RoundedDecoration, add `fun View.rippleBackground` for rounded ripple 
https://user-images.githubusercontent.com/121934748/216276631-ff6fe6bd-5681-4143-8fb4-e57269c63bab.mp4

PWN-5814 - add RoundedDecoration, rounded ripple background

---

app/src/main/java/org/p2p/wallet/auth/analytics/OnboardingAnalytics.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootPresenter.kt
app/src/main/java/org/p2p/wallet/common/analytics/constants/EventNames.kt
app/src/main/java/org/p2p/wallet/common/permissions/new/MultiplePermissionRequest.kt
app/src/main/java/org/p2p/wallet/common/permissions/new/PermissionExtensions.kt
app/src/main/java/org/p2p/wallet/common/permissions/new/SinglePermissionRequest.kt
app/src/main/java/org/p2p/wallet/home/analytics/BrowseAnalytics.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-6964

PWN-6964 - Push notifications allowed events

---

app/src/main/java/org/p2p/wallet/auth/analytics/GeneralAnalytics.kt
app/src/main/java/org/p2p/wallet/home/analytics/BrowseAnalytics.kt
app/src/main/java/org/p2p/wallet/sell/analytics/SellAnalytics.kt
app/src/main/java/org/p2p/wallet/sell/ui/information/SellInformationBottomSheet.kt
app/src/main/java/org/p2p/wallet/sell/ui/warning/SellOnlySolWarningBottomSheet.kt
app/src/main/java/org/p2p/wallet/swap/analytics/SwapAnalytics.kt

https://p2pvalidator.atlassian.net/browse/PWN-6962

PWN-6962 - Off-ramp. New analytics

---

.github/actions/setup-jira-review/action.yml
.github/actions/setup-jira-rft/action.yml
.github/workflows/android-develop-workflow.yml
.github/workflows/android-feature-workflow.yml
.github/workflows/android-release-workflow.yml
bash_scripts/slack_develop_changelog.sh
bash_scripts/slack_shortlog_changelog.sh

https://p2pvalidator.atlassian.net/browse/PWN-6722 

PWN-6722 - Jira&CI/CD manipulations

---

app/src/main/java/org/p2p/wallet/home/MainFragment.kt
app/src/main/res/layout/fragment_history.xml

https://p2pvalidator.atlassian.net/browse/PWN-5814
PWN-5814 - fix status bar to be smoke color like screen not like default bg
Screenshot 1 | Screenshot 2 | Screenshot 3

PWN-5814 - fix status bar to be smoke color like screen not like default bg

---

app/src/main/res/drawable/bg_rounded_rain_4.xml
app/src/main/res/layout/item_history_shimmer.xml
app/src/main/res/layout/view_history_shimmer.xml

https://p2pvalidator.atlassian.net/browse/PWN-6888
PWN-6888 - shimmer redesign done
Screenshot 1 | Screenshot 2 | Screenshot 3

PWN-6888 - shimmer redesign done

---

.idea/codeStyles/Project.xml
app/src/main/java/org/p2p/wallet/infrastructure/network/environment/NetworkServicesUrlProvider.kt
app/src/main/java/org/p2p/wallet/moonpay/repository/sell/MoonpayExternalCustomerIdProvider.kt
app/src/main/java/org/p2p/wallet/moonpay/ui/new/NewBuyFragment.kt

https://sentry.io/organizations/p2p-wallet/issues/3920981189/?project=6479084&referrer=release-issue-stream
https://sentry.io/organizations/p2p-wallet/issues/3920664910/?project=6479084&referrer=release-issue-stream

NO-TICKET - Fix some Sentry entries

---

.github/workflows/android-develop-workflow.yml

PWN-6722 - Added google-services.json file creation in develop workflow

---

.github/actions/setup-jira-rft/action.yml
.github/workflows/android-develop-workflow.yml

PWN-6722 - Moved commit step at the end

---

app/src/main/java/org/p2p/wallet/sell/ui/lock/SellLockedFragment.kt
app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadContract.kt
app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadFragment.kt
app/src/main/java/org/p2p/wallet/sell/ui/payload/SellPayloadPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-6994
https://p2pvalidator.atlassian.net/browse/PWN-6880
- the easiest way to check that we created sell transaction after moonpay widget is closed

PWN-6994 - Off-ramp. Determine sell transaction creation when chrometabs are closed

---

.github/workflows/android-develop-workflow.yml
.github/workflows/android-feature-workflow.yml
bash_scripts/slack_deploy_start_message.sh

https://p2pvalidator.atlassian.net/browse/PWN-6722 

PWN-6722 - Trigger options fixed 2

---

.github/workflows/android-develop-workflow.yml

PWN-6722 - Trigger options fixed

---

app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootFragment.kt

https://p2pvalidator.atlassian.net/browse/PWN-6994

PWN-6994 - Fix notification permission event value

---

.github/actions/setup-commit/action.yml

PWN-6722 - Conflicts resolving

---

.github/actions/setup-commit/action.yml
app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/HistorySellTransactionViewHolder.kt

PWN-6722 - Additional CI/CD improvements

---

app/src/main/java/org/p2p/wallet/history/model/HistoryItem.kt
app/src/main/java/org/p2p/wallet/history/model/HistoryTransaction.kt
app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewPresenter.kt
app/src/main/java/org/p2p/wallet/history/ui/token/adapter/HistoryAdapter.kt
app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/TransactionSwapViewHolder.kt
app/src/main/java/org/p2p/wallet/history/ui/token/adapter/holders/TransactionViewHolder.kt
app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt
ui-kit/src/main/kotlin/org/p2p/uikit/atoms/UiKitTransactionSwapImageView.kt

https://p2pvalidator.atlassian.net/browse/PWN-7187
Move UI mapping in HistoryItemMapper.kt and now viewHolders are totally simple

PWN-7187 - move UI mapping in HistoryItemMapper.kt and now viewHolders are totally simple

---

app/src/main/java/org/p2p/wallet/root/RootActivity.kt

hide splash if initial data already loaded

NO-TICKET - hide splash if initial data already loaded

---

.github/actions/setup-project/action.yml
.github/workflows/android-develop-workflow.yml
.github/workflows/android-feature-workflow.yml
.github/workflows/android-release-workflow.yml
bash_scripts/slack_shortlog_changelog.sh

PWN-6722 - Checking slack

---

app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidget.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidgetModel.kt
app/src/main/res/layout/fragment_jupiter_swap.xml
app/src/main/res/layout/widget_swap.xml
app/src/main/res/menu/menu_jupiter_swap.xml
app/src/main/res/values/swap_strings.xml
ui-kit/src/main/kotlin/org/p2p/uikit/utils/text/TextViewCellModel.kt

https://p2pvalidator.atlassian.net/browse/PWN - 7168
swap widget, fragment xml

PWN - 7168 - swap widget, fragment xml

---

app/src/main/java/org/p2p/wallet/home/ui/main/HomePresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-7222

PWN-7222 - Fix bug with buy screen

---

app/src/main/java/org/p2p/wallet/history/HistoryModule.kt
app/src/main/java/org/p2p/wallet/history/api/RpcHistoryServiceApi.kt
app/src/main/java/org/p2p/wallet/history/repository/remote/RpcHistoryRepository.kt
app/src/main/java/org/p2p/wallet/infrastructure/network/interceptor/RpcInterceptor.kt
app/src/main/java/org/p2p/wallet/rpc/RpcConstants.kt
app/src/main/res/values/environment_config.xml

https://p2pvalidator.atlassian.net/browse/PWN-5812

PWN-5812 - Change history environment config, to push service

---

app/src/main/java/org/p2p/wallet/auth/ui/onboarding/NewOnboardingFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootContract.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootFragment.kt
app/src/main/java/org/p2p/wallet/auth/ui/onboarding/root/OnboardingRootPresenter.kt
app/src/main/java/org/p2p/wallet/debug/settings/DebugSettingsAdapter.kt
app/src/main/java/org/p2p/wallet/deeplinks/AppDeeplinksManager.kt
app/src/main/java/org/p2p/wallet/deeplinks/DeeplinkUtils.kt
app/src/main/java/org/p2p/wallet/home/MainFragment.kt
app/src/main/java/org/p2p/wallet/intercom/IntercomDeeplinkManager.kt
app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt
app/src/main/java/org/p2p/wallet/restore/model/SeedPhraseVerifyResult.kt
app/src/main/java/org/p2p/wallet/restore/ui/seedphrase/SeedPhrasePresenter.kt
app/src/main/java/org/p2p/wallet/root/RootActivity.kt
app/src/main/java/org/p2p/wallet/root/RootListener.kt
app/src/main/java/org/p2p/wallet/settings/ui/reset/seedphrase/ResetSeedPhrasePresenter.kt
app/src/main/java/org/p2p/wallet/splash/SplashContract.kt
app/src/main/java/org/p2p/wallet/splash/SplashFragment.kt
app/src/main/java/org/p2p/wallet/splash/SplashPresenter.kt
app/src/main/res/layout/item_settings_debug_switch.xml
app/src/main/res/layout/item_settings_row_item.xml

https://p2pvalidator.atlassian.net/browse/PWN-7063

PWN-7063 - Deeplinks moved to onboarding screen

---

ui-kit/src/main/kotlin/org/p2p/uikit/components/finance_block/FinanceBlockViewHolder.kt
ui-kit/src/main/kotlin/org/p2p/uikit/components/finance_block/UiKitFinanceBlockView.kt

@NikolaiEmelianov fyi
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.p2p.wallet, PID: 8604
java.lang.IllegalStateException: Not bind yet
at org.p2p.uikit.components.finance_block.UiKitFinanceBlockView.getItem(UiKitFinanceBlockView.kt:29)
at org.p2p.uikit.components.finance_block.FinanceBlockViewHolder.getItem(FinanceBlockViewHolder.kt:22)
at org.p2p.uikit.components.finance_block.FinanceBlockViewHolder.bind(FinanceBlockViewHolder.kt:25)
at org.p2p.wallet.swap.ui.jupiter.tokens.SwapTokensAdapter.onBindViewHolder(SwapTokensFragment.kt:98)
at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
at …
```

NO-TICKET - Fix bind method for Finance block

---

app/src/main/java/org/p2p/wallet/history/analytics/HistoryAnalytics.kt
app/src/main/java/org/p2p/wallet/history/api/model/RpcHistorySwapTokenResponse.kt
app/src/main/java/org/p2p/wallet/history/interactor/mapper/RpcHistoryTransactionConverter.kt
app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryAmount.kt
app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryTransaction.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
app/src/main/java/org/p2p/wallet/transaction/interactor/TransactionBuilderInteractor.kt

https://p2pvalidator.atlassian.net/browse/PWN-5812

PWN-5812 - Provide amount values to all history domain entities

---

app/src/main/java/org/p2p/wallet/history/interactor/mapper/RpcHistoryTransactionConverter.kt
app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryTransaction.kt
app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-5813
PWN-5813 - connect amounts for Unknown and CreateAccount transactions

PWN-5813 - amounts for Unknown and CreateAccount

---

app/build.gradle.kts
app/src/main/java/org/p2p/wallet/restore/ui/seedphrase/SeedPhrasePresenter.kt
buildSrc/src/main/kotlin/org/p2p/wallet/android/library.gradle.kts

NO-TICKET - fix login by seed phrase caused by 6c0c8c65

---

app/src/main/java/org/p2p/wallet/swap/jupiter/domain/model/SwapTokenModel.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapContract.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/SwapButtonState.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/mapper/SwapButtonMapper.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/mapper/SwapWidgetMapper.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidget.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidgetModel.kt
app/src/main/res/layout/fragment_jupiter_swap.xml
app/src/main/res/layout/widget_swap.xml
app/src/main/res/values/swap_strings.xml
core/src/main/java/org/p2p/core/common/TextContainer.kt
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitSliderSolidButton.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/skeleton/SkeletonExtensions.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/text/TextViewCellModel.kt

swap presenter, mapping, autosize widget

PWN-7169 - swap presenter, mapping, autosize widget

---

app/src/main/java/org/p2p/wallet/swap/jupiter/domain/model/SwapTokenModel.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapState.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateAction.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateManager.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateRoutesRefresher.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateTokenAZeroHandler.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapContract.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/SwapButtonState.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/mapper/SwapButtonMapper.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/mapper/SwapWidgetMapper.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidget.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidgetModel.kt
app/src/main/res/layout/fragment_jupiter_swap.xml
app/src/main/res/layout/widget_swap.xml
app/src/main/res/values/swap_strings.xml
core/src/main/java/org/p2p/core/common/TextContainer.kt
ui-kit/src/main/kotlin/org/p2p/uikit/components/UiKitSliderSolidButton.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/skeleton/SkeletonExtensions.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/text/TextViewCellModel.kt

local feature token model, new actions

PWN-7169 - local feature token model, new actions

---

app/src/main/java/org/p2p/wallet/history/HistoryModule.kt
app/src/main/java/org/p2p/wallet/history/interactor/HistoryInteractor.kt
app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryTokenState.kt
app/src/main/java/org/p2p/wallet/history/repository/remote/HistoryRemoteRepository.kt
app/src/main/java/org/p2p/wallet/history/repository/remote/HistoryRepository.kt
app/src/main/java/org/p2p/wallet/history/repository/remote/MoonpayHistoryRemoteRepository.kt
app/src/main/java/org/p2p/wallet/history/repository/remote/RpcHistoryRepository.kt
app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewPresenter.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/mapper/SwapWidgetMapper.kt
solana/src/main/java/org/p2p/solanaj/model/types/RpcMapRequest.kt

https://p2pvalidator.atlassian.net/browse/PWN-5812

PWN-5812 - Fix paging state for token history screen

---

.github/workflows/android-develop-workflow.yml

PWN-6722 - Changed to merge commit check

---

.github/actions/setup-jira-rft/action.yml

PWN-6722 - Fixed Jira

---

.github/actions/setup-jira-rft/action.yml
.github/workflows/android-develop-workflow.yml

PWN-6722 check pull request

---

app/src/main/java/org/p2p/wallet/history/interactor/HistoryInteractor.kt
app/src/main/java/org/p2p/wallet/history/interactor/mapper/RpcHistoryTransactionConverter.kt
app/src/main/java/org/p2p/wallet/history/model/rpc/RpcFee.kt
app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryTransaction.kt
app/src/main/java/org/p2p/wallet/history/repository/remote/HistoryRepository.kt
app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetFragment.kt
app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsBottomSheetPresenter.kt
app/src/main/java/org/p2p/wallet/history/ui/detailsbottomsheet/HistoryTransactionDetailsContract.kt
app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewPresenter.kt
app/src/main/java/org/p2p/wallet/newsend/ui/NewSendPresenter.kt
app/src/main/java/org/p2p/wallet/transaction/interactor/TransactionBuilderInteractor.kt
app/src/main/java/org/p2p/wallet/transaction/ui/ProgressStateWidget.kt
app/src/main/res/values/history_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-5813
PWN-5813 - show proper error states for transaction details and fix coloring of fees

PWN-5813 - show proper error states for transaction details

---

core/src/main/java/org/p2p/core/common/TextContainer.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/skeleton/Shimmer.java
ui-kit/src/main/kotlin/org/p2p/uikit/utils/skeleton/SkeletonCellModel.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/skeleton/SkeletonDrawable.java
ui-kit/src/main/kotlin/org/p2p/uikit/utils/skeleton/SkeletonExtensions.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/text/TextViewCellModel.kt

skeleton drawable, small fixes
https://user-images.githubusercontent.com/121934748/220453164-a36fb33c-2c27-4bcc-b4c9-16b9f4273935.mp4

NO-TICKET - skeleton drawable, small fixes

---

app/src/main/java/org/p2p/wallet/history/ui/token/TokenHistoryFragment.kt
app/src/main/java/org/p2p/wallet/home/MainFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/swap/SwapModule.kt
app/src/main/java/org/p2p/wallet/swap/ui/SwapFragmentFactory.kt
app/src/main/java/org/p2p/wallet/swap/ui/orca/OrcaSwapFragment.kt

PWN-7169 - create swap fragment by ft

---

.github/workflows/pull-request-check.yml

PWN-6722 - Added pull request check for PRs in `feature` branches

---

app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/SwapTokensFragment.kt

PWN-7169 - navigate to token select

---

app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-7353

PWN-7353 - Hide error view after retry button clicked

---

.github/workflows/pull-request-check.yml
app/src/main/java/org/p2p/wallet/history/HistoryModule.kt
app/src/main/java/org/p2p/wallet/history/repository/remote/MoonpayHistoryRemoteRepository.kt
app/src/main/java/org/p2p/wallet/moonpay/ui/transaction/SellTransactionDetailsPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-7370

PWN-7370 - Fix moonpay details button actions

---

app/src/main/java/org/p2p/wallet/history/analytics/HistoryAnalytics.kt
app/src/main/java/org/p2p/wallet/history/ui/history/HistoryPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-7385
PWN-7385 - history opened event added

PWN-7385 - history opened event added

---

app/src/main/java/org/p2p/wallet/history/api/model/RpcHistoryStatusResponse.kt

https://p2pvalidator.atlassian.net/browse/PWN-7390

PWN-7390 - Fix failed transactions

---

app/src/main/java/org/p2p/wallet/history/model/rpc/RpcHistoryTransaction.kt
app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt

https://p2pvalidator.atlassian.net/browse/PWN-7352

PWN-7352 - Fix mint transaction icon

---

app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListView.kt
app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewContract.kt
app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewPresenter.kt
app/src/main/java/org/p2p/wallet/sell/interactor/HistoryItemMapper.kt

https://p2pvalidator.atlassian.net/browse/PWN-5812

PWN-5812 - Fix empty state

---

app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/SwapTokensFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/adapter/SwapTokenAItemDecoration.kt
app/src/main/res/layout/fragment_jupiter_swap_tokens.xml
ui-kit/src/main/kotlin/org/p2p/uikit/components/finance_block/FinanceBlockCellModel.kt
ui-kit/src/main/kotlin/org/p2p/uikit/components/finance_block/UiKitFinanceBlockView.kt

PWN-7169 - select token a decorator

---

app/src/main/java/org/p2p/wallet/common/di/AppScope.kt
app/src/main/java/org/p2p/wallet/feerelayer/interactor/FeeRelayerInteractor.kt
app/src/main/java/org/p2p/wallet/feerelayer/model/FeeCalculationState.kt
app/src/main/java/org/p2p/wallet/feerelayer/model/FeePoolsState.kt
app/src/main/java/org/p2p/wallet/feerelayer/model/FeeRelayerFee.kt
app/src/main/java/org/p2p/wallet/newsend/SendFeeRelayerManager.kt
app/src/main/java/org/p2p/wallet/newsend/interactor/SendInteractor.kt
app/src/main/java/org/p2p/wallet/newsend/model/NewSendButtonState.kt
app/src/main/java/org/p2p/wallet/newsend/model/SendSolanaFee.kt
app/src/main/java/org/p2p/wallet/solend/interactor/SolendDepositInteractor.kt
app/src/main/java/org/p2p/wallet/solend/interactor/SolendWithdrawInteractor.kt

https://p2pvalidator.atlassian.net/browse/PWN-7425
https://p2pvalidator.atlassian.net/browse/PWN-7426

PWN-7425 - Various fixes on Send screen

---

app/src/main/java/org/p2p/wallet/swap/SwapModule.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/interactor/SwapTokensInteractor.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/interactor/model/SwapTokenModel.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateManagerHolder.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/SwapTokensContract.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/SwapTokensFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/presenter/SearchSwapTokensMapper.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/presenter/SwapTokensAMapper.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/presenter/SwapTokensBMapper.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/presenter/SwapTokensCommonMapper.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/presenter/SwapTokensPresenter.kt
app/src/main/res/values/swap_strings.xml
ui-kit/src/main/kotlin/org/p2p/uikit/components/right_side/RightSideCellModel.kt
ui-kit/src/main/kotlin/org/p2p/uikit/components/right_side/UiKitRightSideView.kt
ui-kit/src/main/res/layout/widget_right_side_single_text_badge.xml

https://p2pvalidator.atlassian.net/browse/PWN-7174

PWN-7174 - New swap. Select token A and B

---

app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListView.kt
app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewContract.kt
app/src/main/java/org/p2p/wallet/history/ui/historylist/HistoryListViewPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-7323
- default parameters are evil!

PWN-7323 - Fix pull-to-refresh token history 

---

app/src/main/java/org/p2p/wallet/AppModule.kt
app/src/main/java/org/p2p/wallet/claim/ClaimModule.kt
app/src/main/java/org/p2p/wallet/claim/ui/ClaimContract.kt
app/src/main/java/org/p2p/wallet/claim/ui/ClaimFragment.kt
app/src/main/java/org/p2p/wallet/claim/ui/ClaimPresenter.kt
app/src/main/java/org/p2p/wallet/home/ui/main/HomeFragment.kt
app/src/main/java/org/p2p/wallet/home/ui/main/adapter/TokenToClaimViewHolder.kt
app/src/main/res/layout/fragment_claim.xml
app/src/main/res/values/bridges_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-7377
PWN-7377 - claim screen added (UI)

PWN-7377 - claim screen added (UI)

---

app/src/main/java/org/p2p/wallet/swap/SwapModule.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapState.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateAction.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateManager.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateRoutesRefresher.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/handler/SwapStateLoadingRoutesHandler.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/handler/SwapStateLoadingTransactionHandler.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/handler/SwapStateSwapLoadedHandler.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/handler/SwapStateTokenAZeroHandler.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapContract.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt
app/src/main/java/org/p2p/wallet/transaction/model/TransactionState.kt
app/src/main/java/org/p2p/wallet/transaction/model/TransactionStateSwapFailureReason.kt
app/src/main/java/org/p2p/wallet/transaction/ui/JupiterTransactionProgressBottomSheet.kt
app/src/main/java/org/p2p/wallet/transaction/ui/JupiterTransactionProgressBottomSheetListener.kt
app/src/main/java/org/p2p/wallet/transaction/ui/SwapTransactionBottomSheetData.kt
app/src/main/res/layout/dialog_jupiter_swap_transaction_progress.xml
app/src/main/res/values/swap_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-7120

PWN-7120 - New swap. Success bottom sheet and navigation

---

app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateManager.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateRoutesRefresher.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/presenter/SwapTokensPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-7114
- on TokenAInvalid state, list was not loaded

PWN-7114 - Fix swap tokens loading if state is wrong

---

app/src/main/java/org/p2p/wallet/restore/interactor/SeedPhraseInteractor.kt
app/src/main/java/org/p2p/wallet/swap/SwapModule.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/interactor/model/SwapTokenModel.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapRateTickerManager.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapState.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateManager.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/SwapStateRoutesRefresher.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/handler/SwapStateLoadingRoutesHandler.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/rate/SwapRateTickerManager.kt
app/src/main/java/org/p2p/wallet/swap/model/jupiter/SwapRateTickerState.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapContract.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/mapper/SwapRateTickerMapper.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/settings/JupiterSwapSettingsContract.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/settings/JupiterSwapSettingsFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/settings/presenter/JupiterSwapSettingsPresenter.kt
app/src/main/java/org/p2p/wallet/user/interactor/UserInteractor.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/text/TextViewCellModel.kt

https://p2pvalidator.atlassian.net/browse/PWN-7452

PWN-7452 - Swap rate ticker added

---

app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/handler/SwapStateTokenAZeroHandler.kt
app/src/main/java/org/p2p/wallet/swap/jupiter/statemanager/token_selector/CommonSwapTokenSelector.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapContract.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/mapper/SwapButtonMapper.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/mapper/SwapWidgetMapper.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidget.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/widget/SwapWidgetModel.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/SwapTokensContract.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/SwapTokensFragment.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/tokens/presenter/SwapTokensPresenter.kt
app/src/main/res/layout/fragment_jupiter_swap.xml
app/src/main/res/layout/fragment_jupiter_swap_tokens.xml
app/src/main/res/values/swap_strings.xml

https://p2pvalidator.atlassian.net/browse/PWN-7451
https://p2pvalidator.atlassian.net/browse/PWN-7456
https://p2pvalidator.atlassian.net/browse/PWN-7458
https://p2pvalidator.atlassian.net/browse/PWN-7481
https://p2pvalidator.atlassian.net/browse/PWN-7484

PWN-7451 - Various Swap fixes

---

app/src/main/java/org/p2p/wallet/swap/jupiter/interactor/JupiterSwapInteractor.kt
app/src/main/java/org/p2p/wallet/swap/ui/jupiter/main/JupiterSwapPresenter.kt

https://p2pvalidator.atlassian.net/browse/PWN-7177
for reference: https://solana.fm/tx/5wfP9jZiuwDAAg1YwYA1pwoguHre21dGJTuzR7v1F9HEoqw89ciETcw26G7D9y64m8GNpjnh7CNBkfVXxEozvzjc?cluster=mainnet-solanafmbeta

PWN-7177 - New swap. Detect RPC low slippage error

---

ui-kit/src/main/kotlin/org/p2p/uikit/utils/skeleton/SkeletonCellModel.kt
ui-kit/src/main/kotlin/org/p2p/uikit/utils/skeleton/SkeletonDrawable.kt

https://p2pvalidator.atlassian.net/browse/PWN-7463
fix skeleton drawable

PWN-7463 - fix skeleton drawable
